(()=>{
'use strict';
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const KEY='garang_v99_state_v1';
let state={profile:null,workouts:[],meals:[],runs:[],body:[],memory:{facts:[],preferences:[],goals:[],events:[]},plan:'FREE'};
let db={exercise:[],food:[]}; let firebaseReady=false; let currentUser=null; let currentPage='home'; let runTimer=null; let runState=null; let mediaDB=null;
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2300)}
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');state={...state,...x};}catch{} state.workouts??=[];state.meals??=[];state.runs??=[];state.body??=[];state.memory??={facts:[],preferences:[],goals:[],events:[]};}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state)); if(firebaseReady&&currentUser) cloudSave().catch(()=>{});}
async function cloudSave(){const fs=firebase.firestore(); await fs.collection('users').doc(currentUser.uid).set({profile:state.profile,workouts:state.workouts.slice(-100),meals:state.meals.slice(-100),runs:state.runs.slice(-100),body:state.body.slice(-100),memory:state.memory,plan:state.plan,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});}
async function cloudLoad(){if(!firebaseReady||!currentUser)return;const d=await firebase.firestore().collection('users').doc(currentUser.uid).get();if(d.exists){const x=d.data();state={...state,...x};saveLocalOnly();}}
function saveLocalOnly(){localStorage.setItem(KEY,JSON.stringify(state))}
async function loadDB(){try{db.exercise=await fetch('exercise-db.json').then(r=>r.json());db.food=await fetch('food-db.json').then(r=>r.json());}catch(e){console.warn(e)}}
function initFirebase(){try{if(window.GARANG_FIREBASE_CONFIG?.apiKey&&!firebase.apps.length)firebase.initializeApp(window.GARANG_FIREBASE_CONFIG);firebaseReady=!!firebase.apps.length; if(firebaseReady) firebase.auth().onAuthStateChanged(async u=>{currentUser=u;if(u){await cloudLoad().catch(()=>{});state.plan=state.plan||'FREE';showApp()} else if(!localStorage.getItem('garang_demo'))showAuth();});}catch(e){firebaseReady=false;console.warn('Firebase unavailable',e)}}
function showAuth(){$('authView').hidden=false;$('appView').hidden=true}
function showApp(){$('authView').hidden=true;$('appView').hidden=false;$('planBadge').textContent=state.plan==='PRO'?'PRO':'FREE';render()}
function bindAuth(){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('loginForm').hidden=b.dataset.authTab!=='login';$('signupForm').hidden=b.dataset.authTab!=='signup'});$('loginForm').onsubmit=async e=>{e.preventDefault();await emailAuth(false)};$('signupForm').onsubmit=async e=>{e.preventDefault();await emailAuth(true)};$('resetPassword').onclick=resetPassword;$('googleBtn').onclick=()=>socialAuth('google');$('appleBtn').onclick=()=>socialAuth('apple');$('demoBtn').onclick=()=>{localStorage.setItem('garang_demo','1');state.profile=state.profile||{name:'GARANG 사용자',age:23,height:174,weight:67,targetWeight:67,goal:'퍼포먼스 향상',activity:'high'};saveState();showApp()};$('logoutBtn').onclick=logout}
async function emailAuth(signup){if(!firebaseReady){toast('Firebase 설정을 확인해 주세요.');return}try{const email=$(signup?'signupEmail':'loginEmail').value.trim(),pw=$(signup?'signupPassword':'loginPassword').value;if(signup){const c=await firebase.auth().createUserWithEmailAndPassword(email,pw);await c.user.updateProfile({displayName:email.split('@')[0]});}else await firebase.auth().signInWithEmailAndPassword(email,pw);toast(signup?'계정이 생성됐어요.':'로그인됐어요.')}catch(e){toast(firebaseError(e))}}
async function socialAuth(kind){if(!firebaseReady){toast('Firebase 설정을 확인해 주세요.');return}try{const p=kind==='google'?new firebase.auth.GoogleAuthProvider():new firebase.auth.OAuthProvider('apple.com');await firebase.auth().signInWithPopup(p)}catch(e){toast(firebaseError(e))}}
async function resetPassword(){if(!firebaseReady)return toast('Firebase 설정을 확인해 주세요.');const email=$('loginEmail').value.trim();if(!email)return toast('이메일을 먼저 입력해 주세요.');try{await firebase.auth().sendPasswordResetEmail(email);toast('재설정 메일을 보냈어요.')}catch(e){toast(firebaseError(e))}}
function firebaseError(e){const c=e?.code||'';const map={'auth/invalid-credential':'이메일 또는 비밀번호가 올바르지 않아요.','auth/email-already-in-use':'이미 사용 중인 이메일이에요.','auth/weak-password':'비밀번호는 6자 이상이어야 해요.','auth/popup-closed-by-user':'로그인이 취소됐어요.','auth/operation-not-allowed':'Firebase Console에서 해당 로그인 방식을 활성화해 주세요.','auth/unauthorized-domain':'Firebase Authentication의 승인 도메인을 확인해 주세요.'};return map[c]||e?.message||'인증 중 오류가 발생했어요.'}
function logout(){if(firebaseReady&&currentUser)firebase.auth().signOut();localStorage.removeItem('garang_demo');currentUser=null;showAuth()}
function nav(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;render()})}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage));const m=$('main');m.innerHTML=pages[currentPage]();bindPage();}
const pages={
home:()=>{const w=state.workouts[0],m=state.meals.reduce((a,x)=>a+x.kcal,0),p=state.meals.reduce((a,x)=>a+x.protein,0),last=state.body.at(-1)||{};return `<div class="page-head"><div><span class="eyebrow">TODAY</span><h1>${esc(state.profile?.name||'GARANG 사용자')}의 오늘</h1><p class="muted">기록이 쌓일수록 GARANG의 코칭도 정확해져요.</p></div><button class="ghost" id="profileBtn">프로필</button></div><div class="card hero-card"><span class="eyebrow">GARANG COACH</span><h2>${coachHeadline()}</h2><p class="muted">${coachSummary()}</p><div class="actions"><button class="primary" data-pagego="workout">오늘 운동 기록</button><button class="ghost" data-pagego="ai">AI에게 물어보기</button></div></div><div class="section-title"><h2>오늘의 상태</h2><span class="pill">${state.plan}</span></div><div class="grid grid-4"><div class="card"><div class="stat">${state.workouts.length}</div><div class="stat-label">운동 기록</div></div><div class="card"><div class="stat">${Math.round(m)}</div><div class="stat-label">섭취 kcal</div></div><div class="card"><div class="stat">${Math.round(p)}g</div><div class="stat-label">단백질</div></div><div class="card"><div class="stat">${last.weight?last.weight+'kg':'—'}</div><div class="stat-label">최근 체중</div></div></div><div class="section-title"><h2>최근 기록</h2></div><div class="grid grid-2"><div class="card"><h3>최근 운동</h3>${w?`<div class="metric-row"><span>${esc(w.name)}</span><b>${w.volume||0} kg</b></div><div class="metric-row"><span>RPE</span><b>${w.rpe||'—'}</b></div>`:`<div class="empty">아직 운동 기록이 없어요.</div>`}</div><div class="card"><h3>오늘 식단</h3>${state.meals.length?state.meals.slice(-4).reverse().map(x=>`<div class="metric-row"><span>${esc(x.name)}</span><b>${Math.round(x.kcal)} kcal</b></div>`).join(''):`<div class="empty">오늘 식단을 기록해 보세요.</div>`}</div></div>`},
workout:()=>`<div class="page-head"><div><span class="eyebrow">WORKOUT</span><h1>운동 기록</h1><p class="muted">세트·중량·RPE·볼륨과 인증까지 한 번에.</p></div></div><div class="grid grid-2"><div class="card"><h3>운동 추가</h3><div class="form-grid"><div class="field full"><label>운동</label><input id="wName" list="exerciseList" placeholder="벤치프레스"><datalist id="exerciseList">${db.exercise.slice(0,500).map(x=>`<option value="${esc(x.exercise_name)}">`).join('')}</datalist></div><div class="field"><label>세트</label><input id="wSets" type="number" min="1" value="3"></div><div class="field"><label>반복</label><input id="wReps" type="number" min="1" value="10"></div><div class="field"><label>중량 kg</label><input id="wWeight" type="number" min="0" step="0.5" value="60"></div><div class="field"><label>RPE</label><input id="wRpe" type="number" min="1" max="10" step="0.5" value="8"></div><div class="field"><label>운동 시간 분</label><input id="wDuration" type="number" min="1" value="45"></div><div class="field"><label>체중 kg</label><input id="wBody" type="number" min="1" step="0.1" value="${state.profile?.weight||67}"></div></div><div class="actions" style="margin-top:13px"><button id="saveWorkout" class="primary">운동 저장</button><button id="certWorkout" class="ghost">인증 사진 추가</button></div></div><div class="card"><h3>운동 인증</h3><p class="muted">사진/영상을 선택하면 GARANG 인증 오버레이가 함께 표시됩니다.</p><div id="workoutCertArea" class="empty">아직 선택한 미디어가 없어요.</div></div></div><div class="section-title"><h2>최근 운동</h2></div><div class="card"><div class="list">${state.workouts.slice().reverse().slice(0,12).map(w=>`<div class="list-item"><div><strong>${esc(w.name)}</strong><div class="muted">${w.date} · ${w.sets}×${w.reps} · ${w.weight}kg · RPE ${w.rpe}</div></div><span class="pill">${w.volume}kg</span></div>`).join('')||'<div class="empty">기록이 없습니다.</div>'}</div></div>`,
nutrition:()=>`<div class="page-head"><div><span class="eyebrow">NUTRITION</span><h1>식단</h1><p class="muted">내장 영양 DB에서 찾아 kcal와 영양정보를 자동으로 채웁니다.</p></div></div><div class="grid grid-2"><div class="card"><h3>음식 검색</h3><div class="field"><label>음식/메뉴</label><input id="foodSearch" list="foodList" placeholder="닭가슴살, 흰쌀밥"><datalist id="foodList">${db.food.slice(0,1000).map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist></div><div class="form-grid" style="margin-top:12px"><div class="field"><label>섭취량 g</label><input id="foodGram" type="number" value="100"></div><div class="field"><label>kcal</label><input id="foodKcal" type="number" value="0"></div><div class="field"><label>단백질 g</label><input id="foodProtein" type="number" value="0"></div><div class="field"><label>탄수화물 g</label><input id="foodCarb" type="number" value="0"></div><div class="field"><label>지방 g</label><input id="foodFat" type="number" value="0"></div></div><div class="actions" style="margin-top:13px"><button id="fillFood" class="ghost">DB 영양정보 불러오기</button><button id="saveMeal" class="primary">식단 저장</button></div></div><div class="card"><h3>오늘 누적</h3><div class="grid grid-2"><div><div class="stat">${Math.round(state.meals.reduce((a,x)=>a+x.kcal,0))}</div><div class="stat-label">kcal</div></div><div><div class="stat">${Math.round(state.meals.reduce((a,x)=>a+x.protein,0))}g</div><div class="stat-label">단백질</div></div><div><div class="stat">${Math.round(state.meals.reduce((a,x)=>a+x.carbs,0))}g</div><div class="stat-label">탄수화물</div></div><div><div class="stat">${Math.round(state.meals.reduce((a,x)=>a+x.fat,0))}g</div><div class="stat-label">지방</div></div></div></div></div><div class="section-title"><h2>최근 식단</h2></div><div class="card"><div class="list">${state.meals.slice().reverse().slice(0,15).map(x=>`<div class="list-item"><div><strong>${esc(x.name)}</strong><div class="muted">${x.date} · ${x.grams}g · P ${Math.round(x.protein)}g</div></div><span class="pill">${Math.round(x.kcal)} kcal</span></div>`).join('')||'<div class="empty">기록이 없습니다.</div>'}</div></div>`,
running:()=>`<div class="page-head"><div><span class="eyebrow">RUNNING</span><h1>러닝</h1><p class="muted">위치 권한을 허용하면 GPS로 거리와 경로를 기록합니다.</p></div></div><div class="grid grid-2"><div class="card"><div class="grid grid-3"><div><div class="stat" id="runDistance">0.00</div><div class="stat-label">km</div></div><div><div class="stat" id="runTime">00:00</div><div class="stat-label">시간</div></div><div><div class="stat" id="runPace">—</div><div class="stat-label">분/km</div></div></div><div class="map-box" style="margin-top:18px"><div class="map-grid"></div><svg class="route" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline id="routeLine" points="8,84 25,70 42,75 58,50 74,58 91,25" opacity=".18"></polyline></svg><div class="map-note" id="gpsStatus">GPS 대기 중</div></div><div class="actions" style="margin-top:13px"><button id="runStart" class="primary">GPS 러닝 시작</button><button id="runStop" class="ghost">정지 & 저장</button><button id="runCert" class="ghost">인증 사진</button></div></div><div class="card"><h3>러닝 인증</h3><div id="runCertArea" class="empty">미디어를 선택하면 러닝 인증 카드가 생성됩니다.</div></div></div><div class="section-title"><h2>러닝 기록</h2></div><div class="card"><div class="list">${state.runs.slice().reverse().slice(0,12).map(x=>`<div class="list-item"><div><strong>${x.distance.toFixed(2)} km</strong><div class="muted">${x.date} · ${x.duration}분 · ${x.pace} /km</div></div><span class="pill">${x.kcal} kcal</span></div>`).join('')||'<div class="empty">기록이 없습니다.</div>'}</div></div>`,
ai:()=>`<div class="page-head"><div><span class="eyebrow">GARANG INTELLIGENCE</span><h1>GARANG AI</h1><p class="muted">개인 기록·오늘 상태·Memory·Learning을 함께 보고 답합니다.</p></div></div><div class="grid grid-2"><div class="card coach-box"><h3>무엇을 도와줄까?</h3><textarea id="aiQuestion" placeholder="예: 최근 운동 기록을 보고 다음 가슴 운동 강도를 정해줘."></textarea><div class="actions" style="margin-top:12px"><button id="askAI" class="primary">코칭 받기</button><button class="ghost" data-q="최근 운동을 분석해줘">최근 운동 분석</button><button class="ghost" data-q="오늘 단백질을 얼마나 더 먹어야 해?">식단 분석</button></div><div class="coach-answer" id="aiAnswer" style="margin-top:18px">질문을 입력하면 GARANG이 답합니다.</div></div><div class="card"><h3>AI Memory</h3><div class="metric-row"><span>장기 사실</span><b>${state.memory.facts?.length||0}</b></div><div class="metric-row"><span>선호</span><b>${state.memory.preferences?.length||0}</b></div><div class="metric-row"><span>목표</span><b>${state.memory.goals?.length||0}</b></div><div class="metric-row"><span>이벤트</span><b>${state.memory.events?.length||0}</b></div><div class="section-title"><h2>Learning</h2></div><p class="muted">운동·식단·대화 기록을 기반으로 다음 답변에 사용할 개인 상태를 계속 업데이트합니다.</p></div></div><div class="section-title"><h2>PRO</h2></div><div class="card pro-lock"><strong>${state.plan==='PRO'?'PRO가 활성화되어 있어요.':'GARANG PRO'}</strong><p>${state.plan==='PRO'?'고급 코칭·리포트 기능을 사용할 수 있습니다.':'FREE에서는 핵심 기록과 기본 코칭을 사용할 수 있습니다. 결제 연결 전에는 테스트용으로 PRO 전환을 사용할 수 있습니다.'}</p><button id="togglePro" class="ghost">${state.plan==='PRO'?'FREE로 전환':'PRO 테스트 활성화'}</button></div>`,
profile:()=>`<div class="page-head"><div><span class="eyebrow">PROFILE</span><h1>내 GARANG</h1></div></div><div class="card"><div class="form-grid"><div class="field"><label>닉네임</label><input id="pName" value="${esc(state.profile?.name||'')}" placeholder="닉네임"></div><div class="field"><label>나이</label><input id="pAge" type="number" value="${state.profile?.age||''}"></div><div class="field"><label>키 cm</label><input id="pHeight" type="number" step=".1" value="${state.profile?.height||''}"></div><div class="field"><label>체중 kg</label><input id="pWeight" type="number" step=".1" value="${state.profile?.weight||''}"></div><div class="field full"><label>목표</label><input id="pGoal" value="${esc(state.profile?.goal||'')}" placeholder="예: 근육량 증가 / 체지방 감량"></div></div><div class="actions" style="margin-top:13px"><button id="saveProfile" class="primary">프로필 저장</button><button id="addBody" class="ghost">현재 체중 기록</button></div></div><div class="section-title"><h2>신체 기록</h2></div><div class="card"><div class="list">${state.body.slice().reverse().slice(0,10).map(x=>`<div class="list-item"><span>${x.date}</span><b>${x.weight} kg</b></div>`).join('')||'<div class="empty">체중 기록이 없습니다.</div>'}</div></div>`
};
function coachHeadline(){const last=state.workouts.at(-1);if(!last)return '첫 기록부터 시작해볼까?';if(last.rpe>=9)return '지난 운동 강도가 높았어. 오늘은 회복을 고려하자.';return `${last.name} 기록을 기준으로 다음 한 걸음을 잡아볼게.`}
function coachSummary(){const p=state.profile||{};const prot=state.meals.reduce((a,x)=>a+x.protein,0);const target=Math.round((p.weight||67)*1.6);return `현재 체중 ${p.weight||'—'}kg · 오늘 단백질 ${Math.round(prot)}g · 권장 최소 약 ${target}g. 기록을 계속 쌓으면 더 개인화된 추천을 만들 수 있어.`}
function bindPage(){document.querySelectorAll('[data-pagego]').forEach(b=>b.onclick=()=>{currentPage=b.dataset.pagego;render()});document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{currentPage='ai';render();$('aiQuestion').value=b.dataset.q;askAI()});$('profileBtn')?.addEventListener('click',()=>{currentPage='profile';render()});
 if(currentPage==='workout'){let media=null;$('saveWorkout').onclick=saveWorkout;$('certWorkout').onclick=()=>pickMedia(m=>{media=m;showCert('workoutCertArea',m,state.workouts.at(-1))});}
 if(currentPage==='nutrition'){$('foodSearch').addEventListener('input',()=>fillFood(false));$('fillFood').onclick=()=>fillFood(true);$('saveMeal').onclick=saveMeal}
 if(currentPage==='running'){$('runStart').onclick=startRun;$('runStop').onclick=stopRun;$('runCert').onclick=()=>pickMedia(m=>showCert('runCertArea',m,state.runs.at(-1)))}
 if(currentPage==='ai'){$('askAI').onclick=askAI;$('togglePro').onclick=()=>{state.plan=state.plan==='PRO'?'FREE':'PRO';saveState();render()};$('aiQuestion').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')askAI()})}
 if(currentPage==='profile'){$('saveProfile').onclick=saveProfile;$('addBody').onclick=()=>{const w=Number($('pWeight').value);if(!w)return toast('체중을 입력해 주세요.');state.body.push({date:today(),weight:w});state.profile={...(state.profile||{}),weight:w};saveState();render();}}
}
function today(){return new Date().toISOString().slice(0,10)}
function saveProfile(){state.profile={name:$('pName').value.trim()||'GARANG 사용자',age:Number($('pAge').value)||null,height:Number($('pHeight').value)||null,weight:Number($('pWeight').value)||null,goal:$('pGoal').value.trim()||'퍼포먼스 향상'};state.memory.goals=[state.profile.goal];saveState();toast('프로필을 저장했어요.');render()}
function saveWorkout(){const name=$('wName').value.trim();if(!name)return toast('운동 종목을 입력해 주세요.');const sets=Number($('wSets').value)||1,reps=Number($('wReps').value)||1,weight=Number($('wWeight').value)||0,dur=Number($('wDuration').value)||45,body=Number($('wBody').value)||67,rpe=Number($('wRpe').value)||8;const met=5+(Math.max(0,rpe-6)*0.7);const kcal=Math.round(met*3.5*body/200*dur);const x={id:crypto.randomUUID(),date:today(),name,sets,reps,weight,rpe,duration:dur,kcal,volume:sets*reps*weight};state.workouts.push(x);state.memory.events.push({type:'workout',date:today(),text:`${name} ${sets}x${reps} ${weight}kg`});saveState();toast(`운동 저장 완료 · 약 ${kcal} kcal`);render()}
function findFood(q){q=q.trim().toLowerCase();if(!q)return null;return db.food.find(x=>x.name?.toLowerCase()===q)||db.food.find(x=>(x.aliases||[]).some(a=>String(a).toLowerCase()===q))||db.food.find(x=>x.name?.toLowerCase().includes(q))}
function fillFood(manual){const f=findFood($('foodSearch').value);if(!f){if(manual)toast('DB에서 음식을 찾지 못했어요. 직접 입력할 수 있어요.');return}const g=Number($('foodGram').value)||100,ratio=g/(Number(f.basis_g)||100);$('foodKcal').value=Math.round(f.kcal*ratio);$('foodProtein').value=(f.protein*ratio).toFixed(1);$('foodCarb').value=(f.carbs*ratio).toFixed(1);$('foodFat').value=(f.fat*ratio).toFixed(1);if(manual)toast(`${f.name} 영양정보를 불러왔어요.`)}
function saveMeal(){const name=$('foodSearch').value.trim();if(!name)return toast('음식을 입력해 주세요.');const g=Number($('foodGram').value)||100;const x={id:crypto.randomUUID(),date:today(),name,grams:g,kcal:Number($('foodKcal').value)||0,protein:Number($('foodProtein').value)||0,carbs:Number($('foodCarb').value)||0,fat:Number($('foodFat').value)||0};state.meals.push(x);saveState();toast('식단 저장 완료');render()}
function pickMedia(cb){const input=$('mediaPicker');input.value='';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const url=URL.createObjectURL(f);cb({url,type:f.type,name:f.name})};input.click()}
function showCert(id,m,record){const area=$(id);area.className='cert';const isVideo=m.type.startsWith('video');area.innerHTML=`${isVideo?`<video src="${m.url}" controls muted playsinline></video>`:`<img src="${m.url}" alt="운동 인증 사진">`}<div class="cert-overlay"><div class="cert-brand">GARANG</div><div class="cert-bottom"><div><div class="muted">${esc(record?.name||'ACTIVITY')}</div><div class="cert-stat">${record?.weight?record.weight+' KG':'VERIFIED'}</div></div><div class="pill">${record?.date||today()}</div></div></div>`}
function startRun(){if(runState)return;runState={started:Date.now(),distance:0,coords:[]};$('gpsStatus').textContent='GPS 연결 중…';if(!navigator.geolocation)return toast('이 기기에서는 GPS를 사용할 수 없어요.');navigator.geolocation.watchId=navigator.geolocation.watchPosition(pos=>{runState.coords.push([pos.coords.latitude,pos.coords.longitude,pos.timestamp]);if(runState.coords.length>1){const a=runState.coords.at(-2),b=runState.coords.at(-1);runState.distance+=haversine(a[0],a[1],b[0],b[1]);}updateRunUI();$('gpsStatus').textContent=`GPS 연결 · ${pos.coords.latitude.toFixed(4)}, ${pos.coords.longitude.toFixed(4)}`},()=>{$('gpsStatus').textContent='GPS 권한 또는 신호를 확인해 주세요.'},{enableHighAccuracy:true,maximumAge:1000,timeout:10000});runTimer=setInterval(updateRunUI,1000);toast('GPS 러닝을 시작했어요.')}
function updateRunUI(){if(!runState)return;const sec=Math.floor((Date.now()-runState.started)/1000),min=Math.floor(sec/60),s=String(sec%60).padStart(2,'0');$('runDistance').textContent=runState.distance.toFixed(2);$('runTime').textContent=`${String(min).padStart(2,'0')}:${s}`;$('runPace').textContent=runState.distance>0?(sec/60/runState.distance).toFixed(2):'—'}
function stopRun(){if(!runState)return toast('진행 중인 러닝이 없어요.');if(navigator.geolocation.watchId)navigator.geolocation.clearWatch(navigator.geolocation.watchId);clearInterval(runTimer);const sec=Math.floor((Date.now()-runState.started)/1000),duration=sec/60,d=runState.distance,pace=d?duration/d:0,kcal=Math.round((d||0)*state.profile?.weight*1.0*1.036||0);const x={id:crypto.randomUUID(),date:today(),distance:d,duration,pace:pace.toFixed(2),kcal,coords:runState.coords};state.runs.push(x);state.memory.events.push({type:'run',date:today(),text:`${d.toFixed(2)}km 러닝`});saveState();runState=null;toast('러닝 저장 완료');render()}
function haversine(a,b,c,d){const R=6371,rad=Math.PI/180,da=(c-a)*rad,db=(d-b)*rad;const x=Math.sin(da/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(db/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function askAI(){const q=$('aiQuestion')?.value?.trim();if(!q)return toast('질문을 입력해 주세요.');$('aiAnswer').textContent='GARANG이 기록을 분석하고 있어요…';setTimeout(()=>{$('aiAnswer').textContent=generateAnswer(q)},250)}
function generateAnswer(q){const lower=q.toLowerCase(),last=state.workouts.at(-1),prot=state.meals.reduce((a,x)=>a+x.protein,0),target=Math.round((state.profile?.weight||67)*1.6);if(/식단|단백질|먹|영양/.test(lower)){const gap=Math.max(0,target-prot);return `현재 기록 기준 오늘 단백질은 약 ${Math.round(prot)}g이야. 최소 목표를 약 ${target}g으로 잡으면 ${Math.round(gap)}g 정도가 더 필요해. 식사마다 30~40g씩 나눠 채우는 게 현실적이야.`}if(/운동|벤치|스쿼트|데드|강도|rpe/.test(lower)){if(!last)return '아직 운동 기록이 없어서 정확한 조절은 어려워. 오늘 첫 운동을 기록하면 다음 세션부터 중량·볼륨·RPE를 연결해서 추천할게.';const suggestion=last.rpe>=9?'지난 세션 RPE가 높았으니 다음 세션은 같은 중량에서 반복을 확보하거나 볼륨을 10% 정도 낮추는 쪽이 좋아.':'지난 세션 강도가 관리되고 있어. 다음 세션은 같은 폼을 유지한다는 전제에서 2.5kg 증가 또는 1회 반복 증가 중 하나만 선택해.';return `최근 ${last.name} ${last.weight}kg × ${last.reps} × ${last.sets}세트, RPE ${last.rpe} 기록을 봤어. ${suggestion}`}if(/최근|상태|분석|어때/.test(lower)){return `현재 GARANG의 상태 요약: 운동 ${state.workouts.length}회, 식단 ${state.meals.length}건, 러닝 ${state.runs.length}회가 기록되어 있어. 오늘 단백질은 ${Math.round(prot)}g이고 최근 체중은 ${state.body.at(-1)?.weight||state.profile?.weight||'미기록'}kg야. 다음 단계는 기록을 더 쌓아서 피로·성과 변화까지 연결하는 거야.`}return `질문을 개인 데이터와 연결해서 판단하려면 운동·식단·러닝 기록이 많을수록 좋아. 현재 ${state.workouts.length}개 운동 기록과 ${state.meals.length}개 식단 기록을 사용하고 있어. 구체적으로 “다음 운동”, “오늘 식단”, “최근 상태”처럼 물어보면 더 정확하게 답할 수 있어.`}
async function boot(){loadState();await loadDB();bindAuth();nav();initFirebase();if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}if(localStorage.getItem('garang_demo'))showApp();else if(!firebaseReady)showAuth();}
boot();
})();