(() => {
'use strict';
const $ = id => document.getElementById(id);
const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid = () => (globalThis.crypto?.randomUUID ? crypto.randomUUID() : `g_${Date.now()}_${Math.random().toString(36).slice(2)}`);
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const KEY = 'garang_v99_state_v2';
let state = {profile:null,workouts:[],meals:[],runs:[],body:[],memory:{facts:[],preferences:[],goals:[],events:[]},plan:'FREE'};
let db = {exercise:[],food:[]};
let knowledge = [];
let firebaseReady = false, currentUser = null, currentPage = 'home';
let runTimer = null, runState = null;
let workoutDraft = [], mealDraft = [], currentCert = {workout:null,running:null};

function toast(msg){ const t=$('toast'); if(!t)return; t.textContent=msg; t.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>t.classList.remove('show'),2400); }
function safeNumber(v, fallback=0){ const n=Number(v); return Number.isFinite(n) ? n : fallback; }
function ensureMemory(){ state.memory ??= {}; for(const k of ['facts','preferences','goals','events']) state.memory[k]=Array.isArray(state.memory[k])?state.memory[k]:[]; }
function normalizeMeals(){
  const src=Array.isArray(state.meals)?state.meals:[];
  state.meals=src.map(m=>{
    const items=Array.isArray(m.items)&&m.items.length?m.items.map(i=>({id:i.id||uid(),name:String(i.name||'음식'),grams:safeNumber(i.grams,100),kcal:safeNumber(i.kcal),protein:safeNumber(i.protein),carbs:safeNumber(i.carbs??i.carbohydrate),fat:safeNumber(i.fat)})):[{id:uid(),name:String(m.name||'음식'),grams:safeNumber(m.grams,100),kcal:safeNumber(m.kcal),protein:safeNumber(m.protein),carbs:safeNumber(m.carbs),fat:safeNumber(m.fat)}];
    const totals=items.reduce((a,i)=>({kcal:a.kcal+i.kcal,protein:a.protein+i.protein,carbs:a.carbs+i.carbs,fat:a.fat+i.fat}),{kcal:0,protein:0,carbs:0,fat:0});
    return {...m,id:m.id||uid(),date:m.date||today(),name:m.name||items.map(i=>i.name).slice(0,2).join(' + '),items,...totals};
  });
}
function normalizeState(){
  state={...{profile:null,workouts:[],meals:[],runs:[],body:[],memory:{facts:[],preferences:[],goals:[],events:[]},plan:'FREE'},...state};
  for(const k of ['workouts','meals','runs','body']) state[k]=Array.isArray(state[k])?state[k]:[];
  state.plan=state.plan==='PRO'?'PRO':'FREE'; ensureMemory(); normalizeMeals();
}
function loadState(){ try{ const raw=localStorage.getItem(KEY); if(raw) state={...state,...JSON.parse(raw)}; }catch(e){console.warn('local state load failed',e)} normalizeState(); }
function saveLocalOnly(){ try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){toast('로컬 저장 공간을 확인해 주세요.');} }
function saveState(){ saveLocalOnly(); if(firebaseReady&&currentUser) cloudSave().catch(e=>console.warn('cloud save failed',e)); }
async function cloudSave(){
  if(!firebaseReady||!currentUser)return;
  const fs=firebase.firestore();
  await fs.collection('users').doc(currentUser.uid).set({profile:state.profile,workouts:state.workouts.slice(-200),meals:state.meals.slice(-200),runs:state.runs.slice(-200),body:state.body.slice(-200),memory:state.memory,plan:state.plan,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});
}
async function cloudLoad(){
  if(!firebaseReady||!currentUser)return;
  const d=await firebase.firestore().collection('users').doc(currentUser.uid).get();
  if(d.exists){ state={...state,...d.data()}; normalizeState(); saveLocalOnly(); }
}
async function loadJSON(path){ const r=await fetch(path,{cache:'no-store'}); if(!r.ok)throw new Error(`${path} ${r.status}`); return r.json(); }
async function loadJSONL(path){ const r=await fetch(path,{cache:'no-store'}); if(!r.ok)throw new Error(`${path} ${r.status}`); const text=await r.text(); return text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(x=>{try{return JSON.parse(x)}catch{return null}}).filter(Boolean); }
async function loadDB(){
  const results=await Promise.allSettled([loadJSON('exercise-db.json'),loadJSON('food-db.json'),loadJSONL('exercise_knowledge.jsonl'),loadJSONL('food_knowledge.jsonl'),loadJSONL('fitmind_rules.jsonl'),loadJSONL('fitmind_sft.jsonl'),loadJSONL('synthetic_korean_dialogue_v6.jsonl')]);
  if(results[0].status==='fulfilled')db.exercise=results[0].value;
  if(results[1].status==='fulfilled')db.food=results[1].value;
  knowledge=results.slice(2).filter(x=>x.status==='fulfilled').flatMap(x=>x.value).slice(0,2500);
  if(!db.exercise.length||!db.food.length)toast('운동/식단 DB 일부를 불러오지 못했어요.');
}
function initFirebase(){
  try{
    const cfg=window.GARANG_FIREBASE_CONFIG;
    if(!cfg?.apiKey||!window.firebase?.apps)return;
    if(!firebase.apps.length)firebase.initializeApp(cfg);
    firebaseReady=!!firebase.apps.length;
    if(firebaseReady)firebase.auth().onAuthStateChanged(async u=>{
      currentUser=u;
      if(u){ await cloudLoad().catch(e=>toast('계정 데이터 동기화에 실패했어요.')); state.plan=state.plan||'FREE'; showApp(); }
      else if(!localStorage.getItem('garang_demo'))showAuth();
    });
  }catch(e){firebaseReady=false;console.warn('Firebase unavailable',e);}
}
function showAuth(){$('authView').hidden=false;$('appView').hidden=true;}
function showApp(){$('authView').hidden=true;$('appView').hidden=false;$('planBadge').textContent=state.plan==='PRO'?'PRO':'FREE';render();}
function bindAuth(){
  document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('loginForm').hidden=b.dataset.authTab!=='login';$('signupForm').hidden=b.dataset.authTab!=='signup';});
  $('loginForm').onsubmit=async e=>{e.preventDefault();await emailAuth(false)};
  $('signupForm').onsubmit=async e=>{e.preventDefault();await emailAuth(true)};
  $('resetPassword').onclick=resetPassword; $('googleBtn').onclick=()=>socialAuth('google'); $('appleBtn').onclick=()=>socialAuth('apple');
  $('demoBtn').onclick=()=>{localStorage.setItem('garang_demo','1');state.profile=state.profile||{name:'GARANG 사용자',age:23,height:174,weight:67,targetWeight:67,goal:'퍼포먼스 향상',activity:'high'};saveState();showApp();};
  $('logoutBtn').onclick=logout;
}
async function emailAuth(signup){
  if(!firebaseReady)return toast('Firebase가 연결되지 않았어요. firebase-config.js와 Firebase 설정을 확인해 주세요.');
  try{const email=$(signup?'signupEmail':'loginEmail').value.trim(),pw=$(signup?'signupPassword':'loginPassword').value;if(signup){const c=await firebase.auth().createUserWithEmailAndPassword(email,pw);await c.user.updateProfile({displayName:email.split('@')[0]});}else await firebase.auth().signInWithEmailAndPassword(email,pw);toast(signup?'계정이 생성됐어요.':'로그인됐어요.');}catch(e){toast(firebaseError(e));}
}
async function socialAuth(kind){
  if(!firebaseReady)return toast('Firebase가 연결되지 않았어요.');
  try{const p=kind==='google'?new firebase.auth.GoogleAuthProvider():new firebase.auth.OAuthProvider('apple.com');await firebase.auth().signInWithPopup(p);}catch(e){toast(firebaseError(e));}
}
async function resetPassword(){if(!firebaseReady)return toast('Firebase가 연결되지 않았어요.');const email=$('loginEmail').value.trim();if(!email)return toast('이메일을 먼저 입력해 주세요.');try{await firebase.auth().sendPasswordResetEmail(email);toast('재설정 메일을 보냈어요.');}catch(e){toast(firebaseError(e));}}
function firebaseError(e){const c=e?.code||'';const map={'auth/invalid-credential':'이메일 또는 비밀번호가 올바르지 않아요.','auth/email-already-in-use':'이미 사용 중인 이메일이에요.','auth/weak-password':'비밀번호는 6자 이상이어야 해요.','auth/popup-closed-by-user':'로그인이 취소됐어요.','auth/operation-not-allowed':'Firebase Console에서 해당 로그인 방식을 활성화해 주세요.','auth/unauthorized-domain':'Firebase Authentication의 승인 도메인을 확인해 주세요.','auth/popup-blocked':'브라우저에서 팝업을 허용해 주세요.'};return map[c]||e?.message||'인증 중 오류가 발생했어요.';}
function logout(){if(firebaseReady&&currentUser)firebase.auth().signOut().catch(()=>{});localStorage.removeItem('garang_demo');currentUser=null;showAuth();}
function nav(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;render();});}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage));const m=$('main');m.innerHTML=pages[currentPage]();bindPage();}
function dayMeals(){return state.meals.filter(x=>x.date===today());}
function totalsMeals(){return dayMeals().reduce((a,x)=>({kcal:a.kcal+safeNumber(x.kcal),protein:a.protein+safeNumber(x.protein),carbs:a.carbs+safeNumber(x.carbs),fat:a.fat+safeNumber(x.fat)}),{kcal:0,protein:0,carbs:0,fat:0});}
function workoutKcalToday(){return state.workouts.filter(x=>x.date===today()).reduce((a,x)=>a+safeNumber(x.kcal),0);}
function coachHeadline(){const t=totalsMeals(), wk=state.workouts.filter(x=>x.date===today()).length;return wk?`${wk}개 운동 기록을 기준으로 다음 한 걸음을 잡아볼게.`:t.kcal?`오늘 식단과 활동을 기준으로 균형을 잡아볼게.`:'오늘의 데이터를 쌓아 GARANG의 기준선을 만들어보자.';}
function coachSummary(){const t=totalsMeals();return `현재 체중 ${state.profile?.weight||'—'}kg · 오늘 섭취 ${Math.round(t.kcal)} kcal · 단백질 ${Math.round(t.protein)}g · 운동 소모 약 ${Math.round(workoutKcalToday())} kcal`}
function pagesForHome(){const w=state.workouts.at(-1),t=totalsMeals(),last=state.body.at(-1)||{};return `<div class="page-head"><div><span class="eyebrow">TODAY</span><h1>${esc(state.profile?.name||'GARANG 사용자')}의 오늘</h1><p class="muted">기록이 쌓일수록 GARANG의 코칭도 정확해져요.</p></div><button class="ghost" id="profileBtn">프로필</button></div><div class="card hero-card"><span class="eyebrow">GARANG COACH</span><h2>${coachHeadline()}</h2><p class="muted">${coachSummary()}</p><div class="actions"><button class="primary" data-pagego="workout">오늘 운동 기록</button><button class="ghost" data-pagego="ai">AI에게 물어보기</button></div></div><div class="section-title"><h2>오늘의 상태</h2><span class="pill">${state.plan}</span></div><div class="grid grid-4"><div class="card"><div class="stat">${state.workouts.filter(x=>x.date===today()).length}</div><div class="stat-label">오늘 운동</div></div><div class="card"><div class="stat">${Math.round(t.kcal)}</div><div class="stat-label">섭취 kcal</div></div><div class="card"><div class="stat">${Math.round(t.protein)}g</div><div class="stat-label">단백질</div></div><div class="card"><div class="stat">${last.weight?last.weight+'kg':state.profile?.weight?state.profile.weight+'kg':'—'}</div><div class="stat-label">최근 체중</div></div></div><div class="section-title"><h2>오늘 운동 소모</h2><span class="pill">약 ${Math.round(workoutKcalToday())} kcal</span></div><div class="card"><div class="metric-row"><span>운동 세션</span><b>${new Set(state.workouts.filter(x=>x.date===today()).map(x=>x.sessionId||x.id)).size}개</b></div><div class="metric-row"><span>총 세트</span><b>${state.workouts.filter(x=>x.date===today()).reduce((a,x)=>a+safeNumber(x.sets),0)}</b></div><div class="metric-row"><span>총 볼륨</span><b>${Math.round(state.workouts.filter(x=>x.date===today()).reduce((a,x)=>a+safeNumber(x.volume),0)).toLocaleString()} kg</b></div></div><div class="section-title"><h2>최근 기록</h2></div><div class="grid grid-2"><div class="card"><h3>최근 운동</h3>${w?`<div class="metric-row"><span>${esc(w.name)}</span><b>${Math.round(w.kcal||0)} kcal</b></div><div class="metric-row"><span>볼륨</span><b>${Math.round(w.volume||0)} kg</b></div>`:`<div class="empty">아직 운동 기록이 없어요.</div>`}</div><div class="card"><h3>오늘 식단</h3>${dayMeals().length?dayMeals().slice().reverse().map(x=>`<div class="metric-row"><span>${esc(x.name)} · ${x.items.length}종</span><b>${Math.round(x.kcal)} kcal</b></div>`).join(''):`<div class="empty">오늘 식단을 기록해 보세요.</div>`}</div></div>`;}
function renderWorkoutDraft(){if(!workoutDraft.length)return '<div class="empty">아직 추가한 운동이 없어요. 위에서 운동을 추가하세요.</div>';return `<div class="list">${workoutDraft.map((x,i)=>`<div class="list-item"><div><strong>${esc(x.name)}</strong><div class="muted">${x.sets}×${x.reps} · ${x.weight}kg · RPE ${x.rpe} · ${x.duration}분 · MET ${x.met.toFixed(1)} · 약 ${Math.round(x.kcal)} kcal</div></div><div class="actions"><button class="ghost small" data-edit-workout="${i}">수정</button><button class="ghost small" data-remove-workout="${i}">삭제</button></div></div>`).join('')}</div>`;}
function renderMealDraft(){if(!mealDraft.length)return '<div class="empty">한 끼에 넣을 음식을 계속 추가하세요.</div>';return `<div class="list">${mealDraft.map((x,i)=>`<div class="list-item"><div><strong>${esc(x.name)}</strong><div class="muted">${x.grams}g · ${Math.round(x.kcal)} kcal · P ${Math.round(x.protein)}g · C ${Math.round(x.carbs)}g · F ${Math.round(x.fat)}g</div></div><div class="actions"><button class="ghost small" data-edit-food="${i}">수정</button><button class="ghost small" data-remove-food="${i}">삭제</button></div></div>`).join('')}</div>`;}
const pages={
 home:pagesForHome,
 workout:()=>`<div class="page-head"><div><span class="eyebrow">WORKOUT</span><h1>운동 기록</h1><p class="muted">한 세션에 여러 운동을 추가하고 운동별 MET·시간·체중 기반 소모 kcal를 계산합니다.</p></div></div><div class="grid grid-2"><div class="card"><h3>운동 추가</h3><div class="form-grid"><div class="field full"><label>운동</label><input id="wName" list="exerciseList" placeholder="바벨 벤치프레스"><datalist id="exerciseList">${db.exercise.slice(0,700).map(x=>`<option value="${esc(x.exercise_name)}">`).join('')}</datalist></div><div class="field"><label>세트</label><input id="wSets" type="number" min="1" value="3"></div><div class="field"><label>반복</label><input id="wReps" type="number" min="1" value="10"></div><div class="field"><label>중량 kg</label><input id="wWeight" type="number" min="0" step="0.5" value="60"></div><div class="field"><label>RPE</label><input id="wRpe" type="number" min="1" max="10" step="0.5" value="8"></div><div class="field"><label>운동 시간 분</label><input id="wDuration" type="number" min="1" value="15"></div><div class="field"><label>체중 kg</label><input id="wBody" type="number" min="1" step="0.1" value="${state.profile?.weight||67}"></div></div><div class="actions" style="margin-top:13px"><button id="addWorkout" class="primary">운동을 세션에 추가</button><button id="clearWorkoutDraft" class="ghost">초기화</button></div><div class="helper">운동 DB에 MET 기본값이 있으면 그대로 사용하고, RPE에 따라 완만하게 보정합니다.</div><div id="workoutDraftArea" class="draft-area" style="margin-top:16px">${renderWorkoutDraft()}</div><div class="session-total"><div><span>세션 총 소모</span><strong>${Math.round(workoutDraft.reduce((a,x)=>a+x.kcal,0))} kcal</strong></div><div><span>총 볼륨</span><strong>${Math.round(workoutDraft.reduce((a,x)=>a+x.volume,0)).toLocaleString()} kg</strong></div></div><button id="saveWorkoutSession" class="primary wide" style="margin-top:13px" ${workoutDraft.length?'':'disabled'}>운동 세션 저장</button></div><div class="card"><h3>운동 인증</h3><p class="muted">사진/영상을 선택하면 GARANG VERIFIED 오버레이를 실제 이미지에 합성할 수 있습니다.</p><div class="actions"><button id="certWorkout" class="ghost">사진/영상 선택</button></div><div id="workoutCertArea" class="empty" style="margin-top:12px">아직 선택한 미디어가 없어요.</div></div></div><div class="section-title"><h2>최근 운동</h2><span class="pill">오늘 약 ${Math.round(workoutKcalToday())} kcal</span></div><div class="card"><div class="list">${state.workouts.slice().reverse().slice(0,30).map(w=>`<div class="list-item"><div><strong>${esc(w.name)}</strong><div class="muted">${w.date} · ${w.sets}×${w.reps} · ${w.weight}kg · RPE ${w.rpe} · MET ${safeNumber(w.met,0).toFixed(1)} · 약 ${Math.round(w.kcal||0)} kcal</div></div><span class="pill">${Math.round(w.volume||0)}kg</span></div>`).join('')||'<div class="empty">기록이 없습니다.</div>'}</div></div>`,
 nutrition:()=>{const t=totalsMeals();return `<div class="page-head"><div><span class="eyebrow">NUTRITION</span><h1>식단</h1><p class="muted">한 끼에 여러 음식을 계속 추가하거나, 여러 줄로 한 번에 입력할 수 있습니다.</p></div></div><div class="grid grid-2"><div class="card"><h3>음식 추가</h3><div class="field"><label>음식/메뉴</label><input id="foodSearch" list="foodList" placeholder="닭가슴살"><datalist id="foodList">${db.food.slice(0,1500).map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist></div><div class="form-grid" style="margin-top:12px"><div class="field"><label>섭취량 g</label><input id="foodGram" type="number" min="1" value="100"></div><div class="field"><label>kcal</label><input id="foodKcal" type="number" value="0"></div><div class="field"><label>단백질 g</label><input id="foodProtein" type="number" value="0"></div><div class="field"><label>탄수화물 g</label><input id="foodCarb" type="number" value="0"></div><div class="field"><label>지방 g</label><input id="foodFat" type="number" value="0"></div></div><div class="actions" style="margin-top:13px"><button id="fillFood" class="ghost">DB 영양정보 불러오기</button><button id="addFood" class="primary">음식 추가</button></div><div class="field" style="margin-top:16px"><label>여러 음식 빠른 추가 · 한 줄에 <b>음식명, g</b></label><textarea id="foodBatch" rows="4" placeholder="닭가슴살, 200\n현미밥, 210\n계란, 100"></textarea><button id="addFoodBatch" class="ghost">여러 음식 한 번에 추가</button></div><div id="mealDraftArea" class="draft-area" style="margin-top:16px">${renderMealDraft()}</div><div class="session-total"><div><span>끼니 총 kcal</span><strong>${Math.round(mealDraft.reduce((a,x)=>a+x.kcal,0))} kcal</strong></div><div><span>P / C / F</span><strong>${Math.round(mealDraft.reduce((a,x)=>a+x.protein,0))} / ${Math.round(mealDraft.reduce((a,x)=>a+x.carbs,0))} / ${Math.round(mealDraft.reduce((a,x)=>a+x.fat,0))} g</strong></div></div><button id="saveMeal" class="primary wide" style="margin-top:13px" ${mealDraft.length?'':'disabled'}>한 끼 전체 저장</button></div><div class="card"><h3>오늘 누적</h3><div class="grid grid-2"><div><div class="stat">${Math.round(t.kcal)}</div><div class="stat-label">kcal</div></div><div><div class="stat">${Math.round(t.protein)}g</div><div class="stat-label">단백질</div></div><div><div class="stat">${Math.round(t.carbs)}g</div><div class="stat-label">탄수화물</div></div><div><div class="stat">${Math.round(t.fat)}g</div><div class="stat-label">지방</div></div></div></div></div><div class="section-title"><h2>오늘 식사</h2></div><div class="card"><div class="list">${dayMeals().slice().reverse().map(x=>`<div class="meal-card"><div class="metric-row"><strong>${esc(x.name)}</strong><b>${Math.round(x.kcal)} kcal</b></div><div class="meal-items">${x.items.map(i=>`<span>${esc(i.name)} ${i.grams}g · ${Math.round(i.kcal)} kcal</span>`).join('')}</div><div class="muted">P ${Math.round(x.protein)}g · C ${Math.round(x.carbs)}g · F ${Math.round(x.fat)}g</div></div>`).join('')||'<div class="empty">기록이 없습니다.</div>'}</div></div>`;},
 running:()=>`<div class="page-head"><div><span class="eyebrow">RUNNING</span><h1>러닝</h1><p class="muted">GPS 거리·페이스·소모 kcal를 기록하고 인증 미디어를 합성·저장하세요.</p></div></div><div class="grid grid-2"><div class="card"><div class="grid grid-3"><div><div class="stat" id="runDistance">0.00</div><div class="stat-label">km</div></div><div><div class="stat" id="runTime">00:00</div><div class="stat-label">시간</div></div><div><div class="stat" id="runPace">—</div><div class="stat-label">분/km</div></div></div><div class="map-box" style="margin-top:18px"><div class="map-grid"></div><svg class="route" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline id="routeLine" points="" opacity=".9"></polyline></svg><div class="map-note" id="gpsStatus">GPS 대기 중</div></div><div class="actions" style="margin-top:13px"><button id="runStart" class="primary">GPS 러닝 시작</button><button id="runStop" class="ghost">정지 & 저장</button><button id="runCert" class="ghost">인증 사진/영상</button></div></div><div class="card"><h3>러닝 인증</h3><div id="runCertArea" class="empty">미디어를 선택하면 러닝 인증 카드가 생성됩니다.</div></div></div><div class="section-title"><h2>러닝 기록</h2></div><div class="card"><div class="list">${state.runs.slice().reverse().slice(0,20).map(x=>`<div class="list-item"><div><strong>${Number(x.distance||0).toFixed(2)} km</strong><div class="muted">${x.date} · ${Number(x.duration||0).toFixed(1)}분 · ${x.pace} /km</div></div><span class="pill">${Math.round(x.kcal||0)} kcal</span></div>`).join('')||'<div class="empty">기록이 없습니다.</div>'}</div></div>`,
 ai:()=>`<div class="page-head"><div><span class="eyebrow">GARANG INTELLIGENCE</span><h1>GARANG AI</h1><p class="muted">현재 배포본은 외부 검색/LLM 서버가 아니라 로컬 코치 로직과 포함된 지식 데이터로 동작합니다.</p></div></div><div class="grid grid-2"><div class="card coach-box"><h3>무엇을 도와줄까?</h3><textarea id="aiQuestion" class="ai-input" rows="8" placeholder="예: 최근 운동 기록과 오늘 식단을 함께 보고 다음 가슴 운동 강도를 정해줘."></textarea><div class="actions" style="margin-top:12px"><button id="askAI" class="primary">코칭 받기</button><button class="ghost" data-q="최근 운동을 분석해줘">최근 운동 분석</button><button class="ghost" data-q="오늘 단백질을 얼마나 더 먹어야 해?">식단 분석</button></div><div class="coach-answer" id="aiAnswer" style="margin-top:18px">질문을 입력하면 GARANG이 답합니다.</div></div><div class="card"><h3>AI Memory</h3><div class="metric-row"><span>장기 사실</span><b>${state.memory.facts.length}</b></div><div class="metric-row"><span>선호</span><b>${state.memory.preferences.length}</b></div><div class="metric-row"><span>목표</span><b>${state.memory.goals.length}</b></div><div class="metric-row"><span>이벤트</span><b>${state.memory.events.length}</b></div><div class="helper" style="margin-top:12px">포함 지식 로드: ${knowledge.length.toLocaleString()}개 항목</div></div></div>`,
 profile:()=>`<div class="page-head"><div><span class="eyebrow">PROFILE</span><h1>프로필</h1></div></div><div class="card"><div class="form-grid"><div class="field"><label>이름</label><input id="pName" value="${esc(state.profile?.name||'')}"></div><div class="field"><label>나이</label><input id="pAge" type="number" value="${state.profile?.age||''}"></div><div class="field"><label>키 cm</label><input id="pHeight" type="number" value="${state.profile?.height||''}"></div><div class="field"><label>체중 kg</label><input id="pWeight" type="number" step="0.1" value="${state.profile?.weight||''}"></div><div class="field full"><label>목표</label><input id="pGoal" value="${esc(state.profile?.goal||'퍼포먼스 향상')}"></div></div><button id="saveProfile" class="primary" style="margin-top:13px">프로필 저장</button></div>`
};
function bindPage(){
  document.querySelectorAll('[data-pagego]').forEach(b=>b.onclick=()=>{currentPage=b.dataset.pagego;render();});
  document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{currentPage='ai';render();$('aiQuestion').value=b.dataset.q;askAI();});
  $('profileBtn')?.addEventListener('click',()=>{currentPage='profile';render();});
  if(currentPage==='workout'){
    $('addWorkout').onclick=addWorkoutDraft;$('clearWorkoutDraft').onclick=()=>{workoutDraft=[];render();};$('saveWorkoutSession').onclick=saveWorkoutSession;
    $('certWorkout').onclick=()=>pickMedia(m=>{currentCert.workout=m;showCert('workoutCertArea',m,state.workouts.at(-1),'workout');});
    document.querySelectorAll('[data-remove-workout]').forEach(b=>b.onclick=()=>{workoutDraft.splice(Number(b.dataset.removeWorkout),1);render();});
    document.querySelectorAll('[data-edit-workout]').forEach(b=>b.onclick=()=>editWorkout(Number(b.dataset.editWorkout)));
  }
  if(currentPage==='nutrition'){
    $('foodSearch').addEventListener('input',()=>fillFood(false));$('fillFood').onclick=()=>fillFood(true);$('addFood').onclick=addMealDraft;$('addFoodBatch').onclick=addMealBatch;$('saveMeal').onclick=saveMealGroup;
    document.querySelectorAll('[data-remove-food]').forEach(b=>b.onclick=()=>{mealDraft.splice(Number(b.dataset.removeFood),1);render();});
    document.querySelectorAll('[data-edit-food]').forEach(b=>b.onclick=()=>editMeal(Number(b.dataset.editFood)));
  }
  if(currentPage==='running'){$('runStart').onclick=startRun;$('runStop').onclick=stopRun;$('runCert').onclick=()=>pickMedia(m=>{currentCert.running=m;showCert('runCertArea',m,state.runs.at(-1),'running');});}
  if(currentPage==='ai'){$('askAI').onclick=askAI;autoGrow($('aiQuestion'));$('aiQuestion').addEventListener('input',()=>autoGrow($('aiQuestion')));}
  if(currentPage==='profile')$('saveProfile').onclick=saveProfile;
}
function autoGrow(el){if(!el)return;el.style.height='auto';el.style.height=Math.min(Math.max(el.scrollHeight,180),520)+'px';}
function exerciseFor(name){const q=String(name||'').trim().toLowerCase();return db.exercise.find(x=>String(x.exercise_name||'').toLowerCase()===q)||db.exercise.find(x=>String(x.exercise_name||'').toLowerCase().includes(q));}
function calcWorkoutKcal({duration,body,rpe,met}){const base=safeNumber(met,5);const intensity=1+Math.max(0,Math.min(10,safeNumber(rpe,7))-7)*0.04;return Math.max(1,Math.round(base*intensity*3.5*body/200*duration));}
function buildWorkout(){const name=$('wName').value.trim();if(!name)return toast('운동 종목을 입력해 주세요.');const ref=exerciseFor(name);const sets=Math.max(1,safeNumber($('wSets').value,1)),reps=Math.max(1,safeNumber($('wReps').value,1)),weight=Math.max(0,safeNumber($('wWeight').value)),rpe=Math.min(10,Math.max(1,safeNumber($('wRpe').value,8))),duration=Math.max(1,safeNumber($('wDuration').value,15)),body=Math.max(1,safeNumber($('wBody').value,state.profile?.weight||67));const met=safeNumber(ref?.met_default,5);return {id:uid(),name,sets,reps,weight,rpe,duration,body,met,kcal:calcWorkoutKcal({duration,body,rpe,met}),volume:sets*reps*weight};}
function addWorkoutDraft(){const x=buildWorkout();if(!x)return;workoutDraft.push(x);toast(`${x.name} 추가 · 약 ${Math.round(x.kcal)} kcal`);render();}
function editWorkout(i){const x=workoutDraft[i];if(!x)return;$('wName').value=x.name;$('wSets').value=x.sets;$('wReps').value=x.reps;$('wWeight').value=x.weight;$('wRpe').value=x.rpe;$('wDuration').value=x.duration;$('wBody').value=x.body;workoutDraft.splice(i,1);window.scrollTo({top:0,behavior:'smooth'});toast('운동 값을 수정한 뒤 다시 추가해 주세요.');}
function saveWorkoutSession(){if(!workoutDraft.length)return toast('먼저 운동을 추가해 주세요.');const sessionId=uid(),total=Math.round(workoutDraft.reduce((a,x)=>a+x.kcal,0));workoutDraft.forEach(x=>state.workouts.push({...x,date:today(),sessionId}));state.memory.events.push({type:'workout_session',date:today(),text:`${workoutDraft.length}종목 · ${total} kcal`});workoutDraft=[];saveState();toast(`운동 세션 저장 완료 · 약 ${total} kcal`);render();}
function findFood(q){q=String(q||'').trim().toLowerCase();if(!q)return null;return db.food.find(x=>String(x.name||'').toLowerCase()===q)||db.food.find(x=>(x.aliases||[]).some(a=>String(a).toLowerCase()===q))||db.food.find(x=>String(x.name||'').toLowerCase().includes(q));}
function foodItem(name,grams){const f=findFood(name);if(!f)return null;const g=Math.max(1,safeNumber(grams,100)),ratio=g/(safeNumber(f.basis_g,100));return {id:uid(),name:f.name,grams:g,kcal:safeNumber(f.kcal)*ratio,protein:safeNumber(f.protein)*ratio,carbs:safeNumber(f.carbs)*ratio,fat:safeNumber(f.fat)*ratio};}
function fillFood(manual){const f=findFood($('foodSearch').value);if(!f){if(manual)toast('DB에서 음식을 찾지 못했어요.');return;}const g=Math.max(1,safeNumber($('foodGram').value,100)),x=foodItem(f.name,g);$('foodKcal').value=Math.round(x.kcal);$('foodProtein').value=x.protein.toFixed(1);$('foodCarb').value=x.carbs.toFixed(1);$('foodFat').value=x.fat.toFixed(1);if(manual)toast(`${f.name} 영양정보를 불러왔어요.`);}
function addMealDraft(){const name=$('foodSearch').value.trim();if(!name)return toast('음식을 입력해 주세요.');const f=findFood(name),g=Math.max(1,safeNumber($('foodGram').value,100));const x=f?foodItem(f.name,g):{id:uid(),name,grams:g,kcal:safeNumber($('foodKcal').value),protein:safeNumber($('foodProtein').value),carbs:safeNumber($('foodCarb').value),fat:safeNumber($('foodFat').value)};if(!f&&!x.kcal&&!x.protein&&!x.carbs&&!x.fat)return toast('DB에서 음식을 찾지 못했어요. 먼저 DB 영양정보를 불러오거나 값을 입력해 주세요.');mealDraft.push(x);toast(`${x.name} 추가`);render();}
function addMealBatch(){const raw=$('foodBatch').value.trim();if(!raw)return toast('여러 음식 입력란을 채워 주세요.');let added=0,missing=[];for(const line of raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)){const m=line.match(/^(.+?)(?:\s*,\s*|\s+)\s*(\d+(?:\.\d+)?)\s*(?:g)?$/i);const name=(m?m[1]:line).trim(),grams=m?safeNumber(m[2],100):100;const x=foodItem(name,grams);if(x){mealDraft.push(x);added++;}else missing.push(name);}if(added){toast(`${added}개 음식을 한 번에 추가했어요.${missing.length?` 찾지 못한 음식 ${missing.length}개`:''}`);render();}else toast(`DB에서 찾지 못한 음식: ${missing.slice(0,3).join(', ')}`);}
function editMeal(i){const x=mealDraft[i];if(!x)return;$('foodSearch').value=x.name;$('foodGram').value=x.grams;$('foodKcal').value=Math.round(x.kcal);$('foodProtein').value=x.protein.toFixed(1);$('foodCarb').value=x.carbs.toFixed(1);$('foodFat').value=x.fat.toFixed(1);mealDraft.splice(i,1);window.scrollTo({top:0,behavior:'smooth'});toast('음식 값을 수정한 뒤 다시 추가해 주세요.');}
function saveMealGroup(){if(!mealDraft.length)return toast('먼저 음식을 추가해 주세요.');const totals=mealDraft.reduce((a,x)=>({kcal:a.kcal+x.kcal,protein:a.protein+x.protein,carbs:a.carbs+x.carbs,fat:a.fat+x.fat}),{kcal:0,protein:0,carbs:0,fat:0});const meal={id:uid(),date:today(),name:mealDraft.map(x=>x.name).slice(0,2).join(' + ')+(mealDraft.length>2?` 외 ${mealDraft.length-2}종`:''),items:mealDraft.map(x=>({...x})),...totals};state.meals.push(meal);state.memory.events.push({type:'meal',date:today(),text:`${meal.items.length}종 · ${Math.round(meal.kcal)} kcal`});mealDraft=[];saveState();toast(`한 끼 저장 완료 · ${Math.round(totals.kcal)} kcal`);render();}
function pickMedia(cb){const input=$('mediaPicker');input.value='';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const url=URL.createObjectURL(f);cb({url,type:f.type,name:f.name,file:f});};input.click();}
function recordForCert(kind){return kind==='running'?(state.runs.at(-1)||{date:today(),distance:0,duration:0,pace:'—',kcal:0}):(state.workouts.at(-1)||{date:today(),name:workoutDraft.at(-1)?.name||'WORKOUT',weight:workoutDraft.at(-1)?.weight||0,sets:workoutDraft.at(-1)?.sets||0,reps:workoutDraft.at(-1)?.reps||0,rpe:workoutDraft.at(-1)?.rpe||'—',kcal:workoutDraft.at(-1)?.kcal||0});}
function certInfo(record,kind){const r=record||recordForCert(kind);return kind==='running'?{title:'RUN VERIFIED',main:`${safeNumber(r.distance).toFixed(2)} KM`,meta:`${Number(r.duration||0).toFixed(1)} MIN · ${r.pace||'—'} /KM · ${Math.round(r.kcal||0)} KCAL · ${r.date||today()}`}:{title:'WORKOUT VERIFIED',main:`${r.name||'WORKOUT'} · ${r.weight||0} KG`,meta:`${r.sets||0} SETS · ${r.reps||0} REPS · RPE ${r.rpe||'—'} · ${Math.round(r.kcal||0)} KCAL · ${r.date||today()}`};}
function showCert(id,m,record,kind){const area=$(id);if(!area)return;const isVideo=m.type.startsWith('video'),info=certInfo(record,kind);area.className='cert';area.innerHTML=`<div class="cert-media"><${isVideo?'video':'img'} id="certMedia" src="${m.url}" ${isVideo?'controls muted playsinline':''} alt="GARANG 인증 미디어"></${isVideo?'video':'img'}><div class="cert-overlay-pro"><div class="overlay-top"><div class="overlay-brand"><img src="garang-mark.svg" alt="GARANG"><span>GARANG</span></div><span class="verified-chip">VERIFIED</span></div><div class="overlay-bottom"><span class="overlay-kicker">${info.title}</span><strong>${esc(info.main)}</strong><span class="overlay-meta">${esc(info.meta)}</span></div></div></div><div class="cert-controls"><button class="primary small" id="certSave">${isVideo?'영상 합성 저장/공유':'오버레이 이미지 저장'}</button><button class="ghost small" id="certShare">원본 공유</button></div>`;$('certSave').onclick=()=>isVideo?saveVideoWithOverlay(m,info):saveImageWithOverlay(m,info);$('certShare').onclick=()=>shareMedia(m);}
function drawOverlay(ctx,w,h,info){const pad=Math.max(18,w*0.035),size=Math.max(16,Math.min(34,w*0.045));const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'rgba(0,0,0,.58)');grad.addColorStop(.3,'rgba(0,0,0,0)');grad.addColorStop(.7,'rgba(0,0,0,0)');grad.addColorStop(1,'rgba(0,0,0,.72)');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.fillStyle='#d9ff45';ctx.font=`900 ${Math.round(size*.55)}px -apple-system,BlinkMacSystemFont,sans-serif`;ctx.letterSpacing='3px';ctx.fillText('GARANG',pad,pad+size*.55);ctx.fillStyle='#d9ff45';ctx.font=`900 ${Math.round(size*.55)}px -apple-system,BlinkMacSystemFont,sans-serif`;ctx.fillText(info.title,pad,h-pad-size*1.45);ctx.fillStyle='#fff';ctx.font=`900 ${Math.round(size*1.05)}px -apple-system,BlinkMacSystemFont,sans-serif`;ctx.fillText(info.main,pad,h-pad-size*.75);ctx.fillStyle='rgba(235,240,240,.9)';ctx.font=`700 ${Math.round(size*.42)}px -apple-system,BlinkMacSystemFont,sans-serif`;ctx.fillText(info.meta.slice(0,120),pad,h-pad);}
async function saveImageWithOverlay(m,info){try{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');const max=2400,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);drawOverlay(ctx,c.width,c.height,info);c.toBlob(async blob=>{if(!blob)return toast('이미지 합성에 실패했어요.');const file=new File([blob],`GARANG_${today()}_VERIFIED.jpg`,{type:'image/jpeg'});await shareOrDownloadBlob(file,blob,'GARANG_'+today()+'_VERIFIED.jpg');},'image/jpeg',.94);};img.onerror=()=>toast('이미지를 읽을 수 없어요.');img.src=m.url;}catch(e){toast('이미지 저장 중 오류가 발생했어요.');}}
async function saveVideoWithOverlay(m,info){
  if(!('MediaRecorder' in window)&&!HTMLCanvasElement.prototype.captureStream)return shareMedia(m);
  try{
    const v=document.createElement('video');v.src=m.url;v.muted=true;v.playsInline=true;await v.play();
    const c=document.createElement('canvas');c.width=v.videoWidth||1280;c.height=v.videoHeight||720;const ctx=c.getContext('2d');const stream=c.captureStream(30);let recorder;
    const mime=['video/mp4;codecs=h264','video/webm;codecs=vp9','video/webm'].find(x=>MediaRecorder.isTypeSupported?.(x))||'';recorder=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream);const chunks=[];recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);const done=new Promise(resolve=>recorder.onstop=()=>resolve(new Blob(chunks,{type:recorder.mimeType||'video/webm'})));recorder.start(250);const draw=()=>{if(v.paused||v.ended){recorder.stop();return;}ctx.drawImage(v,0,0,c.width,c.height);drawOverlay(ctx,c.width,c.height,info);requestAnimationFrame(draw);};draw();v.onended=()=>{try{recorder.stop();}catch{}};const blob=await done;const ext=(blob.type.includes('mp4')?'mp4':'webm');const file=new File([blob],`GARANG_${today()}_VERIFIED.${ext}`,{type:blob.type});await shareOrDownloadBlob(file,blob,file.name);}catch(e){console.warn('video overlay failed',e);toast('이 브라우저에서는 영상 합성이 제한돼 원본 공유로 전환합니다.');await shareMedia(m);}}
async function shareOrDownloadBlob(file,blob,name){try{if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'GARANG 인증',text:'GARANG FITNESS VERIFIED',files:[file]});toast('공유 창을 열었어요.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.rel='noopener';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('저장을 시작했어요. 모바일에서는 공유 메뉴를 사용할 수 있어요.');}catch(e){if(e?.name!=='AbortError')toast('브라우저 정책상 저장이 제한됩니다. 공유 메뉴를 이용해 주세요.');}}
async function shareMedia(m){try{if(navigator.share&&m.file&&navigator.canShare?.({files:[m.file]})){await navigator.share({title:'GARANG 인증',text:'GARANG FITNESS VERIFIED',files:[m.file]});toast('공유 창을 열었어요.');return;}const a=document.createElement('a');a.href=m.url;a.download=m.name;a.target='_blank';a.rel='noopener';a.click();toast('원본 파일 저장/열기를 시도했어요.');}catch(e){if(e?.name!=='AbortError')toast('공유/저장이 브라우저 정책으로 제한됐어요.');}}
function startRun(){if(runState)return;if(!navigator.geolocation)return toast('이 기기에서는 GPS를 사용할 수 없어요.');runState={started:Date.now(),distance:0,coords:[],watchId:null};$('gpsStatus').textContent='GPS 연결 중…';runState.watchId=navigator.geolocation.watchPosition(pos=>{const p=pos.coords;runState.coords.push([p.latitude,p.longitude,pos.timestamp]);if(runState.coords.length>1){const a=runState.coords.at(-2),b=runState.coords.at(-1);runState.distance+=haversine(a[0],a[1],b[0],b[1]);}updateRoute();updateRunUI();$('gpsStatus').textContent=`GPS 연결 · ${p.latitude.toFixed(4)}, ${p.longitude.toFixed(4)}`;},()=>{$('gpsStatus').textContent='GPS 권한 또는 신호를 확인해 주세요.';toast('GPS 권한 또는 위치 신호를 확인해 주세요.');},{enableHighAccuracy:true,maximumAge:1000,timeout:10000});runTimer=setInterval(updateRunUI,1000);toast('GPS 러닝을 시작했어요.');}
function updateRunUI(){if(!runState)return;const sec=Math.floor((Date.now()-runState.started)/1000),min=Math.floor(sec/60),s=String(sec%60).padStart(2,'0');$('runDistance').textContent=runState.distance.toFixed(2);$('runTime').textContent=`${String(min).padStart(2,'0')}:${s}`;$('runPace').textContent=runState.distance>0?(sec/60/runState.distance).toFixed(2):'—';}
function updateRoute(){const line=$('routeLine');if(!line||!runState?.coords.length)return;const pts=runState.coords;if(pts.length<2){line.setAttribute('points','50,50');return;}const lats=pts.map(p=>p[0]),lons=pts.map(p=>p[1]),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons),dLat=maxLat-minLat||1e-6,dLon=maxLon-minLon||1e-6;line.setAttribute('points',pts.map(p=>`${8+84*(p[1]-minLon)/dLon},${92-84*(p[0]-minLat)/dLat}`).join(' '));}
function stopRun(){if(!runState)return toast('진행 중인 러닝이 없어요.');if(runState.watchId!=null)navigator.geolocation.clearWatch(runState.watchId);clearInterval(runTimer);const sec=Math.max(1,Math.floor((Date.now()-runState.started)/1000)),duration=sec/60,d=runState.distance,pace=d?duration/d:0,body=safeNumber(state.profile?.weight,67),kcal=Math.round(d*body*1.036);const x={id:uid(),date:today(),distance:d,duration,pace:pace.toFixed(2),kcal,coords:runState.coords};state.runs.push(x);state.memory.events.push({type:'run',date:today(),text:`${d.toFixed(2)}km 러닝 · ${kcal} kcal`});runState=null;saveState();toast(`러닝 저장 완료 · 약 ${kcal} kcal`);render();}
function haversine(a,b,c,d){const R=6371,rad=Math.PI/180,da=(c-a)*rad,db=(d-b)*rad,x=Math.sin(da/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(db/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
function relevantKnowledge(q){const terms=String(q).toLowerCase().split(/\s+/).filter(x=>x.length>1).slice(0,8);return knowledge.map(item=>{const text=JSON.stringify(item).toLowerCase();const score=terms.reduce((s,t)=>s+(text.includes(t)?1:0),0);return {item,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(x=>x.item);}
function buildAIContext(){const t=totalsMeals();return {profile:state.profile,today:{meals:dayMeals(),mealTotals:t,workoutKcal:workoutKcalToday(),workouts:state.workouts.filter(x=>x.date===today()),runs:state.runs.filter(x=>x.date===today())},recentWorkouts:state.workouts.slice(-10),recentRuns:state.runs.slice(-10),memory:state.memory};}
function askAI(){const q=$('aiQuestion')?.value?.trim();if(!q)return toast('질문을 입력해 주세요.');$('aiAnswer').textContent='GARANG이 현재 기록과 포함 지식 데이터를 분석하고 있어요…';setTimeout(()=>{$('aiAnswer').textContent=generateAnswer(q);},120);}
function generateAnswer(q){const lower=q.toLowerCase(),ctx=buildAIContext(),last=state.workouts.at(-1),t=ctx.today.mealTotals,notes=relevantKnowledge(q);let answer='';if(/식단|단백질|먹|영양/.test(lower)){const target=Math.round((state.profile?.weight||67)*1.6),gap=Math.max(0,target-t.protein);answer=`오늘 기록 기준 단백질은 약 ${Math.round(t.protein)}g이야. 최소 목표를 약 ${target}g으로 잡으면 ${Math.round(gap)}g 정도 더 필요해. 오늘 섭취 ${Math.round(t.kcal)} kcal / P ${Math.round(t.protein)}g / C ${Math.round(t.carbs)}g / F ${Math.round(t.fat)}g까지 반영했어.`;}else if(/운동|벤치|스쿼트|데드|강도|rpe/.test(lower)){if(!last)answer='아직 운동 기록이 없어서 정확한 조절은 어려워. 첫 세션을 기록하면 중량·볼륨·RPE를 연결해서 추천할 수 있어.';else{const suggestion=last.rpe>=9?'지난 세션 RPE가 높았으니 같은 중량에서 반복을 확보하거나 총 볼륨을 5~10% 낮추는 쪽이 좋아.':'지난 세션 강도가 관리되고 있어. 폼이 유지된다는 전제에서 2.5kg 증가 또는 1회 반복 증가 중 하나만 선택해.';answer=`최근 ${last.name} ${last.weight}kg × ${last.reps} × ${last.sets}세트, RPE ${last.rpe}, 약 ${Math.round(last.kcal||0)} kcal 기록을 봤어. ${suggestion}`;}}else if(/최근|상태|분석|어때/.test(lower))answer=`현재 GARANG 상태: 오늘 운동 ${ctx.today.workouts.length}개, 식사 ${dayMeals().length}개, 러닝 ${ctx.today.runs.length}개. 오늘 섭취 ${Math.round(t.kcal)} kcal, 단백질 ${Math.round(t.protein)}g, 운동 소모 약 ${Math.round(ctx.today.workoutKcal)} kcal야.`;else answer=`현재 ${state.workouts.length}개 운동 기록, ${state.meals.length}개 식사 기록, ${state.runs.length}개 러닝 기록을 같은 사용자 상태로 연결해 보고 있어. 질문을 운동·식단·러닝 중 하나로 구체화하면 더 정확하게 답할 수 있어.`;if(notes.length)answer+=`\n\n[관련 로컬 지식 ${notes.length}개를 참고함]`;return answer;}
function saveProfile(){state.profile={name:$('pName').value.trim()||'GARANG 사용자',age:safeNumber($('pAge').value),height:safeNumber($('pHeight').value),weight:safeNumber($('pWeight').value),goal:$('pGoal').value.trim()||'퍼포먼스 향상'};saveState();toast('프로필을 저장했어요.');render();}
async function boot(){loadState();await loadDB();bindAuth();nav();initFirebase();if(localStorage.getItem('garang_demo'))showApp();else if(!firebaseReady)showAuth();}
boot();
})();
