/* Root scope worker. Only public static shell assets are cached; never API/user data. */
const CACHE='garang-final-'+encodeURIComponent(self.registration.scope)+'-1';
const ASSETS=['./','index.html','01_app/app.js','02_core/garang-v10-core.js','02_core/data-schema.js','04_data/ui-translations.js','04_data/ui-final-translations.js','services/storage.js','services/performance.js','services/records.js','services/adapters.js','06_features/final/features.js','07_config/firebase-config.js','07_config/services-config.js','07_config/manifest.webmanifest','03_styles/core/styles.css','03_styles/core/garang-v10-release.css','03_styles/features/garang-planner-v10.css','03_styles/features/final.css','03_styles/mobile/garang-v10.9-mobile-max.css','05_assets/garang-mark.svg','05_assets/icon-192.png','05_assets/icon-512.png','04_data/knowledge/exercise-db.json','04_data/knowledge/food-db.json','04_data/knowledge/exercise_knowledge.jsonl','04_data/knowledge/food_knowledge.jsonl','04_data/knowledge/fitmind_rules.jsonl','04_data/knowledge/fitmind_sft.jsonl','04_data/knowledge/synthetic_korean_dialogue_v6.jsonl'];
const allowed=new Set(ASSETS.map(x=>new URL(x,self.registration.scope).pathname));
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('garang-final-'+encodeURIComponent(self.registration.scope)+'-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET'||url.origin!==self.location.origin||!allowed.has(url.pathname))return;
 event.respondWith(fetch(event.request).then(response=>{if(response.ok){const copy=response.clone();event.waitUntil(caches.open(CACHE).then(cache=>cache.put(event.request,copy)));}return response;}).catch(async()=>{const cache=await caches.open(CACHE);const cached=await cache.match(event.request,{ignoreSearch:true});return cached||Response.error();}));
});
