
(function(){
'use strict';
const $=id=>document.getElementById(id);
function save85(){try{if(typeof save==='function')save();else localStorage.setItem('fitmind_v2',JSON.stringify(window.__FitMindV6DB?.()||{}));}catch(e){console.warn(e)}}
function ensure85(){const d=window.__FitMindV6DB?window.__FitMindV6DB():null;if(!d)return null;if(!Array.isArray(d.runs))d.runs=[];if(!d.onboarding)d.onboarding={complete:false,goal:'',sports:[],coachStyle:''};if(!d.profile)d.profile={};return d}
window.garangAsk=q=>{const i=$('chatInput');if(i){i.value=q;$('chatForm')?.dispatchEvent(new Event('submit',{cancelable:true,bubbles:true}));}};
window.newGarangChat=()=>{try{localStorage.removeItem('fitmind_chat_v77');const d=ensure85();if(d)d.chat=[];save85();if(typeof renderChat==='function')renderChat();}catch(e){} const l=$('chatLog');if(l)l.innerHTML='';};

function bindFullDBSelectors(){
 const ex=$('exercise');
 if(ex && ex.tagName==='SELECT') ex.addEventListener('change',()=>{const d=ensure85(),x=(typeof exerciseDB!=='undefined'?exerciseDB:[]).find(v=>v.exercise_name===ex.value);if(x){if($('sets'))$('sets').value=x.default_sets||'';if($('reps'))$('reps').value=x.default_reps||'';}});
 const meal=$('meal');
 if(meal && meal.tagName==='SELECT') meal.addEventListener('change',()=>{const f=(typeof foodDB!=='undefined'?foodDB:[]).find(v=>v.name===meal.value);if(f&&typeof window.selectFood==='function')window.selectFood(f.food_id);});
}
function onboardingData(){const d=ensure85();return d?.onboarding||{} }
let step=1;let data={goal:'',height:'',weight:'',targetWeight:'',experience:'beginner',sports:[],coachStyle:''};
function loadOn(){const d=ensure85();const p=d?.profile||{},o=d?.onboarding||{};data={goal:o.goal||p.goal||'',height:p.height||'',weight:p.weight||'',targetWeight:p.targetWeight||'',experience:p.experience||'beginner',sports:Array.isArray(o.sports)?o.sports:[],coachStyle:o.coachStyle||''};if($('onHeight'))$('onHeight').value=data.height;if($('onWeight'))$('onWeight').value=data.weight;if($('onTargetWeight'))$('onTargetWeight').value=data.targetWeight;if($('onExperience'))$('onExperience').value=data.experience;document.querySelectorAll('.choiceGrid[data-key]').forEach(g=>{const k=g.dataset.key;g.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',Array.isArray(data[k])?data[k].includes(b.dataset.value):data[k]===b.dataset.value));});renderStep();}
function renderStep(){document.querySelectorAll('.onboardStep').forEach(x=>x.classList.toggle('active',+x.dataset.step===step));if($('onboardingStepText'))$('onboardingStepText').textContent=step+' / 5';if($('onboardingProgress'))$('onboardingProgress').style.width=(step*20)+'%';if($('onPrev'))$('onPrev').style.visibility=step===1?'hidden':'visible';if($('onNext'))$('onNext').textContent=step===5?'GARANG 시작하기':'다음';if(step===5&&$('onboardSummary'))$('onboardSummary').innerHTML='<b>'+((data.goal||'목표 미설정'))+'</b><br>운동: '+(data.sports.join(', ')||'미설정')+'<br>코칭 스타일: '+(data.coachStyle||'미설정')+'<br>신체: '+(data.height||'-')+'cm · '+(data.weight||'-')+'kg';}
function collectStep(){if(step===1){const g=document.querySelector('.choiceGrid[data-key="goal"] .selected');data.goal=g?.dataset.value||data.goal;}if(step===2){data.height=+$('onHeight')?.value||0;data.weight=+$('onWeight')?.value||0;data.targetWeight=+$('onTargetWeight')?.value||0;data.experience=$('onExperience')?.value||'beginner';}if(step===3){data.sports=[...document.querySelectorAll('.choiceGrid[data-key="sports"] .selected')].map(b=>b.dataset.value)}if(step===4){data.coachStyle=document.querySelector('.choiceGrid[data-key="coachStyle"] .selected')?.dataset.value||data.coachStyle;}}
function finishOn(){const d=ensure85();if(!d)return;d.profile=Object.assign({},d.profile,{height:Number(data.height)||0,weight:Number(data.weight)||0,targetWeight:Number(data.targetWeight)||0,goal:data.goal,experience:data.experience});d.onboarding={complete:true,goal:data.goal,sports:data.sports,coachStyle:data.coachStyle,completedAt:new Date().toISOString()};if(d.profile.weight&&!d.body?.length)d.body=[{weight:d.profile.weight,date:new Date().toISOString().slice(0,10),note:'온보딩 초기 체중'}];save85();if(typeof fillProfileForm==='function')fillProfileForm();openPage('dashboard');}
$('onNext')?.addEventListener('click',()=>{collectStep();if(step<5){step++;renderStep()}else finishOn()});$('onPrev')?.addEventListener('click',()=>{collectStep();if(step>1){step--;renderStep()}});document.querySelectorAll('.choiceGrid').forEach(g=>g.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(g.classList.contains('multi'))b.classList.toggle('selected');else{g.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}}));
window.addEventListener('load',()=>{bindFullDBSelectors();setTimeout(()=>{if(window.fbAuth)fbAuth.onAuthStateChanged(u=>{if(!u)return;setTimeout(()=>{const d=ensure85();if(d&&!d.onboarding?.complete){loadOn();openPage('onboarding')}else{updateDash85();updateCoachInsight()}},650)},100);},300)});
window.garangStartOnboarding=()=>{step=1;loadOn();openPage('onboarding')};
function updateDash85(){const d=ensure85();if(!d)return;const today=new Date().toISOString().slice(0,10);if($('dashGreeting'))$('dashGreeting').textContent=(d.profile?.name?d.profile.name+'님, 오늘도 가볼까요?':'오늘도 가볼까요?');if($('dashWeight'))$('dashWeight').textContent=d.profile?.weight||'-';const ws=(d.workouts||[]).filter(x=>x.date===today),ms=(d.meals||[]).filter(x=>x.date===today),runs=(d.runs||[]).filter(x=>x.date===today);if($('dashWorkout'))$('dashWorkout').textContent=ws.length+runs.length;if($('dashMeals'))$('dashMeals').textContent=ms.length;const feed=$('dashActivityFeed');if(feed){const arr=[...ws.map(x=>({t:'운동',n:x.exercise||x.name||'운동',v:(x.volume||0)+' kg'})),...runs.map(x=>({t:'러닝',n:(Number(x.distance||0).toFixed(2))+' km',v:x.pace||'--'})),...ms.map(x=>({t:'식단',n:x.food||x.name||'식사',v:Math.round(x.calories||0)+' kcal'}))];feed.innerHTML=arr.length?arr.slice(-6).reverse().map(x=>`<div class="activityItem"><span><b>${esc85(x.n)}</b><small>${esc85(x.t)}</small></span><strong>${esc85(x.v)}</strong></div>`).join(''):'<p class="muted">아직 오늘의 기록이 없습니다.</p>';}if($('dashGoalProgress')){const goal=d.onboarding?.goal||d.profile?.goal||'목표';const count=ws.length+runs.length+ms.length;const pct=Math.min(100,Math.round(count/3*100));$('dashGoalProgress').innerHTML='<div><b>'+esc85(goal)+'</b><span class="muted"> 오늘 '+count+'개 활동</span></div><div class="progressBar"><i style="width:'+pct+'%"></i></div><small class="muted">하루 3개 핵심 기록을 기준으로 한 가벼운 체크</small>';}}
function updateCoachInsight(){const d=ensure85();if(!d||!$('coachInsightText'))return;const w=(d.workouts||[]).slice(-1)[0],r=(d.runs||[]).slice(-1)[0],m=(d.meals||[]).slice(-1)[0];let text='오늘 기록을 쌓으면 GARANG이 패턴을 분석해드려요.';if(w)text='최근 '+(w.exercise||w.name||'운동')+' 기록을 기준으로 다음 세션의 중량과 볼륨을 조절해볼 수 있어요.';if(r)text='최근 러닝 '+Number(r.distance||0).toFixed(2)+'km · '+(r.pace||'페이스 기록 없음')+' 기록을 바탕으로 다음 러닝을 설계할 수 있어요.';if(m&&!w&&!r)text='최근 식단 '+Math.round(m.calories||0)+'kcal 기록이 있어요. 오늘 총섭취와 단백질을 이어서 확인해보세요.';$('coachInsightText').textContent=text;if($('coachTip'))$('coachTip').textContent=text;}
function esc85(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
window.garangRenderProfile=()=>{const d=ensure85();if(!d)return;const p=d.profile||{};if($('profGoal'))$('profGoal').value=p.goal||''};
const oldOpen=window.openPage; if(oldOpen){window.openPage=function(id){oldOpen(id);if(id==='dashboard'){updateDash85();updateCoachInsight()}if(id==='chat')updateCoachInsight();if(id==='running'&&window.garangRenderRuns)window.garangRenderRuns();}};
// Apple sign-in: Firebase console must have Apple provider configured.
$('appleBtn')?.addEventListener('click',async()=>{try{if(!window.fbAuth)throw new Error('auth');const provider=new firebase.auth.OAuthProvider('apple.com');await fbAuth.signInWithPopup(provider)}catch(e){if($('authError'))$('authError').textContent='Apple 로그인은 Firebase에서 Apple 제공자를 활성화한 뒤 사용할 수 있습니다.'}});
})();
