/* GARANG HOT v1 — public source, no video re-upload. */
(() => {
'use strict';
if(window.GarangHotV1)return;
const VERSION='1.0.0',STORE_KEY='garang_hot_v1_state',ROUTINE_INTENT_KEY='garang_hot_v1_pending_routine';
const ALLOWED=new Set(['PR','TRANSFORM','ROUTINE','INTENSITY','COMEBACK','FIRST']);
let embedPromise=null,pendingShare=null;
const main=()=>document.getElementById('main'),root=()=>document.getElementById('garangHotRoot'),isKo=()=>document.documentElement.lang!=='en';
const uid=()=>globalThis.crypto?.randomUUID?crypto.randomUUID():'hot_'+Date.now()+'_'+Math.random().toString(36).slice(2);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function empty(){return{posts:[],reactions:{}}}
function read(){try{const x=JSON.parse(localStorage.getItem(STORE_KEY)||'null');if(x&&Array.isArray(x.posts)&&x.reactions&&typeof x.reactions==='object')return x}catch{}return empty()}
function write(x){try{x.posts=x.posts.slice(0,80);localStorage.setItem(STORE_KEY,JSON.stringify(x));return true}catch{return false}}
function toast(m){const t=document.getElementById('toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1900)}
function normalizeInstagramUrl(value){try{const u=new URL(String(value||'').trim());if(!/(^|\.)instagram\.com$/i.test(u.hostname))return null;const p=u.pathname.split('/').filter(Boolean),type=String(p[0]||'').toLowerCase();if(!['reel','reels','p'].includes(type)||!p[1])return null;return'https://www.instagram.com/'+type+'/'+encodeURIComponent(p[1])+'/'}catch{return null}}
function urlFromText(value){const m=String(value||'').match(/https?:\/\/[^\s]+/i);return m?normalizeInstagramUrl(m[0]):null}
function consumeShareTarget(){const q=new URLSearchParams(location.search);if(q.get('garangShare')!=='hot')return null;const shared=normalizeInstagramUrl(q.get('url'))||urlFromText(q.get('text'));if(shared)pendingShare={url:shared,caption:String(q.get('title')||'').slice(0,180)};['garangShare','title','text','url'].forEach(k=>q.delete(k));try{history.replaceState(history.state,'',location.pathname+(q.toString()?'?'+q.toString():'')+location.hash)}catch{}return pendingShare}
function reaction(s,id){const r=s.reactions[id]||{};return{fire:r.fire===true,why:r.why===true}}
function postMarkup(p,s){const r=reaction(s,p.id),cap=p.caption||(isKo()?'보고 끝내지 마. 너도 하면 된다.':'Do not just watch. Go do it.');return '<article class="garang-hot-post" data-hot-post="'+esc(p.id)+'"><div class="garang-hot-stage"><div class="garang-hot-fallback"><div><strong>INSTAGRAM REEL</strong><p>'+esc(cap)+'</p></div></div><div class="garang-hot-instagram" data-garang-hot-instagram data-ready="0"><blockquote class="instagram-media" data-instgrm-permalink="'+esc(p.url)+'" data-instgrm-version="14"></blockquote></div><div class="garang-hot-scrim"></div></div><div class="garang-hot-source-note">'+(isKo()?'Instagram 원본 출처 유지 · 영상 재업로드 없음':'Original Instagram source · no re-upload')+'</div><div class="garang-hot-meta"><div class="garang-hot-creator"><span class="garang-hot-avatar">G</span><span>'+esc(p.creator||'@instagram')+'</span><span class="garang-hot-source">INSTAGRAM</span></div><p class="garang-hot-caption">'+esc(cap)+'</p><div class="garang-hot-chips"><span class="garang-hot-chip">'+esc(p.category||'HOT')+'</span>'+(p.routine?'<span class="garang-hot-chip">'+esc(p.routine)+'</span>':'')+'</div>'+(p.routine?'<button class="garang-hot-routine" type="button" data-hot-action="routine" data-id="'+esc(p.id)+'">'+(isKo()?'이 루틴 해보기 →':'Try this routine →')+'</button>':'')+'<button class="garang-hot-source-link" type="button" data-hot-action="source" data-id="'+esc(p.id)+'">'+(isKo()?'원본 열기 ↗':'Open original ↗')+'</button></div><aside class="garang-hot-actions"><button class="garang-hot-action fire" type="button" data-hot-action="fire" data-id="'+esc(p.id)+'" data-active="'+(r.fire?'1':'0')+'"><span>🔥</span><b>FIRE</b><small>'+(r.fire?'ON':'')+'</small></button><button class="garang-hot-action why" type="button" data-hot-action="why" data-id="'+esc(p.id)+'" data-active="'+(r.why?'1':'0')+'"><span>WHY<br>NOT?</span><b>'+(isKo()?'나도 한다':'I am in')+'</b><small>'+(r.why?'GO':'')+'</small></button><button class="garang-hot-action" type="button" data-hot-action="share" data-id="'+esc(p.id)+'"><span>↗</span><b>'+(isKo()?'공유':'Share')+'</b><small>HOT</small></button></aside></article>'}
function sheetMarkup(){return '<div class="garang-hot-backdrop" data-hot-sheet hidden><section class="garang-hot-sheet" role="dialog" aria-modal="true"><div class="garang-hot-sheet-head"><div><span>GARANG HOT / EXTERNAL REEL</span><h2>'+(isKo()?'뜨거운 영상을 가져오기':'Bring the heat')+'</h2></div><button class="garang-hot-close" type="button" data-hot-close>×</button></div><form data-hot-form><div class="garang-hot-field"><label>Instagram public Reel URL</label><input name="url" inputmode="url" placeholder="https://www.instagram.com/reel/..." required></div><p class="garang-hot-help">'+(isKo()?'운동 행동을 부르는 공개 콘텐츠만. 영상 파일은 복제하지 않고 원본 출처를 유지합니다.':'Public fitness content that makes people move. Original source is preserved.')+'</p><div class="garang-hot-field"><label>'+(isKo()?'크리에이터':'Creator')+'</label><input name="creator" placeholder="@creator"></div><div class="garang-hot-field"><label>'+(isKo()?'왜 뜨거운 영상인가':'Why is it hot?')+'</label><textarea name="caption" maxlength="180" required></textarea></div><div class="garang-hot-field"><label>'+(isKo()?'분류':'Category')+'</label><select name="category"><option>PR</option><option>TRANSFORM</option><option>ROUTINE</option><option>INTENSITY</option><option>COMEBACK</option><option>FIRST</option></select></div><div class="garang-hot-field"><label>'+(isKo()?'연결할 루틴 이름 (선택)':'Routine name (optional)')+'</label><input name="routine" maxlength="80"></div><button class="garang-hot-submit" type="submit">'+(isKo()?'GARANG HOT에 공유':'Share to GARANG HOT')+'</button></form></section></div>'}
function render(){const mount=root();if(!mount)return;const s=read(),feed=s.posts.length?s.posts.map(p=>postMarkup(p,s)).join(''):'<div class="garang-hot-empty"><div><strong>SEE IT.<br>DO IT.</strong><p>'+(isKo()?'아무 영상이나 모으지 않습니다. 보고 나서 진짜 운동하고 싶어지는 공개 Reel만 HOT에 가져오세요.':'Bring only the public Reels that make you want to train.')+'</p><button type="button" data-hot-open>'+(isKo()?'첫 Reel 공유하기':'Share the first Reel')+'</button></div></div>';mount.innerHTML='<section class="garang-hot-shell"><header class="garang-hot-head"><strong>GARANG</strong><b>HOT</b><button class="garang-hot-import" type="button" data-hot-open>REEL +</button></header><div class="garang-hot-feed">'+feed+'</div>'+sheetMarkup()+'</section>';bind(mount);hydrate();if(pendingShare){openSheet(mount,pendingShare);pendingShare=null}}
function openSheet(mount,prefill){const sheet=mount.querySelector('[data-hot-sheet]'),form=sheet?.querySelector('[data-hot-form]');if(!sheet)return;sheet.hidden=false;if(form&&prefill){if(prefill.url)form.elements.url.value=prefill.url;if(prefill.caption)form.elements.caption.value=prefill.caption}requestAnimationFrame(()=>form?.elements?.url?.focus?.({preventScroll:true}))}
function closeSheet(mount){const s=mount.querySelector('[data-hot-sheet]');if(s)s.hidden=true}
function saveImport(form){const url=normalizeInstagramUrl(form.elements.url.value),caption=String(form.elements.caption.value||'').trim().slice(0,180),category=String(form.elements.category.value||'ROUTINE').toUpperCase();if(!url){toast(isKo()?'공개 Instagram Reel/Post URL을 확인해 주세요.':'Check the public Instagram URL.');return false}if(!caption){toast(isKo()?'왜 뜨거운 영상인지 한 줄을 적어 주세요.':'Explain why it is hot.');return false}if(!ALLOWED.has(category))return false;const s=read();if(s.posts.some(p=>p.url===url)){toast(isKo()?'이미 HOT에 있는 원본입니다.':'Already in HOT.');return false}s.posts.unshift({id:uid(),kind:'instagram',url,creator:String(form.elements.creator.value||'@instagram').trim().slice(0,80)||'@instagram',caption,category,routine:String(form.elements.routine.value||'').trim().slice(0,80),createdAt:new Date().toISOString()});write(s);toast(isKo()?'GARANG HOT에 추가했습니다.':'Added to GARANG HOT.');return true}
function toggle(id,type){const s=read();s.reactions[id]=s.reactions[id]||{};s.reactions[id][type]=s.reactions[id][type]!==true;write(s);render();requestAnimationFrame(()=>document.querySelector('[data-hot-post="'+CSS.escape(String(id))+'"]')?.scrollIntoView({block:'start'}));if(type==='why'&&s.reactions[id][type])toast(isKo()?'WHY NOT? 오늘 한다.':'WHY NOT? Go do it.')}
function tryRoutine(p){if(!p?.routine)return;try{localStorage.setItem(ROUTINE_INTENT_KEY,JSON.stringify({source:'garang-hot-v1',routine:p.routine,postId:p.id,createdAt:new Date().toISOString()}))}catch{}let ok=false;try{ok=window.GarangRouter?.navigate?.('workout',{source:'garang-hot-v1',force:true})===true}catch{}toast(ok?(isKo()?'Workout으로 연결했습니다.':'Opened Workout.'):(isKo()?'루틴 정보를 저장했습니다.':'Routine saved.'))}
async function sharePost(p){if(!p)return;const text=(p.caption||'GARANG HOT')+'\nWHY NOT?';if(navigator.share){try{await navigator.share({title:'GARANG HOT',text,url:p.url});return}catch{}}try{await navigator.clipboard.writeText(text+'\n'+p.url);toast(isKo()?'공유 내용이 복사됐습니다.':'Copied.')}catch{toast(isKo()?'공유를 지원하지 않는 브라우저입니다.':'Sharing unavailable.')}}
function bind(mount){mount.onclick=e=>{if(e.target.closest?.('[data-hot-open]')){openSheet(mount);return}if(e.target.closest?.('[data-hot-close]')){closeSheet(mount);return}const sheet=e.target.closest?.('[data-hot-sheet]');if(sheet&&e.target===sheet){closeSheet(mount);return}const a=e.target.closest?.('[data-hot-action]');if(!a)return;const s=read(),p=s.posts.find(x=>String(x.id)===String(a.dataset.id));if(!p)return;const name=a.dataset.hotAction;if(name==='fire'||name==='why')toggle(p.id,name);else if(name==='routine')tryRoutine(p);else if(name==='source')window.open(p.url,'_blank','noopener,noreferrer');else if(name==='share')sharePost(p)};const form=mount.querySelector('[data-hot-form]');if(form)form.onsubmit=e=>{e.preventDefault();if(saveImport(form)){form.reset();closeSheet(mount);render()}}}
function loadInstagram(){if(window.instgrm?.Embeds)return Promise.resolve(true);if(embedPromise)return embedPromise;embedPromise=new Promise(resolve=>{const existing=document.querySelector('script[data-garang-hot-instagram]');if(existing){existing.addEventListener('load',()=>resolve(true),{once:true});existing.addEventListener('error',()=>resolve(false),{once:true});return}const script=document.createElement('script');script.async=true;script.src='https://www.instagram.com/embed.js';script.dataset.garangHotInstagram='1';script.onload=()=>resolve(true);script.onerror=()=>resolve(false);document.body.appendChild(script)});return embedPromise}
async function hydrate(){const hosts=[...document.querySelectorAll('[data-garang-hot-instagram]')];if(!hosts.length)return;const ok=await loadInstagram();if(!ok)return;try{window.instgrm?.Embeds?.process?.()}catch{}setTimeout(()=>hosts.forEach(h=>h.dataset.ready='1'),700)}
function publishExternal(input){const url=normalizeInstagramUrl(input?.url),caption=String(input?.caption||'').trim().slice(0,180);if(!url||!caption)return false;const s=read();if(s.posts.some(p=>p.url===url))return false;s.posts.unshift({id:uid(),kind:'instagram',url,creator:String(input?.creator||'@instagram').slice(0,80),caption,category:ALLOWED.has(String(input?.category||'').toUpperCase())?String(input.category).toUpperCase():'ROUTINE',routine:String(input?.routine||'').slice(0,80),createdAt:new Date().toISOString()});write(s);render();return true}
function reconcile(){if(main()?.dataset?.garangScreen==='hot'||root())render()}
consumeShareTarget();window.addEventListener('garang:screen-rendered',reconcile);window.addEventListener('garang:route-completed',reconcile);window.addEventListener('pageshow',()=>{if(location.search.includes('garangShare=hot'))consumeShareTarget();reconcile()});window.GarangHotV1=Object.freeze({version:VERSION,normalizeInstagramUrl,publishExternal,reconcile});reconcile();
})();
