const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const ctx=vm.createContext({console,URL,AbortController,FormData,setTimeout,clearTimeout,location:{href:'https://example.test/app/',origin:'https://example.test'}});
for(const f of ['02_core/data-schema.js','services/performance.js','services/records.js','services/adapters.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),ctx);
const results=[];
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message});}}
(async()=>{
 await test('disconnected LLM rejects without a successful AI message',()=>assert.rejects(ctx.GarangAdapters.LLMService.send(ctx.GarangSchema.empty(),[]),/NOT_CONNECTED/));
 await test('disconnected payment never grants PRO',()=>assert.rejects(ctx.GarangAdapters.PaymentService.checkout(),/NOT_CONNECTED/));
 await test('OCR rejects non-images',()=>assert.rejects(ctx.GarangAdapters.InBodyOCRService.analyze({type:'text/plain',size:1}),/INVALID_IMAGE/));
 await test('external API endpoint is rejected before transmission',async()=>{ctx.GARANG_SERVICES_CONFIG={llmEndpoint:'https://untrusted.test'};await assert.rejects(ctx.GarangAdapters.LLMService.send(ctx.GarangSchema.empty(),[]),/UNTRUSTED_ENDPOINT/);});
 await test('invalid LLM response is not rendered as success (unit stub only)',async()=>{ctx.GARANG_SERVICES_CONFIG={llmEndpoint:'/api/coach'};ctx.fetch=async()=>({ok:true,json:async()=>({})});await assert.rejects(ctx.GarangAdapters.LLMService.send(ctx.GarangSchema.empty(),[]),/INVALID_RESPONSE/);});
 await test('HTTP failure propagates (unit stub only)',async()=>{ctx.fetch=async()=>({ok:false,status:503});await assert.rejects(ctx.GarangAdapters.LLMService.send(ctx.GarangSchema.empty(),[]),/HTTP_503/);});
 await test('Memory CRUD is independent from chat history',()=>{const s=ctx.GarangSchema.empty(),r=ctx.GarangRecords.create(()=>s);const m=r.MemoryService.save({text:'Keep original',category:'goals'});r.MemoryService.save({text:'Edited',category:'preferences'},m.id);assert.equal(r.MemoryService.list()[0].text,'Edited');assert.equal(s.aiChats.length,0);r.MemoryService.remove(m.id);assert.equal(r.MemoryService.list().length,0);});
 await test('Planner edit keeps completion and validates impossible dates',()=>{const s=ctx.GarangSchema.empty(),p=ctx.GarangRecords.create(()=>s).PlannerService;const x=p.save({title:'Test',date:'2026-08-31',time:'08:00'});p.toggle(x.id);p.save({title:'Edited',date:'2026-09-01',time:'09:30'},x.id);assert.equal(s.planner[0].done,true);assert.throws(()=>p.save({title:'bad',date:'2026-02-30',time:'25:00'}));p.remove(x.id);assert.equal(s.planner.length,0);});
 await test('Memory v2 keeps revisions and tombstones deleted records',()=>{const s=ctx.GarangSchema.empty(),m=ctx.GarangRecords.create(()=>s).MemoryService,x=m.save({text:'First',category:'goals',key:'primary-goal'});m.save({text:'Second',category:'goals',key:'primary-goal'},x.id);assert.equal(x.revisionHistory.length,1);m.remove(x.id);assert.ok(s.memory.deletedIds.includes(x.id));const cloud=ctx.GarangSchema.migrate({memory:{entries:[x]}});assert.equal(ctx.GarangSchema.mergeStates(s,cloud).memory.entries.length,0);});
 await test('Planner v2 records AI origin and an editable revision trail',()=>{const s=ctx.GarangSchema.empty(),p=ctx.GarangRecords.create(()=>s).PlannerService,x=p.save({title:'AI plan',date:'2026-09-01',time:'09:00',origin:'ai',confirmed:true});p.save({title:'Edited by user',date:'2026-09-01',time:'10:00',origin:'user'},x.id);assert.equal(x.revisionHistory.length,1);assert.equal(x.revisionHistory[0].title,'AI plan');assert.equal(x.origin,'user');});
 console.log(JSON.stringify(results,null,2));if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
})();
