'use strict';
const assert=require('node:assert/strict');
const Agent=require('../06_features/final/agent-contract-v2.js');
let passed=0,seq=0;const idFactory=prefix=>`${prefix}_${++seq}`;const clock=()=>new Date('2026-09-08T12:00:00.000Z');
const test=async(name,fn)=>{await fn();passed++;console.log(`PASS ${name}`);};
const code=expected=>error=>error?.code===expected;
(async()=>{
 await test('v2 keeps the v1 wire contract while advertising full CRUD domains',()=>{const req=Agent.createRequest({message:'x',context:{},language:'en'},{idFactory,clock});assert.equal(req.contractVersion,'garang-agent-action-v1');assert.equal(req.capabilities.actionLayerVersion,'garang-agent-action-v2.1');assert.deepEqual(req.capabilities.crudDomains,['workouts','meals','runs','body','planner','memory']);assert.ok(req.capabilities.writeTools.includes('createRecord'));assert.ok(req.capabilities.writeTools.includes('updateRecord'));assert.equal(req.policy.idempotentConfirmedWrites,true);assert.equal(req.policy.revisionConflictProtection,true);assert.deepEqual(req.policy.recommendationLifecycle,['accept','modify','dismiss']);assert.equal(req.policy.outcomeLinkage,true);});
 await test('generic create/update actions are validated as confirmed proposals',()=>{const create=Agent.normalizeToolCall({id:'c1',tool:'createRecord',args:{domain:'workouts',record:{name:'Squat'}}},{idFactory});assert.equal(create.kind,'write');assert.equal(create.requiresConfirmation,true);const update=Agent.normalizeToolCall({id:'u1',tool:'updateRecord',args:{domain:'planner',id:'p1',patch:{title:'New'},expectedRevision:2}},{idFactory});assert.equal(update.status,'proposal');assert.equal(update.args.expectedRevision,2);});
 await test('invalid generic CRUD payloads fail at the tool boundary',()=>{assert.throws(()=>Agent.normalizeToolCall({tool:'createRecord',args:{domain:'settings',record:{}}},{idFactory}),code('INVALID_TOOL_ARGS'));assert.throws(()=>Agent.normalizeToolCall({tool:'updateRecord',args:{domain:'planner',id:'p1',patch:{id:'p2'}}},{idFactory}),code('INVALID_TOOL_ARGS'));});
 await test('proposal id is the stable recommendation id and can be modified before acceptance',async()=>{let call=null;const adapter={respond:async()=>({answer:'proposal',meta:{provider:'mock'},toolCalls:[{id:'recommendation-1',tool:'createPlan',args:{title:'Recovery',duration:30,type:'recovery',reasonCodes:['LOW_SLEEP']},reason:'Sleep is short'}]})};const session=Agent.createSession({getState:()=>({planner:[]}),applyWrite:(tool,args,meta)=>{call={tool,args,meta};return {id:'p1',...args};},idFactory,clock});const result=await session.run({message:'plan',context:{decision:{confidence:.82,reasonCodes:['LOW_SLEEP']}},language:'en'},{adapter});const proposal=result.proposals[0];assert.equal(proposal.recommendationId,'recommendation-1');assert.equal(proposal.revision,1);assert.deepEqual(proposal.evidence,['LOW_SLEEP']);assert.equal(proposal.confidence,.82);const modified=session.modify(proposal.id,{duration:20,title:'Short recovery'});assert.equal(modified.id,'recommendation-1');assert.equal(modified.recommendationId,'recommendation-1');assert.equal(modified.revision,2);assert.equal(modified.args.duration,20);assert.equal(modified.args.title,'Short recovery');assert.equal(call,null,'modification must not write before acceptance');const accepted=session.confirm(proposal.id,true);assert.equal(accepted.proposal.status,'confirmed');assert.equal(call.args.recommendationId,'recommendation-1');assert.equal(call.args.recommendationRevision,2);assert.deepEqual(call.args.recommendationEvidence,['LOW_SLEEP']);assert.equal(call.args.recommendationConfidence,.82);assert.match(call.args.expectedOutcome,/execution evidence/i);assert.equal(call.meta.recommendationId,'recommendation-1');assert.equal(call.meta.recommendationRevision,2);});
 await test('confirmation passes proposal id as durable idempotency metadata',async()=>{let call=null;const adapter={respond:async request=>({answer:'proposal',requestId:request.requestId,toolCalls:[{id:'proposal-create-1',tool:'createRecord',args:{domain:'meals',record:{name:'Lunch'}}}]})};const session=Agent.createSession({getState:()=>({}),applyWrite:(tool,args,meta)=>{call={tool,args,meta};return {id:'m1'};},idFactory,clock});const result=await session.run({message:'save lunch',context:{},language:'en'},{adapter});assert.equal(call,null);const resolved=session.confirm(result.proposals[0].id,true);assert.equal(resolved.result.id,'m1');assert.equal(call.tool,'createRecord');assert.equal(call.meta.callId,'proposal-create-1');assert.equal(call.meta.idempotencyKey,'proposal-create-1');assert.equal(call.meta.userConfirmed,true);});
 await test('planner CRUD proposal persists recommendation metadata inside the record',async()=>{let saved=null;const adapter={respond:async()=>({answer:'proposal',toolCalls:[{id:'planner-rec-1',tool:'createRecord',args:{domain:'planner',record:{title:'Easy run',type:'running'}}}]})};const session=Agent.createSession({getState:()=>({}),applyWrite:(tool,args)=>{saved={tool,args};return args.record;},idFactory,clock});const result=await session.run({message:'plan run',context:{},language:'en'},{adapter});session.confirm(result.proposals[0].id,true);assert.equal(saved.args.record.recommendationId,'planner-rec-1');assert.equal(saved.args.record.recommendationRevision,1);assert.match(saved.args.record.expectedOutcome,/execution evidence/i);});
 await test('legacy two-argument Coach write adapters retain scoped confirmation',async()=>{let scoped=null;const adapter={respond:async()=>({answer:'proposal',toolCalls:[{id:'legacy-plan-1',tool:'createPlan',args:{title:'Recovery',duration:30}}]})};const legacyBridge={applyWrite(tool,args){scoped=globalThis[Agent.CONFIRMATION_SCOPE_KEY];return {tool,args,id:'p1'};}};const session=Agent.createSession({getState:()=>({planner:[]}),applyWrite:(tool,args)=>legacyBridge.applyWrite(tool,args),idFactory,clock});const result=await session.run({message:'plan',context:{},language:'en'},{adapter});const resolved=session.confirm(result.proposals[0].id,true);assert.equal(resolved.result.id,'p1');assert.equal(scoped?.userConfirmed,true);assert.equal(scoped?.callId,'legacy-plan-1');assert.equal(scoped?.idempotencyKey,'legacy-plan-1');assert.equal(scoped?.recommendationId,'legacy-plan-1');assert.equal(globalThis[Agent.CONFIRMATION_SCOPE_KEY],undefined);});
 await test('confirmation scope is always cleared when a write fails',async()=>{const adapter={respond:async()=>({answer:'proposal',toolCalls:[{id:'fail-plan-1',tool:'createPlan',args:{title:'Fail',duration:30}}]})};const session=Agent.createSession({getState:()=>({planner:[]}),applyWrite:()=>{throw new Error('persist failed');},idFactory,clock});const result=await session.run({message:'plan',context:{},language:'en'},{adapter});assert.throws(()=>session.confirm(result.proposals[0].id,true),/persist failed/);assert.equal(globalThis[Agent.CONFIRMATION_SCOPE_KEY],undefined);});
 await test('dismissal still performs zero writes',async()=>{let writes=0;const adapter={respond:async()=>({answer:'proposal',toolCalls:[{id:'reject-1',tool:'updateRecord',args:{domain:'workouts',id:'w1',patch:{weight:90}}}]})};const session=Agent.createSession({getState:()=>({}),applyWrite:()=>{writes++;},idFactory,clock});const result=await session.run({message:'change',context:{},language:'en'},{adapter});const dismissed=session.confirm(result.proposals[0].id,false);assert.equal(dismissed.proposal.status,'rejected');assert.equal(dismissed.proposal.recommendationId,'reject-1');assert.equal(writes,0);});
 console.log(`${passed} agent contract v2 tests passed`);
})().catch(error=>{console.error(error);process.exitCode=1;});
