const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');
function harness(){
 const data=new Map(),nodes=new Map();let quota=false;
 const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',hidden:false,style:{},classList:{add(){},remove(){}},replaceChildren(){},setAttribute(){}});return nodes.get(id);};
 const c=vm.createContext({console,Date,Math,URL,AbortController,JSON,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},navigator:{},location:{hash:''},localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>{if(quota)throw Error('quota');data.set(k,v);},removeItem:k=>data.delete(k)},document:{getElementById:node,querySelectorAll:()=>[],body:{classList:{remove(){}}}},});c.window=c;
 for(const f of ['02_core/data-schema.js','services/storage.js','services/performance.js','services/records.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c);
 let source=fs.readFileSync(path.join(root,'01_app/app.js'),'utf8');source=source.slice(0,source.indexOf('const finalFeatures=GarangFinal('))+`const finalFeatures={resetSession(){}};render=()=>{};window.audit={loadState,saveState,saveWorkoutSession,saveMealGroup,cloudLoad,cloudSave,resetSessionRuntime,safeNumber,getState:()=>state,setState:x=>{state=GarangSchema.migrate(x);committedState=JSON.stringify(state);},setUser:u=>{currentUser={uid:u};firebaseReady=true;authEpoch++;store=null;KEY='garang_account_'+u;loadState();},setDrafts:(w,m)=>{workoutDraft=w;mealDraft=m;},drafts:()=>({workoutDraft,mealDraft})};})();`;
 source=source.replace('window.audit={loadState,','window.audit={editWorkout,editMeal,fillFood,loadState,');c.scrollTo=()=>{};
 vm.runInContext(source,c);c.audit.loadState();return {c,data,node,quota:x=>quota=x};
}
const results=[];
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack});}}
(async()=>{
 await test('editing workout leaves original draft intact until replacement',()=>{const {c}=harness();c.audit.setDrafts([{id:'w',name:'Bench',sets:3,reps:10,weight:20,rpe:7,duration:10,body:70}],[]);c.audit.editWorkout(0);assert.equal(c.audit.drafts().workoutDraft.length,1);});
 await test('editing meal leaves original draft intact until replacement',()=>{const {c}=harness();c.audit.setDrafts([],[{id:'m',name:'Rice',grams:100,kcal:100,protein:2,carbs:20,fat:1}]);c.audit.editMeal(0);assert.equal(c.audit.drafts().mealDraft.length,1);});
 await test('unknown food clears stale database nutrition fields',()=>{const {c,node}=harness();node('foodSearch').value='Unknown';node('foodKcal').value=999;c.audit.fillFood(false);assert.equal(node('foodKcal').value,'');});
 await test('failed workout save preserves draft and rolls back unsaved records',()=>{const h=harness();h.c.audit.setDrafts([{id:'w',name:'Bench',kcal:50}],[]);h.quota(true);h.c.audit.saveWorkoutSession();assert.equal(h.c.audit.getState().workouts.length,0);assert.equal(h.c.audit.drafts().workoutDraft.length,1);h.quota(false);h.c.audit.saveWorkoutSession();assert.equal(h.c.audit.getState().workouts.length,1);assert.equal(h.c.audit.drafts().workoutDraft.length,0);});
 await test('failed meal save preserves draft; retry saves once',()=>{const h=harness();h.c.audit.setDrafts([],[{name:'Rice',kcal:100,protein:2,carbs:22,fat:0}]);h.quota(true);h.c.audit.saveMealGroup();assert.equal(h.c.audit.getState().meals.length,0);assert.equal(h.c.audit.drafts().mealDraft.length,1);h.quota(false);h.c.audit.saveMealGroup();assert.equal(h.c.audit.getState().meals.length,1);});
 await test('late account A cloud read cannot enter account B',async()=>{const h=harness();let complete;h.c.firebase={firestore:()=>({collection:()=>({doc:()=>({get:()=>new Promise(r=>complete=r)})})})};h.c.audit.setUser('A');const pending=h.c.audit.cloudLoad();h.c.audit.setUser('B');complete({exists:true,data:()=>({profile:{name:'PRIVATE A'},updatedAtMs:999})});await pending;assert.equal(h.c.audit.getState().profile,null);assert.equal(h.data.has('garang_account_B'),false);});
 await test('cloud read cannot replace local changes made while request is pending',async()=>{const h=harness();let complete;h.c.firebase={firestore:()=>({collection:()=>({doc:()=>({get:()=>new Promise(r=>complete=r),set:async()=>{}})})})};h.c.audit.setUser('A');const pending=h.c.audit.cloudLoad();h.c.audit.getState().profile={name:'New edit'};h.c.audit.saveState();complete({exists:true,data:()=>({profile:{name:'Old server'},updatedAtMs:Date.now()+100000})});await pending;assert.equal(h.c.audit.getState().profile.name,'New edit');});
 await test('old cloud document cannot replace meal-only local account',async()=>{const h=harness();h.c.firebase={firestore:()=>({collection:()=>({doc:()=>({get:async()=>({exists:true,data:()=>({profile:{name:'Old'},updatedAtMs:1})})})})})};h.c.audit.setUser('A');h.c.audit.setState({meals:[{name:'Meal',date:'2026-09-01'}],updatedAtMs:100});await h.c.audit.cloudLoad();assert.equal(h.c.audit.getState().meals.length,1);});
 await test('queued writes preserve order',async()=>{const h=harness();const seen=[];let release;h.c.firebase={firestore:()=>({collection:()=>({doc:()=>({set:p=>{seen.push(p.profile.name);return seen.length===1?new Promise(r=>release=r):Promise.resolve();}})})})};h.c.audit.setUser('A');h.c.audit.setState({profile:{name:'one'}});const first=h.c.audit.cloudSave();await Promise.resolve();await Promise.resolve();h.c.audit.getState().profile.name='two';const second=h.c.audit.cloudSave();assert.equal(seen.length,1);release();await first;await second;assert.deepEqual(seen,['one','two']);});
 await test('unknown weight uses fallback rather than zero',()=>{assert.equal(harness().c.audit.safeNumber(null,67),67);});
 await test('score history is sorted during import',()=>{const {c}=harness();const s=c.GarangSchema.migrate({scoreHistory:[{date:'2026-09-01',total:1},{date:'2026-08-01',total:2}]});assert.equal(s.scoreHistory[0].date,'2026-08-01');});
 await test('imported memory category and plan type cannot inject markup',()=>{const {c}=harness();vm.runInContext(fs.readFileSync(path.join(root,'06_features/final/features.js'),'utf8'),c);const s=c.GarangSchema.migrate({memory:{entries:[{text:'x',category:'<img src=x onerror=alert(1)>'}]},planner:[{title:'x',type:'<script>x</script>',date:c.GarangSchema.date()}]});const esc=x=>String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const f=c.GarangFinal({getState:()=>s,esc,today:c.GarangSchema.date});assert.ok(!f.memory().includes('<img src=x'));assert.ok(!f.planner().includes('<script>x'));});
 await test('session reset discards stale AI response',async()=>{const {c,node}=harness();vm.runInContext(fs.readFileSync(path.join(root,'06_features/final/features.js'),'utf8'),c);let s=c.GarangSchema.empty(),complete;node('aiQuestion').value='Private question';node('aiConsent').checked=true;c.GARANG_SERVICES_CONFIG={llmEndpoint:'/api'};c.GarangAdapters={LLMService:{send:()=>new Promise(r=>complete=r)}};const f=c.GarangFinal({$:node,getState:()=>s,esc:String,today:c.GarangSchema.date,uid:c.GarangSchema.id,save:()=>true,render(){},toast(){},getPage:()=> 'home'});const pending=f.ask();f.resetSession();s=c.GarangSchema.empty();complete({text:'Private answer',plans:[]});await pending;assert.equal(s.aiChats.length,0);});
 console.log(JSON.stringify({status:results.some(x=>x.status==='FAIL')?'FAIL':'PASS',tests:results},null,2));if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
})();
