'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const route=read('06_features/ui/runtime/garang-auth-route-reconcile-v1.js');
const router=read('06_features/ui/runtime/garang-router-v1.js');
const mobile=read('06_features/ui/runtime/garang-mobile-auth-v1.js');
assert.ok(route.includes("screen&&screen!=='modeling'"),'cloud restore must not hijack an already active non-onboarding screen');
assert.ok(route.includes('document.activeElement'));assert.ok(route.includes('INPUT|TEXTAREA|SELECT'),'focused onboarding input must block automatic route change');
assert.ok(route.includes("router.navigate('today',{source:'auth-reconcile'})"),'auth hydration must delegate to canonical router');
assert.equal(route.includes('.click('),false,'auth reconciliation must not synthesize a navigation click');
assert.ok(router.includes('window.GarangRouter=Object.freeze'),'canonical router export missing');
assert.ok(router.includes('removeTransient'),'route transition must centrally settle transient layers');
assert.ok(mobile.includes('signInWithPopup'),'mobile/PWA social auth must avoid cross-origin redirect flow on modern Safari');
assert.equal(mobile.includes('signInWithRedirect'),false,'mobile auth must not reintroduce redirect loop risk');
assert.ok(mobile.includes('GoogleAuthProvider'));assert.ok(mobile.includes("OAuthProvider('apple.com')"));assert.ok(mobile.includes('(display-mode: standalone)'));
assert.equal(mobile.includes('setInterval('),false);
console.log('auth-route-mobile: PASS');
