'use strict';
const {startStaticServer}=require('./helpers/static-server.cjs');
const {installAuthenticatedFirebaseMock}=require('./helpers/authenticated-browser-fixture.cjs');
const assert=require('node:assert/strict');
const path=require('node:path');
const {webkit}=require('playwright');
const root=path.resolve(__dirname,'..'),serveRoot=path.join(root,'dist'),port=8791,baseURL=`http://127.0.0.1:${port}`;
const pad=n=>String(n).padStart(2,'0'),today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;};
const instagramUA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 398.0.0.0.0';
async function waitForServer(){const deadline=Date.now()+15000;while(Date.now()<deadline){try{const r=await fetch(baseURL);if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,180));}throw new Error('GARANG Today visual preview server did not start');}
function seedState(){const date=today(),now=new Date().toISOString();return {meta:{schemaVersion:5,updatedAt:now},profile:{name:'Visual Parity',age:27,height:174,weight:70,gender:'male',goal:'근육 증가'},onboarding:{complete:true,skipped:false,goal:'근육 증가',weeklyFrequency:4,availableMinutes:60},preferences:{language:'ko',unit:'metric'},planner:[],workouts:[{id:'vp-workout',date,name:'하체 운동',sets:4,reps:8,weight:80,rpe:7,duration:45,createdAt:now,updatedAt:now}],meals:[{id:'vp-meal',date,name:'계란후라이 + 크림파스타',kcal:1073,protein:48,carbs:112,fat:44,items:[{name:'계란후라이',kcal:273},{name:'크림파스타',kcal:800}],createdAt:now,updatedAt:now}],runs:[],body:[],checkins:[],dailyCheckins:[],aiChat:[],actionLog:[],errors:[],analytics:{events:[{name:'coach_recommendation_shown',date,props:{screen:'coach',date}}]},memory:{entries:[],facts:[],preferences:[],goals:[],events:[]},plan:'FREE'};}
async function boot(browser,width,height,options={}){const contextOptions={viewport:{width,height},isMobile:true,hasTouch:true,reducedMotion:options.reducedMotion||'no-preference'};if(options.userAgent)contextOptions.userAgent=options.userAgent;const context=await browser.newContext(contextOptions);await installAuthenticatedFirebaseMock(context);
await context.addInitScript(payload=>{localStorage.setItem('garang_user_mock-user_v3',JSON.stringify(payload));},seedState());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e?.stack||e?.message||e)));await page.goto(baseURL,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.getElementById('appView')&&!document.getElementById('appView').hidden,{timeout:15000});await page.waitForFunction(()=>window.GarangProductConsolidationV1?.version==='garang-product-consolidation-v1.1.0'&&document.getElementById('main')?.dataset?.gpcToday==='1',{timeout:10000});await page.waitForFunction(()=>document.querySelector('#garangTodayBrandHero')&&document.querySelector('#garangTodayDensity')&&document.querySelector('#garangTodayFlow .gtf-decision'),{timeout:10000});await page.waitForTimeout(500);return {context,page,errors};}
async function verify(browser,width,height,options={}){const {context,page,errors}=await boot(browser,width,height,options);const flow=page.locator('#garangTodayFlow');assert.equal(await page.locator('#main').getAttribute('data-garang-screen'),'today');assert.equal(await page.locator('#garangTodayBrandHero').count(),1,'brand hero markup remains for rollback');assert.equal(await page.locator('#garangTodayBrandHero').isHidden(),true,'decorative hero must be internalized');assert.equal(await page.locator('#garangTodayDensity').count(),1,'density capability markup remains');assert.equal(await page.locator('#garangTodayDensity').isHidden(),true,'dashboard-like density must be internalized');assert.equal(await page.locator('#main [data-garang-motion-surface]:visible').count(),0,'decorative motion cannot compete with the core question');assert.equal(await page.locator('.gtd3-motion-canvas').count(),0,'falling droplet canvas must not mount');assert.equal(await page.locator('script[data-garang-accumulation-motion-v1]').count(),0,'decorative accumulation motion runtime must not be injected');assert.equal(await page.evaluate(()=>!!window.GarangAccumulationMotionV1),false,'decorative motion runtime must stay inactive');assert.equal(await flow.locator('.gtf-decision').isVisible(),true,'judgment summary is visible');assert.equal(await flow.locator('.gpc-coach-explain').isVisible(),true,'rationale has one Coach entry');assert.equal(await flow.locator('.gpc-today-plan').isVisible(),true,'Today plan is visible');assert.equal(await flow.locator('.gpc-today-plan .gtf-track').count(),3,'plan preserves three canonical domains');const order=await flow.evaluate(node=>[...node.children].filter(x=>['gtf-state','gtf-decision','gpc-coach-explain','gpc-today-plan','gtf-action'].some(c=>x.classList.contains(c))).map(x=>x.classList.contains('gtf-state')?'state':x.classList.contains('gtf-decision')?'decision':x.classList.contains('gpc-coach-explain')?'explain':x.classList.contains('gpc-today-plan')?'plan':'action'));assert.deepEqual(order.slice(0,4),['state','decision','explain','plan'],'Today hierarchy must begin state -> judgment -> rationale entry -> plan');const layout=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,main:document.getElementById('main')?.getBoundingClientRect().width||0}));assert.ok(layout.scroll<=layout.client+1&&layout.main<=width+1,`Today must respect ${width}px viewport: ${JSON.stringify(layout)}`);assert.deepEqual(errors,[],`Today consolidated visual errors @${width}:\n${errors.join('\n')}`);await context.close();}
(async()=>{const server=startStaticServer(serveRoot,port);let browser;try{await waitForServer();browser=await webkit.launch({headless:true});await verify(browser,390,844);await verify(browser,393,852);await verify(browser,430,932);await verify(browser,390,844,{userAgent:instagramUA});await verify(browser,390,844,{reducedMotion:'reduce'});console.log('browser-today-visual-parity restrained product consolidation + no decorative droplet motion: PASS');}finally{if(browser)await browser.close().catch(()=>{});server.kill('SIGTERM');}})().catch(error=>{console.error(error);process.exit(1);});
