'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const {webkit}=require('playwright');
const {startStaticServer}=require('./helpers/static-server.cjs');
const {installAuthenticatedFirebaseMock}=require('./helpers/authenticated-browser-fixture.cjs');
const root=path.resolve(__dirname,'..'),serveRoot=path.join(root,'dist'),port=8796,baseURL=`http://127.0.0.1:${port}`;
function isoDate(offset=0){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function demoState(){const yesterday=isoDate(-1),older=isoDate(-18);return {meta:{schemaVersion:5,updatedAt:new Date().toISOString()},profile:{name:'Reference',age:29,height:176,weight:73,gender:'male',goal:'퍼포먼스 향상'},onboarding:{complete:true,skipped:false,goal:'퍼포먼스 향상',experience:'intermediate',equipmentProfile:'full_gym',weeklyFrequency:4,availableMinutes:55},preferences:{language:'ko',unit:'metric'},settings:{},privacy:{consent:{analytics:false}},planner:[],workouts:[{id:'w-prev',date:yesterday,name:'바벨 벤치프레스',sets:4,reps:8,weight:72.5,rpe:8,duration:48,setDetails:[{weight:72.5,reps:8,rpe:8},{weight:72.5,reps:8,rpe:8},{weight:72.5,reps:7,rpe:8.5},{weight:70,reps:8,rpe:8.5}]}],meals:[{id:'m-prev',date:yesterday,name:'닭가슴살 식사',kcal:630,protein:51,carbs:62,fat:14,items:[{name:'닭가슴살',grams:180,kcal:300,protein:48,carbs:0,fat:6},{name:'현미밥',grams:210,kcal:330,protein:3,carbs:62,fat:8}]}],runs:[],body:[{id:'b0',date:older,weight:74,muscle:32.2,fatPercent:15.3},{id:'b1',date:yesterday,weight:73,muscle:32.8,fatPercent:14.7}],checkins:[],dailyCheckins:[],physiologicalSignals:[],aiChat:[{role:'assistant',text:'오늘은 최근 훈련과 회복 상태를 반영해 운동을 준비했습니다.',at:new Date().toISOString()}],memory:{entries:[],facts:[],preferences:[],goals:[],events:[]},foodIdentity:{barcodes:[],misses:[],corrections:[]},actionLog:[],analytics:{events:[]},errors:[],plan:'FREE'};}
async function waitServer(){const until=Date.now()+15000;while(Date.now()<until){try{const r=await fetch(baseURL);if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,160));}throw new Error('reference UI preview server did not start');}
async function route(page,screen){const ok=await page.evaluate(next=>window.GarangRouter?.navigate?.(next,{source:'reference-ui-v2-test',force:true}),screen);assert.equal(ok,true,`${screen} route must stay canonical`);await page.waitForFunction(expected=>document.getElementById('main')?.dataset?.garangScreen===expected,screen,{timeout:7000});await page.waitForFunction(()=>document.getElementById('main')?.dataset?.garangReferenceUi==='v2',null,{timeout:5000});await page.waitForTimeout(260);}
async function noHorizontalOverflow(page,label){const result=await page.evaluate(()=>({inner:window.innerWidth,doc:document.documentElement.scrollWidth,body:document.body.scrollWidth,main:document.getElementById('main')?.scrollWidth||0}));assert.ok(result.doc<=result.inner+2,`${label} document overflow: ${JSON.stringify(result)}`);assert.ok(result.body<=result.inner+2,`${label} body overflow: ${JSON.stringify(result)}`);}
async function box(page,selector){return page.locator(selector).first().boundingBox();}
async function ownsTouch(page,selector,label){const loc=page.locator(selector).first();await loc.waitFor({state:'visible',timeout:5000});await loc.evaluate(el=>el.scrollIntoView({block:'center',inline:'nearest',behavior:'auto'}));await page.waitForTimeout(60);const result=await loc.evaluate(el=>{const r=el.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2,target=document.elementFromPoint(x,y);return {owned:!!target&&(target===el||el.contains(target)),rect:{x:r.x,y:r.y,width:r.width,height:r.height},hit:{tag:target?.tagName||'',id:target?.id||'',className:String(target?.className||'')}};});assert.equal(result.owned,true,`${label} must own its physical touch center: ${JSON.stringify(result)}`);return result.rect;}
async function activateExerciseSurface(page){const tab=page.locator('[data-gws-step="exercise"]').first();await tab.waitFor({state:'visible',timeout:6000});await tab.click();await page.waitForTimeout(180);await page.locator('#workoutSetDetails .execution-set-row.current-set').first().waitFor({state:'visible',timeout:6000});}
(async()=>{const server=startStaticServer(serveRoot,port);let browser;try{
 await waitServer();browser=await webkit.launch({headless:true});
 for(const width of [320,360,390,430]){
  const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true});await installAuthenticatedFirebaseMock(context);await context.addInitScript(payload=>localStorage.setItem('garang_user_mock-user_v3',JSON.stringify(payload)),demoState());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e?.message||e)));
  await page.goto(baseURL,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.getElementById('appView')&&!document.getElementById('appView').hidden,null,{timeout:15000});await page.waitForFunction(()=>window.GarangReferenceUIV2?.version==='garang-reference-ui-v2.0.0',null,{timeout:8000});await page.waitForFunction(()=>document.getElementById('main')?.dataset?.garangReferenceUi==='v2',null,{timeout:8000});
  assert.equal(await page.locator('.g-ref-date-strip>span').count(),7,'Today reference date strip must contain seven days');assert.equal(await page.locator('.g-ref-date-strip .is-today').count(),1,'Today must mark exactly one current day');assert.equal(await page.locator('.g-ref-today-stage>#garangTodayFlow').count(),1,'Today decision owner must be structurally placed inside the reference stage');assert.equal(await page.locator('#garangTodayFlow .gtf-decision').isVisible(),true,'Today decision must stay visible');const start=page.locator('#garangTodayFlow [data-garang-direct-workout-start="1"]');await start.waitFor({state:'attached',timeout:8000});const startBox=await start.boundingBox();if(startBox)assert.ok(startBox.height>=44,'Today primary action must remain touch safe');await noHorizontalOverflow(page,`Today ${width}`);

  await route(page,'workout');assert.equal(await page.locator('#main.g-ref-screen-workout').count(),1,'Workout must use reference screen structure');assert.equal(await page.locator('.workout-session-bar').count(),1,'Workout must preserve one session/timer owner');assert.equal(await page.locator('#addWorkout').count(),1,'Workout canonical add owner must remain singular');await activateExerciseSurface(page);const sessionStart=page.locator('#startWorkoutSession');await sessionStart.waitFor({state:'visible',timeout:6000});const sessionStartRect=await ownsTouch(page,'#startWorkoutSession',`Workout session start ${width}`);assert.ok(sessionStartRect.height>=44,`Workout session start must remain touch safe at ${width}px`);await sessionStart.click();await page.waitForFunction(()=>document.querySelector('.workout-session-bar')?.classList.contains('is-live'),null,{timeout:4000});const timerBox=await box(page,'.workout-session-live strong');assert.ok(timerBox&&timerBox.height>=30,`Workout LIVE timer must remain a dominant visual at ${width}px`);

  const current=page.locator('#workoutSetDetails .execution-set-row.current-set').first();await current.waitFor({state:'visible',timeout:5000});const geometry=await current.evaluate(row=>{const rect=e=>{const r=e?.getBoundingClientRect?.();return r?{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right}:null;};return {row:rect(row),weight:rect(row.querySelector('[data-set-weight]')),reps:rect(row.querySelector('[data-set-reps]')),complete:rect(row.querySelector('[data-execution-set-complete]')),nav:rect(document.getElementById('bottomNav')),viewport:window.innerWidth};});assert.ok(geometry.row&&geometry.row.x>=-1&&geometry.row.right<=geometry.viewport+1,`Current set must stay inside ${width}px viewport: ${JSON.stringify(geometry)}`);assert.ok(geometry.weight&&geometry.reps,`Weight/Reps must remain visible: ${JSON.stringify(geometry)}`);assert.ok(Math.abs(geometry.weight.width-geometry.reps.width)<=2,`Weight/Reps must be equal useful columns at ${width}px: ${JSON.stringify(geometry)}`);assert.ok(geometry.weight.height>=56&&geometry.reps.height>=56,`Weight/Reps inputs must be >=56px at ${width}px: ${JSON.stringify(geometry)}`);assert.ok(geometry.complete&&geometry.complete.height>=50,`Complete Set must be >=50px at ${width}px: ${JSON.stringify(geometry)}`);assert.ok(geometry.complete.width>=geometry.row.width-24,`Complete Set must use the current-set width at ${width}px: ${JSON.stringify(geometry)}`);await ownsTouch(page,'#workoutSetDetails .execution-set-row.current-set [data-execution-set-complete]',`Complete Set ${width}`);await current.locator('[data-execution-set-complete]').click();

  const rest=page.locator('#workoutExecutionRest');await rest.waitFor({state:'visible',timeout:4000});const restGeometry=await rest.evaluate(el=>{const r=el.getBoundingClientRect(),nav=document.getElementById('bottomNav')?.getBoundingClientRect();return {rest:{top:r.top,bottom:r.bottom,width:r.width,height:r.height},nav:nav?{top:nav.top,bottom:nav.bottom}:null,clock:document.getElementById('workoutExecutionRestClock')?.getBoundingClientRect().height||0};});assert.ok(restGeometry.clock>=110,`Approved Rest timer must remain visually dominant at ${width}px: ${JSON.stringify(restGeometry)}`);if(restGeometry.nav)assert.ok(restGeometry.rest.bottom<=restGeometry.nav.top+1||restGeometry.rest.top>=restGeometry.nav.bottom-1,`Rest must not overlap bottom navigation at ${width}px: ${JSON.stringify(restGeometry)}`);await ownsTouch(page,'#skipWorkoutRest',`Skip Rest ${width}`);await page.locator('#skipWorkoutRest').click();await page.locator('#workoutSetDetails .execution-set-row.completed').first().waitFor({state:'visible',timeout:4000});await page.locator('#workoutSetDetails .execution-set-row.current-set').first().waitFor({state:'visible',timeout:4000});await noHorizontalOverflow(page,`Workout ${width}`);

  await route(page,'nutrition');assert.equal(await page.locator('.g-ref-nutrition-stage>.meal-scan-card').count(),1,'Meal Scan must be structurally promoted to the nutrition primary stage');assert.equal(await page.locator('#saveMeal').count(),1,'Nutrition canonical meal save owner must remain singular');const scanBox=await box(page,'.meal-scan-card .meal-scan-empty');if(scanBox)assert.ok(scanBox.height>=180,`Meal Scan camera surface must dominate at ${width}px`);await noHorizontalOverflow(page,`Nutrition ${width}`);
  await route(page,'body');assert.equal(await page.locator('.g-ref-body-stage>.body-hero').count(),1,'Body anatomy hero must occupy the primary reference stage');assert.equal(await page.locator('#saveBody').count(),1,'Body canonical save owner must remain singular');const bodyBox=await box(page,'.g-ref-body-primary');assert.ok(bodyBox&&bodyBox.height>=320,`Body anatomy hero must remain dominant at ${width}px: ${bodyBox?.height}`);await noHorizontalOverflow(page,`Body ${width}`);
  await route(page,'coach');assert.equal(await page.locator('.coach-app-shell.g-ref-coach-shell').count(),1,'Coach must use chat-first reference shell');assert.equal(await page.locator('.g-ref-coach-thread').count(),1,'Coach thread must remain attached');assert.equal(await page.locator('.g-ref-coach-composer').count(),1,'Coach composer must remain attached');const composer=await box(page,'.g-ref-coach-composer .gpt-composer');assert.ok(composer&&composer.height>=44,'Coach composer must remain a real touch target');await noHorizontalOverflow(page,`Coach ${width}`);
  assert.equal(errors.length,0,`Reference UI must not introduce page errors at ${width}px: ${errors.join('\n')}`);await context.close();
 }
 console.log('browser-reference-ui-v2 Founder-approved structural + Workout execution contract 320/360/390/430: PASS');
}catch(error){console.error(error);process.exitCode=1;}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})();
