'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const {startStaticServer}=require('./helpers/static-server.cjs');
const {webkit}=require('playwright');
const root=path.resolve(__dirname,'..'),serveRoot=path.join(root,'dist'),port=8792,baseURL=`http://127.0.0.1:${port}`;
function date(offset){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10);}
function state(){return {meta:{schemaVersion:5,updatedAt:new Date().toISOString()},profile:{name:'Quiet',age:30,height:174,weight:70,gender:'male',goal:'퍼포먼스 향상'},onboarding:{complete:true,skipped:false,goal:'퍼포먼스 향상',weeklyFrequency:4,availableMinutes:60},preferences:{language:'ko',unit:'metric'},planner:[{id:'p1',date:date(0),title:'오늘 운동',completed:false,status:'confirmed'}],workouts:[{id:'w1',date:date(-1),name:'스쿼트',sets:3,reps:8,weight:60,rpe:8}],meals:[{id:'m1',date:date(-1),name:'식사',kcal:600,protein:40}],runs:[],body:[{id:'b1',date:date(-1),weight:70}],checkins:[{id:'c1',date:date(-1),sleep:7,energy:4,stress:2,soreness:1}],dailyCheckins:[],aiChat:[],actionLog:[],errors:[],analytics:{events:[]},memory:{entries:[],facts:[],preferences:[],goals:[],events:[]},plan:'FREE'};}
async function ready(page){await page.waitForFunction(()=>document.getElementById('appView')&&!document.getElementById('appView').hidden,{timeout:15000});await page.locator('#garangQuietToday').waitFor({state:'visible',timeout:7000});}
(async()=>{const server=startStaticServer(serveRoot,port);let browser;try{browser=await webkit.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await context.addInitScript(payload=>{localStorage.setItem('garang_demo','1');localStorage.setItem('garang_demo_state_v3',JSON.stringify(payload));},state());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e?.stack||e?.message||e)));await page.goto(baseURL,{waitUntil:'domcontentloaded'});await ready(page);
 assert.equal(await page.locator('#garangQuietToday').count(),1,'Today must have one composed quiet surface');
 for(const selector of ['#garangTodayFlow','#garangCoreToday','[data-golden-path-surface]','.visual-today-hero','.today-snapshot','.status-visual-card','.today-plan-card']) assert.equal(await page.locator(selector).count(),1,`${selector} must not be duplicated`);
 assert.equal(await page.locator('.gq-details').count(),2,'Today details must be grouped into two progressive disclosures');
 assert.equal(await page.locator('.gq-details').evaluateAll(nodes=>nodes.every(node=>!node.open)),true,'secondary details must start quiet and closed');
 assert.equal(await page.locator('#garangTodayFlow').isVisible(),true,'next action remains visible');assert.equal(await page.locator('#garangCoreToday').isVisible(),true,'current state remains visible');assert.equal(await page.locator('.visual-today-hero [data-today-view="front"]').isVisible(),true,'anatomy controls remain usable');
 await page.locator('[data-gq-details="signals"] summary').click();assert.equal(await page.locator('.gq-details[data-gq-details="signals"] .today-snapshot').isVisible(),true,'signals disclosure must reveal existing snapshot');assert.equal(await page.locator('.gq-details[data-gq-details="signals"] [data-action="open-checkin"]').count(),1,'check-in action must remain reachable');
 await page.locator('[data-gq-details="plan"] summary').click();assert.equal(await page.locator('.gq-details[data-gq-details="plan"] .today-plan-card').isVisible(),true,'plan disclosure must reveal existing plan');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'quiet Today must not introduce horizontal overflow');assert.deepEqual(errors,[],'quiet Today must not create page errors');
 await page.locator('#bottomNav [data-page="coach"]').click();await page.waitForFunction(()=>document.getElementById('main')?.dataset?.garangScreen==='coach',{timeout:5000});await page.locator('#bottomNav [data-page="today"]').click();await ready(page);assert.equal(await page.locator('#garangQuietToday').count(),1,'Today must remount as one surface after route round trip');assert.deepEqual(errors,[],'route round trip must remain error-free');console.log('browser quiet Today surface: ok');}finally{if(browser)await browser.close();server.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
