'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const src=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-brand-runtime-v2.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.ok(src.includes('function currentAuthUid()'),'Coach must resolve the live authenticated uid');
assert.ok(src.includes('`garang_user_${authUid}_v3`'),'authenticated Coach must pin storage to the signed-in account');
assert.ok(src.includes('function coachAppState()'),'Coach must have a canonical live-state accessor');
assert.ok(src.includes('bridge?.ready?.()')&&src.includes('bridge.getState?.()'),'Coach must prefer the live Agent state bridge');
const plan=src.indexOf('/plan|schedule|계획|플래너/');
const recovery=src.indexOf('/회복|상태|수면|오늘/');
assert.ok(plan>=0&&recovery>=0&&plan<recovery,'plan intent must be classified before generic 오늘/recovery intent');
for(const forbidden of ['window.prompt(','window.confirm(','stopImmediatePropagation','addEventListener(\'pointerdown\',close,true)','addEventListener("pointerdown",close,true)'])assert.equal(src.includes(forbidden),false,`Coach must avoid blocking/global-capture interaction: ${forbidden}`);
assert.ok(src.includes('if(!runtime.root.isConnected)return'),'late Coach answers must not write into a detached route');
assert.ok(src.includes('function focusComposer(runtime)')&&src.includes('if(!isTouchLike()'),'touch devices must not force composer focus/visual viewport jumps');
assert.ok(html.includes('garang-brand-runtime-v2.js?v=2.1.0-auth-pinned-coach'),'shell must publish the authenticated Coach runtime with a fresh cache key');
console.log('coach-auth-stability: PASS');
