'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const src=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-brand-runtime-v2.js'),'utf8');
const agent=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-coach-agent-v4.js'),'utf8');
const coreLoop=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-core-loop-v1.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.ok(src.includes('function currentAuthUid()'),'Coach must resolve the live authenticated uid');
assert.ok(src.includes('`garang_user_${authUid}_v3`'),'authenticated Coach must pin storage to the signed-in account');
assert.ok(src.includes('function coachAppState()'),'Coach must have a canonical live-state accessor');
assert.ok(src.includes('bridge?.ready?.()')&&src.includes('bridge.getState?.()'),'Coach must prefer the live Agent state bridge');
const plan=src.indexOf('/plan|schedule|계획|플래너/');
const recovery=src.indexOf('/회복|상태|수면|오늘/');
assert.ok(plan>=0&&recovery>=0&&plan<recovery,'plan intent must be classified before generic 오늘/recovery intent');
for(const forbidden of ['window.prompt(','window.confirm(','stopImmediatePropagation','addEventListener(\'pointerdown\',close,true)','addEventListener("pointerdown",close,true)'])assert.equal(src.includes(forbidden),false,`Coach must avoid blocking/global-capture interaction: ${forbidden}`);
assert.ok(src.includes('if(!runtime.root.isConnected)return'),'late Coach answers must not write into a detached route');
assert.ok(src.includes('function focusComposer(runtime)')&&src.includes('if(!isTouchLike()'),'touch devices must not force composer focus/visual viewport jumps');
const readyGuard=agent.indexOf("if(!Contract||!Bridge?.ready?.())");
const seenAfterReady=agent.indexOf('seenAssistantIds.add(messageId)',readyGuard);
assert.ok(readyGuard>=0&&seenAfterReady>readyGuard,'an assistant must not be marked processed before authenticated Agent state is ready');
assert.ok(agent.includes('processingAssistantIds'),'Agent proposal generation must deduplicate concurrent lifecycle retries');
assert.ok(agent.includes("window.addEventListener('garang:cloud-state-ready'"),'cloud hydration must explicitly retry a pending Coach proposal');
assert.ok(agent.includes("messageEl.dataset.g4AgentPending='1'"),'unhydrated Agent work must remain retryable');
assert.ok(agent.includes("garang:coach-prompt-strip-ready"),'Coach Agent must publish the prompt-strip lifecycle handshake');
assert.ok(coreLoop.includes("garang:coach-prompt-strip-ready"),'Core Loop must reconcile contextual actions when the canonical prompt strip becomes ready');
assert.ok(html.includes('garang-brand-runtime-v2.js?v=2.3.0-server-action-owner'),'shell must publish the authenticated Coach runtime with a fresh cache key');
assert.ok(html.includes('agent-state-hook-v1.js?v=1.5.0-auth-write-pinned'),'authenticated Agent state pinning must be cache-busted');
assert.ok(html.includes('garang-coach-agent-v4.js?v=4.9.2-prompt-strip-handshake'),'canonical hydration-safe Coach Agent must publish the prompt-strip handshake build');
assert.ok(html.includes('garang-core-loop-v1.js?v=1.1.3-coach-handshake'),'Core Loop must ship the Coach action reconciliation handshake build');
console.log('coach-auth-stability: PASS');
