'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const runtime=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-coach-decision-v1.js'),'utf8');
const coreLoop=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-core-loop-v1.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');

assert.ok(runtime.includes("VERSION='garang-coach-decision-v1.5-canonical-next'"),'canonical-next Coach runtime v1.5 must be active');
assert.ok(runtime.includes('garang-decision-primary')&&runtime.includes('garang-decision-preview'),'Coach must expose judgment and reason before chat detail');
assert.ok(runtime.includes('garang-decision-toggle'),'decision evidence must use one disclosure toggle');
assert.ok(runtime.includes('aria-expanded'),'decision detail disclosure must be accessible');
assert.ok(runtime.includes('garang-decision-details')&&runtime.includes('[hidden]{display:none!important}'),'supporting evidence must stay progressively disclosed by default');
assert.ok(runtime.includes('garang-decision-action-wrap')&&runtime.includes('Propose this plan')&&runtime.includes('계획 제안'),'proposal-gated plan action must be visible without expanding evidence');
assert.ok(runtime.includes('min-height:52px!important'),'mobile decision-first surface must stay compact without losing its touch target');
assert.ok(runtime.includes('min-height:0!important')&&runtime.includes('height:auto!important'),'decision container must resist inherited oversized card heights');
assert.ok(runtime.includes('garang-has-decision-card')&&runtime.includes('grid-template-rows:auto auto minmax(0,1fr) auto!important'),'decision card must own its own grid row instead of consuming the chat 1fr track');
assert.ok(runtime.includes("card.dataset.expanded='false'"),'new decision cards must start with evidence collapsed');
assert.ok(runtime.includes("input.value='오늘 계획을 만들어줘'"),'plan action must remain wired through the existing Coach proposal flow');
assert.ok(runtime.includes('function actionReason(action,isEn)')&&runtime.includes('최근 회복 근거가 부족해 과도한 개인화를 하지 않고 오늘 상태를 먼저 확인합니다.'),'Korean Coach must localize the canonical next-action reason instead of leaking the English core reason');
assert.ok(runtime.includes('nextReason=actionReason(canonical,isEn)'),'decision details must render the locale-aware canonical reason');
assert.equal(runtime.includes('localStorage.setItem'),false,'decision presentation must not create a direct persistence path');
assert.equal(runtime.includes('.applyWrite('),false,'decision presentation must not bypass the Coach approval boundary');
assert.equal(runtime.includes('>+</'),false,'ambiguous plus-only decision action must not return');
assert.ok(coreLoop.includes("promptStrip=coachRoot.querySelector('.g4-prompt-strip')"),'contextual Coach actions must live inside the existing Coach prompt surface');
assert.equal(coreLoop.includes('gcl-context-label'),false,'standalone action label must not be exposed in Coach');
assert.ok(coreLoop.includes('overflow-x:hidden!important')&&coreLoop.includes('writing-mode:horizontal-tb!important'),'Coach surface must prevent mobile clipping and vertical action pills');
assert.ok(html.includes('garang-coach-decision-v1.js?v=1.4.0-lifecycle'),'production shell must retain the Coach decision runtime');
assert.ok(html.includes('garang-core-loop-v1.js?v=1.1.2-quiet-actions'),'core loop runtime must load the current single-surface release');
console.log('coach-decision-compact-ui: PASS');