const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),pkg=require('../package.json'),manifest=require('../runtime-manifest.json');
const ctx=vm.createContext({console,Date,Math,URL,AbortController,setTimeout,clearTimeout,structuredClone,crypto:crypto.webcrypto,location:{origin:'https://example.test'},GARANG_SERVICES_CONFIG:{apiBase:null}});
for(const file of ['version.js','commercial-core.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);
const tests=[];function test(name,fn){try{fn();tests.push({name,status:'PASS'});}catch(error){tests.push({name,status:'FAIL',error:error.message});process.exitCode=1;}}
test('one version controls package, runtime manifest and browser label',()=>{assert.equal(pkg.version,manifest.version);assert.equal(ctx.GARANG_BUILD.version,pkg.version);});
test('disconnected analytics reports the real state without queuing fake success',()=>{const a=ctx.GarangCommercial.analytics(),x=a.track('screen_view');assert.equal(x.accepted,false);assert.equal(x.reason,'NOT_CONNECTED');assert.equal(a.pending.length,0);});
test('local migration payload is deterministic for the same state',()=>{const state={schemaVersion:6,updatedAtMs:12,workouts:[]},m=ctx.GarangCommercial.migration();assert.equal(m.prepare(state,'u1').migrationId,m.prepare(state,'u1').migrationId);assert.deepEqual(m.prepare(state,'u1').state,state);});
test('agent reads return a clone and ignore unconfirmed or expired memory',()=>{const state={workouts:[{id:'w1'}],memory:{entries:[{id:'ok',userConfirmed:true},{id:'no',userConfirmed:false},{id:'old',userConfirmed:true,expiresAt:'2000-01-01T00:00:00Z'}]}};const gate=ctx.GarangCommercial.createAgentGate(()=>state,()=>{});const rows=gate.read('getWorkoutHistory');rows[0].id='changed';assert.equal(state.workouts[0].id,'w1');assert.deepEqual(Array.from(gate.read('getMemory'),x=>x.id),['ok']);});
test('agent writes require an explicit proposal and confirmation',()=>{let applied=0;const gate=ctx.GarangCommercial.createAgentGate(()=>({}),()=>++applied),x=gate.propose('createPlan',{title:'Run'});assert.equal(applied,0);gate.confirm(x.id,true);assert.equal(applied,1);assert.throws(()=>gate.confirm(x.id,true),/PROPOSAL_ALREADY_RESOLVED/);});
test('rejected agent writes never mutate application state',()=>{let applied=0;const gate=ctx.GarangCommercial.createAgentGate(()=>({}),()=>++applied),x=gate.propose('deleteRecord',{id:'x'});gate.confirm(x.id,false);assert.equal(applied,0);});
test('unknown agent tools are rejected',()=>{const gate=ctx.GarangCommercial.createAgentGate(()=>({}),()=>{});assert.throws(()=>gate.read('readEverything'),/TOOL_NOT_ALLOWED/);assert.throws(()=>gate.propose('executeCode',{}),/TOOL_NOT_ALLOWED/);});
test('every declared runtime asset exists',()=>{for(const group of ['styles','scripts','data','assets'])for(const file of manifest[group])assert.ok(fs.existsSync(path.join(root,file)),file);});
console.log(JSON.stringify(tests,null,2));
