'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const Browser=require('../02_core/decision-intelligence-v1.js');
const Server=require('../functions/src/decision-intelligence.cjs');
const root=path.resolve(__dirname,'..');
let passed=0;const test=(name,fn)=>{fn();passed++;console.log(`PASS ${name}`);};
function state(overrides={}){return {engineVersion:'state-intelligence-v1',asOf:'2026-09-06',confidence:.7,readiness:{value:72,band:'ready',confidence:.8,reasons:['CHECKIN_STABLE']},fatigue:{score:30,band:'low',confidence:.7,reasons:['NO_FATIGUE_CLUSTER']},load:{ratio:1,band:'stable',confidence:.7},patterns:[],goalAlignment:{score:82,band:'aligned',confidence:.7},...overrides};}
test('browser and server decision engines are identical',()=>{const input=state();assert.deepEqual(Browser.decide(input),Server.decide(input));assert.equal(Browser.ENGINE_VERSION,'decision-intelligence-v1');});
test('missing data produces collect_data without a plan proposal',()=>{const d=Browser.decide(state({confidence:.1,readiness:{value:null,band:'unknown',reasons:['NO_RECENT_CHECKIN']},fatigue:{score:null,band:'unknown',reasons:[]}}));assert.equal(d.mode,'collect_data');assert.equal(d.actionProposal,null);});
test('pain caution dominates every training progression signal',()=>{const d=Browser.decide(state({readiness:{value:90,band:'high',reasons:['PAIN_CAUTION']},fatigue:{score:10,band:'low',reasons:[]}}));assert.equal(d.mode,'caution');assert.equal(d.recommendation.intensityScale,0);assert.equal(d.actionProposal,null);});
test('load spike plus guarded readiness chooses recovery',()=>{const d=Browser.decide(state({readiness:{value:52,band:'guarded',reasons:['SHORT_SLEEP']},load:{ratio:1.7,band:'spike',confidence:.8}}));assert.equal(d.mode,'recover');assert.equal(d.actionProposal.requiresConfirmation,true);});
test('high fatigue chooses reduced load instead of progression',()=>{const d=Browser.decide(state({fatigue:{score:70,band:'high',confidence:.8,reasons:['SLEEP_DEBT']}}));assert.equal(d.mode,'reduce');assert.ok(d.recommendation.intensityScale<1);});
test('stable high readiness can allow small controlled progression',()=>{const d=Browser.decide(state({confidence:.8,readiness:{value:88,band:'high',confidence:.9,reasons:['CHECKIN_STABLE']},fatigue:{score:20,band:'low',confidence:.8,reasons:[]},load:{ratio:1.05,band:'stable',confidence:.8}}));assert.equal(d.mode,'progress');assert.ok(d.recommendation.intensityScale>1);assert.ok(d.recommendation.intensityScale<=1.05);});
test('low goal alignment creates goal_focus while keeping confirmation gate',()=>{const d=Browser.decide(state({goalAlignment:{score:52,band:'mixed',confidence:.8}}));assert.equal(d.mode,'goal_focus');assert.equal(d.guardrails.requiresConfirmation,true);});
test('memory evidence is summarized without changing safety priority',()=>{const d=Browser.decide(state(),{memoryContext:{entries:[{id:'g',type:'goal',memoryClass:'semantic',userConfirmed:true,status:'active'},{id:'p',type:'preference',memoryClass:'preference',userConfirmed:true,status:'active'}]}});assert.equal(d.memoryEvidence.evidenceCount,2);assert.equal(d.memoryEvidence.goalMemory,true);assert.equal(d.memoryEvidence.preferenceCount,1);});
test('live bridge, Coach context and visible decision card are wired',()=>{const bridge=fs.readFileSync(path.join(root,'06_features/final/agent-state-hook-v1.js'),'utf8'),coach=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-coach-agent-v4.js'),'utf8'),ui=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-coach-decision-v1.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const token of ['getDecision','getDecisionContext','getDecisionDiagnostics'])assert.ok(bridge.includes(token),token);assert.ok(coach.includes('context.decision=Bridge.getDecisionContext()'));assert.ok(ui.includes('GARANG DECISION'));assert.ok(html.indexOf('./02_core/decision-intelligence-v1.js')<html.indexOf('./06_features/final/agent-state-hook-v1.js'));});
console.log(`${passed} decision intelligence tests passed`);
