'use strict';
const assert=require('node:assert/strict');
const Agent=require('../06_features/final/agent-contract-v1.js');
let passed=0;async function test(name,fn){await fn();passed++;console.log(`PASS ${name}`);}let seq=0;const idFactory=p=>`${p}_${++seq}`,clock=()=>new Date('2026-09-06T00:00:00Z');
(async()=>{
 await test('collect_data decision never creates a write proposal',async()=>{const session=Agent.createSession({getState:()=>({planner:[]}),clock,idFactory}),result=await session.run({message:'Create a plan for today.',language:'en',context:{decision:{mode:'collect_data',engineVersion:'decision-intelligence-v1',actionProposal:null}}},{adapter:Agent.createMockAdapter({idFactory})});assert.equal(result.proposals.length,0);assert.equal(result.reads.length,1);assert.match(result.response.answer,/enough recent state data/i);});
 await test('decision action becomes a pending proposal with decision metadata',async()=>{let applied=0;const decision={engineVersion:'decision-intelligence-v1',mode:'recover',actionProposal:{title:{ko:'회복 중심 세션',en:'Recovery-focused session'},args:{type:'recovery',duration:30,intensityScale:.5,volumeScale:.55,decisionEngineVersion:'decision-intelligence-v1',decisionMode:'recover',reasonCodes:['MODE_RECOVER','LOAD_SPIKE']}}};const session=Agent.createSession({getState:()=>({planner:[]}),applyWrite:(tool,args)=>{applied++;return {tool,args};},clock,idFactory}),result=await session.run({message:'Create a plan for today.',language:'en',context:{decision}},{adapter:Agent.createMockAdapter({idFactory})});assert.equal(applied,0);assert.equal(result.proposals.length,1);const p=result.proposals[0];assert.equal(p.tool,'createPlan');assert.equal(p.args.title,'Recovery-focused session');assert.equal(p.args.duration,30);assert.equal(p.args.decisionMode,'recover');const confirmed=session.confirm(p.id,true);assert.equal(applied,1);assert.equal(confirmed.result.args.decisionEngineVersion,'decision-intelligence-v1');});
 await test('caution decision blocks plan creation even when user asks directly',async()=>{let applied=0;const session=Agent.createSession({getState:()=>({planner:[]}),applyWrite:()=>{applied++;},clock,idFactory}),result=await session.run({message:'오늘 계획을 만들어줘',language:'ko',context:{decision:{mode:'caution',engineVersion:'decision-intelligence-v1',actionProposal:null}}},{adapter:Agent.createMockAdapter({idFactory})});assert.equal(result.proposals.length,0);assert.equal(applied,0);assert.match(result.response.answer,/통증|주의/);});
 console.log(`${passed} decision Agent E2E tests passed`);
})().catch(error=>{console.error(error);process.exitCode=1;});
