'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-today-quiet-surface-v1.js'),'utf8');
const css=fs.readFileSync(path.join(root,'03_styles/runtime/garang-today-quiet-surface-v1.css'),'utf8');
const manifest=fs.readFileSync(path.join(root,'runtime-manifest.json'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.match(js,/garang-today-quiet-surface-v1/);
assert.match(js,/garangQuietToday/);
assert.match(js,/data-gq-details/);
assert.match(js,/garang:screen-rendered/);
assert.match(js,/garang:route-completed/);
assert.doesNotMatch(js,/MutationObserver|\.observe\s*\(/);
assert.doesNotMatch(js,/localStorage|saveState|firestore|setItem/);
for(const selector of ['garangTodayFlow','garangCoreToday','data-golden-path-surface','visual-today-hero','today-snapshot','status-visual-card','today-plan-card','garang-daily-workout']) assert.match(js,new RegExp(selector.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
assert.match(css,/garang-quiet-today/);
assert.match(css,/details\s+summary/);
assert.match(manifest,/garang-today-quiet-surface-v1\.css/);
assert.match(manifest,/garang-today-quiet-surface-v1\.js/);
assert.match(index,/garang-today-quiet-surface-v1\.css/);
assert.match(index,/garang-today-quiet-surface-v1\.js/);
console.log('garang today quiet surface contract: ok');
