'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const index=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('01_app/app.js','utf8'),router=fs.readFileSync('06_features/ui/runtime/garang-router-v1.js','utf8'),registry=fs.readFileSync('06_features/ui/runtime/garang-screen-registry-v1.js','utf8'),shell=fs.readFileSync('06_features/ui/runtime/garang-simplified-shell-v1.js','utf8'),runtime=fs.readFileSync('06_features/ui/runtime/garang-hot-v1.js','utf8'),css=fs.readFileSync('03_styles/runtime/garang-hot-v1.css','utf8'),shellCss=fs.readFileSync('03_styles/runtime/garang-simplified-shell-v1.css','utf8'),mobileCss=fs.readFileSync('03_styles/runtime/garang-commercial-mobile-v1.css','utf8'),manifest=JSON.parse(fs.readFileSync('07_config/manifest.webmanifest','utf8')),runtimeManifest=JSON.parse(fs.readFileSync('runtime-manifest.json','utf8'));
assert.match(index,/data-page="hot"[^>]*data-garang-primary-nav="1"/);
assert.match(index,/garang-hot-v1\.css\?v=1\.0\.0/);assert.match(index,/garang-hot-v1\.js\?v=1\.0\.0/);
assert.match(app,/hot:hotPage/);assert.match(app,/garangHotRoot/);assert.match(router,/['"]hot['"]/);assert.match(registry,/key:'hot'/);assert.match(shell,/screen === 'hot'/);assert.match(shellCss,/repeat\(5,minmax\(0,1fr\)\)/);assert.match(mobileCss,/repeat\(5,1fr\)/);assert.doesNotMatch(css,/#bottomNav/);
assert.equal(manifest.share_target.action,'../?garangShare=hot');assert.equal(manifest.share_target.params.url,'url');assert.ok(runtimeManifest.styles.includes('03_styles/runtime/garang-hot-v1.css'));assert.ok(runtimeManifest.scripts.includes('06_features/ui/runtime/garang-hot-v1.js'));assert.equal(runtimeManifest.runtimeContract.singleOwners.hotSocial,'06_features/ui/runtime/garang-hot-v1.js');
assert.match(runtime,/normalizeInstagramUrl/);assert.match(runtime,/instagram\.com/);assert.match(runtime,/WHY NOT\?/);assert.match(runtime,/navigator\.share/);assert.match(runtime,/garang_hot_v1_pending_routine/);assert.doesNotMatch(runtime,/fetch\([^)]*instagram/i);assert.doesNotMatch(runtime,/download.*video/i);
console.log('GARANG HOT v1 contract: PASS');
