'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),sw=fs.readFileSync(path.join(root,'02_core/sw-runtime.js'),'utf8'),loader=fs.readFileSync(path.join(root,'sw.js'),'utf8'),updater=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-sw-update-v2.js'),'utf8'),bootstrap=fs.readFileSync(path.join(root,'01_app/pwa.js'),'utf8');
assert.match(sw,/CACHE_PREFIX='garang-app-shell-'/);
assert.match(sw,/key\.startsWith\(CACHE_PREFIX\)/,'must delete only GARANG-owned caches');
assert.doesNotMatch(sw,/cached\|\|caches\.match\('\.\/index\.html'\)/,'asset requests must never fall back to HTML');
assert.match(sw,/event\.request\.mode==='navigate'/,'HTML fallback must be navigation-only');
assert.match(sw,/cache\.match\(event\.request\)|cache\.match\(request\)/);
assert.match(sw,/fetch\(request,\{cache:'no-store'\}\)/,'live same-origin runtime requests must bypass stale browser HTTP cache');
assert.match(sw,/fetch\('\.\/index\.html',\{cache:'reload'\}\)/,'new worker install must force a fresh app shell');
const cacheVersion=sw.match(/CACHE=`\$\{CACHE_PREFIX\}(v\d+-\d+)`/)?.[1];
const loaderVersion=loader.match(/app-shell-(v\d+-\d+)/)?.[1];
const importVersion=loader.match(/sw-runtime\.js\?v=app-shell-(v\d+-\d+)/)?.[1];
assert.ok(cacheVersion&&loaderVersion&&importVersion,'SW loader/runtime must expose an app-shell version');
assert.equal(loaderVersion,cacheVersion,'root SW loader and runtime cache must rotate together');
assert.equal(importVersion,cacheVersion,'root SW import query must rotate with the runtime cache');
const durabilityFromUpdater=updater.match(/garang-state-event-durability-v1\.js\?v=([0-9.]+)/)?.[1];
const durabilityFromPrecache=sw.match(/garang-state-event-durability-v1\.js\?v=([0-9.]+)/)?.[1];
assert.ok(durabilityFromUpdater&&durabilityFromPrecache,'State durability runtime must expose a versioned dynamic asset');
assert.equal(durabilityFromPrecache,durabilityFromUpdater,'State durability runtime must be precached at the exact version requested by the app');
const overrideFromUpdater=updater.match(/garang-today-checkin-override-v1\.js\?v=([0-9.]+)/)?.[1];
const overrideFromPrecache=sw.match(/garang-today-checkin-override-v1\.js\?v=([0-9.]+)/)?.[1];
assert.ok(overrideFromUpdater&&overrideFromPrecache,'Today Check-in runtime must expose a versioned dynamic asset');
assert.equal(overrideFromPrecache,overrideFromUpdater,'Today Check-in runtime must be precached at the exact version requested by the app');
const prepFromUpdater=updater.match(/garang-today-workout-prep-integration-v1\.js\?v=([0-9.]+)/)?.[1];
const prepFromPrecache=sw.match(/garang-today-workout-prep-integration-v1\.js\?v=([0-9.]+)/)?.[1];
assert.ok(prepFromUpdater&&prepFromPrecache,'Today workout preparation integration must expose a versioned dynamic asset');
assert.equal(prepFromPrecache,prepFromUpdater,'Today workout preparation integration must be precached at the exact version requested by the app');
assert.match(sw,/EXTRA_ASSETS/,'dynamically loaded critical runtimes must be explicitly available offline');
assert.match(updater,/updateViaCache:'none'/);
assert.match(updater,/registration\.update\(\)/);
assert.match(bootstrap,/updateViaCache:'none'/,'initial PWA registration must not reuse a stale worker script');
assert.match(bootstrap,/registration=>registration\.update\(\)/,'initial PWA registration must explicitly check for the newest worker');
console.log('pwa-safety: PASS');
