'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const services=fs.readFileSync('07_config/garang-services-config.js','utf8');
const app=fs.readFileSync('01_app/app.js','utf8');
const index=fs.readFileSync('functions/index.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('03_styles/runtime/garang-photo-evidence-v1.css','utf8');

assert.match(services,/const mealScanEndpoint=`\$\{apiBase\}\/meal\/scan`/);
assert.match(services,/mealScanEndpoint,/);
assert.match(services,/nutritionLookupEndpoint/);
assert.match(services,/url===nutritionLookupEndpoint&&method==='POST'/);
assert.match(services,/url===mealScanEndpoint&&method==='POST'/);
assert.match(services,/authenticatedFetch\(mealScanEndpoint/);
assert.match(index,/createMealScanHandler/);
assert.match(index,/app\.post\('\/meal\/scan'/);
assert.match(index,/createNutritionLookupHandler/);
assert.match(index,/app\.post\('\/nutrition\/lookup'/);
assert.match(index,/request\.path==='\/coach'\|\|request\.path==='\/meal\/scan'\?coachJson:smallJson/);
assert.match(app,/async function prepareMealScanImage/);
assert.match(app,/pickLabelScan/);
assert.match(app,/nutritionLabelScanItem/);
assert.match(app,/nutrition_label_scan/);
assert.match(app,/LABEL SCAN · 확인 필요/);
assert.match(app,/function mealScanMatch/);
assert.match(app,/JSON\.stringify\(\{image,language:/);
assert.ok(app.includes(',mode})}),payload'),'Meal/Label Scan request must send an explicit vision mode');
assert.match(app,/scanEvidence:\{visionName:/);
assert.match(app,/portionConfidence/);
assert.match(app,/confirmationRequired/);
assert.match(app,/음식\/양 확인 필요|확인 필요/);
assert.match(app,/lookupMealScanNutrition/);
assert.match(app,/estimated/);
assert.match(app,/meal_scan_web_nutrition_resolved/);
assert.match(app,/WEB ESTIMATE/);
assert.match(app,/MEAL_SCAN_NO_FOOD_DETECTED/);
assert.match(app,/사진에서 음식을 찾지 못했습니다\. 음식이 잘 보이는 사진으로 다시 촬영해 주세요\./);
assert.match(app,/GARANG DB/);
assert.match(app,/신뢰 가능한 웹 출처/);
assert.match(app,/Food DB에 자동 매칭되지 않은 항목/);
assert.doesNotMatch(app,/data\.items\.map\(i=>\(\{id:uid\(\),name:String\(i\.name\|\|'음식'\),grams:num\(i\.grams,100\),kcal:num\(i\.kcal\)/,'Meal Vision response must not directly supply nutrition');
assert.match(css,/\.meal-scan-unmatched/);
assert.match(html,/garang-services-config\.js\?v=1\.2\.0-nutrition-web/);
assert.match(html,/food-identity-v1\.js\?v=1\.0\.0/);
assert.match(html,/adaptive-nutrition-learning-v1\.js\?v=1\.2\.0/);
assert.match(html,/app\.js\?v=0\.11\.0-beta\.13-running-analysis/);
assert.match(app,/lookupBarcodeNutrition/);
assert.match(app,/detectBarcodeLocally/);
assert.match(app,/detectBarcodeWithVision/);
assert.match(app,/rememberBarcodeMapping/);
assert.match(app,/REPORT_NO_EXACT/);
assert.match(app,/findReportNoMatch/,'Label product identity must use exact K-FIND report-number matching before fuzzy resolution');
assert.match(app,/nutrition_barcode_mapping_confirmed/);
assert.match(app,/food_identity_miss/);
assert.match(app,/food_identity_correction/);
console.log('Real Meal + Label Scan client contract: PASS');
