'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html');
const manifest=JSON.parse(read('runtime-manifest.json'));
const app=read('01_app/app.js');
const router=read('06_features/ui/runtime/garang-router-v1.js');
const registry=read('06_features/ui/runtime/garang-screen-registry-v1.js');
const runtime=read('06_features/ui/runtime/garang-simplified-shell-v1.js');
const experienceV4=read('06_features/ui/runtime/garang-experience-v4.js');
const nextAction=read('06_features/ui/runtime/garang-today-single-next-action-v1.js');
const goldenPathUi=read('06_features/ui/runtime/garang-golden-path-v1.js');
const css=read('03_styles/runtime/garang-simplified-shell-v1.css');
const coreSource=read('06_features/ui/runtime/garang-core-loop-v1.js');
const planSurface=read('06_features/ui/runtime/garang-plan-execution-ui-v1.js');
const coreCss=read('03_styles/runtime/garang-core-loop-v1.css');
const recovery=read('06_features/ui/runtime/garang-functional-recovery.js');
const Core=require('../06_features/ui/runtime/garang-core-loop-v1.js');

assert.match(app,/function logPage\(\)/,'legacy LOG page must remain for route compatibility');
assert.match(app,/function workoutPage\(/,'Workout route must remain');
assert.match(app,/function nutritionPage\(/,'Nutrition route must remain');
assert.match(app,/function runningPage\(/,'Running route must remain');
assert.match(app,/function bodyPage\(/,'Body route must remain');
assert.match(app,/function plannerPage\(/,'Planner route must remain');
assert.match(app,/function memoryPage\(/,'Memory route must remain');
assert.match(app,/function profilePage\(/,'Profile route must remain');
assert.match(app,/function settingsPage\(/,'Settings route must remain');
assert.match(registry,/memory:\s*Object\.freeze\(\{key:'memory'[\s\S]*selectors:\['#saveMemory'\]/,'Memory must remain a first-class screen identity');
assert.match(registry,/log:\s*Object\.freeze\(\{key:'log'[^\n]*selectors:\['\.visual-log-grid'\]/,'Record must remain a first-class screen identity');
assert.match(registry,/version:'1\.2\.2'/,'Screen Registry version must include the Record identity fix');
assert.match(runtime,/const VERSION = '1\.1\.1'/,'Simplified Shell runtime version must advance with canonical More routing');
assert.match(runtime,/RECORD_ROUTES[\s\S]*workout[\s\S]*nutrition[\s\S]*running[\s\S]*body/,'Record surface must preserve all four existing record routes');
assert.match(runtime,/quick-visual-grid/,'Today quick-record duplicate must be internalized by the shell');
assert.match(runtime,/status-visual-card/,'Today legacy status owner must stay in the DOM but be internalized by the shell');
assert.match(runtime,/garang-state-owner-internalized/,'Today must mark the duplicate state owner as internalized');
assert.match(runtime,/DUPLICATE_MENU_ROUTES/,'duplicate first-level menu routes must be internalized');
assert.match(runtime,/garang-more-sheet \[data-route\][\s\S]*simplified-shell-more/,'visible More routes must be delegated through the canonical Router');
assert.doesNotMatch(runtime,/document\.querySelector\(`\[data-pagego=/,'Record shell must not bypass the canonical Router with a DOM fallback');
assert.match(recovery,/function navigateAny\(page\)[\s\S]*GarangRouter\?\.navigate/,'More menu must use the canonical Router for every non-primary route');
assert.match(recovery,/const route=b\.dataset\.route;if\(!navigateAny\(route\)\)[\s\S]*else\{sheet\.remove\(\);\}/,'More route must navigate before the WebKit-sensitive sheet removal');
assert.match(router,/let ok=callBound\(bottomTarget\(next\)\)[\s\S]*if\(cleanup\)removeTransient\(\);/,'Router must render the requested screen before removing the active More sheet');
assert.doesNotMatch(recovery,/proxy\.dataset\.page=page|proxy\.click\(\)/,'functional recovery must not synthesize navigation through a Bottom Nav proxy');
assert.doesNotMatch(runtime,/localStorage\.|firebase\.|firestore|saveState\(|state\.[a-zA-Z]+\s*=/,'simplified shell must not write user data');
assert.match(router,/VERSION='garang-router-v1\.3\.1-touch-intent'/,'canonical router must use the touch-intent app-bridge version');
assert.doesNotMatch(router,/function viaMenu\(|ok=viaMenu/,'Router must not reopen More as a hidden navigation dependency');
assert.match(router,/function callAppBridge\(route\)/,'Router must delegate non-primary features through one app-bound bridge');
assert.match(router,/bridge\.dataset\.page=route[\s\S]*finally\{bridge\.dataset\.page=previous\|\|'__bridge'/,'app bridge must restore its inert route after every navigation');
assert.match(router,/route==='settings'[\s\S]*settingsTopBtn/,'Settings must use its existing native top control instead of a duplicate bridge');
assert.match(router,/route==='profile'[\s\S]*profileTopBtn/,'Profile must use its existing native top control instead of a duplicate bridge');
assert.match(css,/repeat\(4,minmax\(0,1fr\)\)/,'bottom navigation must expose four primary axes');
assert.match(css,/data-garang-route-bridge="1"\]\{display:none!important\}/,'internal route bridge must never be visible');
assert.match(css,/body\.garang-record-open\{overflow-y:hidden/,'record sheet must explicitly lock vertical background scrolling');
assert.doesNotMatch(css,/@import[^;]*garang-core-loop-v1\.css/,'Simplified Shell must not own Core Loop stylesheet loading through a hidden import');
const coreStyleIndex=manifest.styles.indexOf('03_styles/runtime/garang-core-loop-v1.css'),shellStyleIndex=manifest.styles.indexOf('03_styles/runtime/garang-simplified-shell-v1.css');
assert.ok(coreStyleIndex>=0&&coreStyleIndex<shellStyleIndex,'manifest must explicitly own Core Loop -> Simplified Shell stylesheet order');
assert.equal(manifest.runtimeContract.singleOwners.coreLoopStyle,'03_styles/runtime/garang-core-loop-v1.css','runtime contract must name one Core Loop stylesheet owner');
assert.doesNotMatch(runtime,/createElement\('script'\)|garang-core-loop-v1\.js|goal-alignment-v1\.js/,'Simplified Shell must not dynamically own runtime boot dependencies');
assert.doesNotMatch(experienceV4,/createElement\('script'\)|data-garang-today-single-next-action-v1|garang-today-single-next-action-v1\.js/,'Experience v4 must not dynamically own Today Next Action boot');
assert.match(nextAction,/window\.GarangTodaySingleNextActionV1/,'Today Next Action must remain a first-class runtime');
assert.match(goldenPathUi,/if\(window\.GarangTodaySingleNextActionV1\)return '';/,'Golden Path UI must stay orchestration-only when Today Next Action owns the visible CTA');
assert.doesNotMatch(nextAction,/rootObserver\.observe\(main|observe\(main,\s*\{\s*childList:true,\s*subtree:true/,'Today Next Action must rely on canonical lifecycle events instead of a broad #main observer');
const experienceIndex=manifest.scripts.indexOf('06_features/ui/runtime/garang-experience-v4.js'),nextActionIndex=manifest.scripts.indexOf('06_features/ui/runtime/garang-today-single-next-action-v1.js'),goalIndex=manifest.scripts.indexOf('02_core/goal-alignment-v1.js'),shellIndex=manifest.scripts.indexOf('06_features/ui/runtime/garang-simplified-shell-v1.js'),coreIndex=manifest.scripts.indexOf('06_features/ui/runtime/garang-core-loop-v1.js');
assert.ok(experienceIndex>=0&&experienceIndex<nextActionIndex&&nextActionIndex<goalIndex&&goalIndex<shellIndex&&shellIndex<coreIndex,'manifest must explicitly own deterministic Experience v4 -> Today Next Action -> Goal Alignment -> Simplified Shell -> Core Loop boot order');
assert.equal(manifest.runtimeContract.singleOwners.todayNextAction,'06_features/ui/runtime/garang-today-single-next-action-v1.js','runtime contract must name one Today Next Action owner');
assert.match(html,/garang-screen-registry-v1\.js\?v=1\.2\.2/,'Screen Registry cache key must ship the Record identity fix');
assert.match(html,/garang-core-loop-v1\.css\?v=1\.0\.2-explicit-boot/,'Core Loop stylesheet must ship as an explicit boot asset');
assert.match(html,/garang-simplified-shell-v1\.css\?v=1\.1\.3-explicit-style-owner/,'Simplified Shell stylesheet cache key must ship explicit style ownership');
assert.match(html,/goal-alignment-v1\.js\?v=1\.0\.0-explicit-boot/,'Goal Alignment must ship as an explicit parser-owned runtime dependency');
assert.match(html,/garang-experience-v4\.js\?v=1\.7\.0-essential-first/,'Experience v4 cache key must ship essential-first simplification without changing boot ownership');
assert.match(html,/garang-today-single-next-action-v1\.js\?v=1\.1\.4-explicit-boot-lifecycle/,'Today Next Action must ship as an explicit parser-owned lifecycle runtime');
assert.match(html,/garang-golden-path-v1\.js\?v=1\.0\.3-single-visible-owner/,'Golden Path UI cache key must ship the single visible next-action owner contract');
assert.match(html,/garang-simplified-shell-v1\.js\?v=1\.1\.4-explicit-boot-owner/,'Simplified Shell runtime cache key must ship explicit boot ownership');
assert.match(html,/garang-router-v1\.js\?v=1\.3\.1-touch-intent/,'router cache key must match the touch-intent app-bridge implementation');
const nav=html.match(/<nav class="bottom-nav"[\s\S]*?<\/nav>/)?.[0]||'';
const primary=[...nav.matchAll(/<button(?=[^>]*data-garang-primary-nav="1")(?=[^>]*data-page="([^"]+)")[^>]*>/g)].map(x=>x[1]);
assert.deepEqual(primary,['today','log','coach','progress'],'only Today, Record, Coach and Accumulation may be visible first-level navigation');
const bridges=[...nav.matchAll(/<button(?=[^>]*data-garang-route-bridge="1")(?=[^>]*data-page="([^"]+)")(?=[^>]*hidden)[^>]*>/g)].map(x=>x[1]);
assert.deepEqual(bridges,['__bridge'],'all non-primary features must share one inert hidden app bridge');
assert.doesNotMatch(nav,/<button(?=[^>]*data-garang-primary-nav="1")(?=[^>]*data-page="(?:workout|nutrition|running|body)")/,'record sub-routes must not return to first-level navigation');

for(const forbidden of ['localStorage.setItem','firebase.firestore','applyWrite('])assert.equal(coreSource.includes(forbidden),false,`Core Loop must stay write-free: ${forbidden}`);
assert.match(coreSource,/g2-composer textarea/,'Coach actions must use the existing canonical composer');
assert.match(coreSource,/GarangRouter\?\.navigate/,'Record reuse must use the canonical Router');
assert.match(coreCss,/gcl-accum/,'Accumulation UI must have a dedicated restrained layout');
assert.match(coreCss,/grid-template-rows:auto auto auto minmax\(0,1fr\) auto/,'Coach action row must sit between the decision and message stream');
assert.match(coreCss,/gcl-coach-actions\{grid-row:3/,'Coach actions must occupy the dedicated next-action row');
assert.match(coreSource,/최근 \$\{streak\}일 연속 기록이 이어졌습니다/,'Accumulation streak must explain consecutive recording days');
assert.match(planSurface,/dataset\.gxStreakKind='recording'/,'Accumulation must identify a recording streak separately from plan completion');
assert.match(planSurface,/hero=week\.planned\?pct\(week\.executionRate\):\(week\.recorded\?`\$\{week\.recorded\}\/7`:'—'\)/,'Accumulation must show an explicit unknown hero when no plan or saved weekly evidence exists');
assert.match(planSurface,/GarangGoalAlignment/,'Accumulation must use deterministic goal alignment');
assert.match(coreSource,/gcl-context-actions/,'Coach actions must be embedded as contextual next actions');
assert.doesNotMatch(coreSource,/ACT \/ 행동/,'Coach must not render a standalone ACT section');
const workoutUi=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-workout-intelligence-ui-v1.js'),'utf8');
assert.match(app,/workoutSetDetailsOpen/,'Set-by-set entry must have one canonical app owner');
assert.match(app,/data-set-weight/,'Canonical Log surface must retain per-set weight input');
assert.doesNotMatch(workoutUi,/garang-set-builder|data-garang-set-row/,'Workout intelligence runtime must not inject a duplicate set builder');
const sample={planner:[{date:'2026-09-09',completed:true},{date:'2026-09-09',completed:false}],workouts:[{date:'2026-09-08',name:'Squat',sets:3,reps:5,weight:80}],meals:[{date:'2026-09-08',name:'Meal',items:[{name:'Chicken',grams:150,kcal:250,protein:40}]}],runs:[{date:'2026-09-08',distance:5,duration:30}],body:[{date:'2026-08-20',weight:70},{date:'2026-09-08',weight:69.2}],checkins:[{date:'2026-09-08'}]};
assert.equal(Core.deriveToday(sample,{date:'2026-09-09'}).completion,50);
assert.deepEqual(Core.deriveRecent(sample).map(x=>x.route),['workout','nutrition','running','body']);
assert.equal(Core.deriveAccumulation(sample,{date:'2026-09-09',days:30}).bodyDelta,-0.8);
assert.ok(Core.deriveCoachActions(sample,{date:'2026-09-09'}).length>=2);
const streakSample={workouts:[{date:'2026-09-06'}],meals:[{date:'2026-09-07'}],checkins:[{date:'2026-09-08'}],body:[{date:'2026-09-09',weight:70}],planner:[{date:'2026-09-09',completed:false}]};
const streakModel=Core.deriveAccumulation(streakSample,{date:'2026-09-09',days:30});
assert.equal(streakModel.recordStreak,4);
assert.equal(streakModel.planStreak,0);
assert.deepEqual(streakModel.streakEvidence.map(x=>x.date),['2026-09-06','2026-09-07','2026-09-08','2026-09-09']);
assert.deepEqual(streakModel.streakEvidence.map(x=>x.domains),[['운동'],['식단'],['회복'],['체성분']]);
const emptyModel=Core.deriveAccumulation({}, {date:'2026-09-09',days:30});
assert.equal(emptyModel.hasRecords,false);
assert.equal(emptyModel.streak,0);
assert.equal(emptyModel.planStreak,0);
assert.deepEqual(emptyModel.streakEvidence,[]);
console.log('simplified-shell-v1 contract: PASS');
