'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html');
const app=read('01_app/app.js');
const router=read('06_features/ui/runtime/garang-router-v1.js');
const runtime=read('06_features/ui/runtime/garang-simplified-shell-v1.js');
const css=read('03_styles/runtime/garang-simplified-shell-v1.css');

assert.match(app,/function logPage\(\)/,'legacy LOG page must remain for route compatibility');
assert.match(app,/function workoutPage\(/,'Workout route must remain');
assert.match(app,/function nutritionPage\(/,'Nutrition route must remain');
assert.match(app,/function runningPage\(/,'Running route must remain');
assert.match(app,/function bodyPage\(/,'Body route must remain');
assert.match(app,/function plannerPage\(/,'Planner route must remain');
assert.match(app,/function memoryPage\(/,'Memory route must remain');
assert.match(app,/function profilePage\(/,'Profile route must remain');
assert.match(app,/function settingsPage\(/,'Settings route must remain');
assert.match(runtime,/RECORD_ROUTES[\s\S]*workout[\s\S]*nutrition[\s\S]*running[\s\S]*body/,'Record surface must preserve all four existing record routes');
assert.match(runtime,/quick-visual-grid/,'Today quick-record duplicate must be internalized by the shell');
assert.match(runtime,/DUPLICATE_MENU_ROUTES/,'duplicate first-level menu routes must be internalized');
assert.doesNotMatch(runtime,/document\.querySelector\(`\[data-pagego=/,'Record shell must not bypass the canonical Router with a DOM fallback');
assert.doesNotMatch(runtime,/localStorage\.|firebase\.|firestore|saveState\(|state\.[a-zA-Z]+\s*=/,'simplified shell must not write user data');
assert.match(router,/VERSION='garang-router-v1\.3\.0'/,'canonical router must use the single app-bridge version');
assert.doesNotMatch(router,/function viaMenu\(|ok=viaMenu/,'Router must not reopen More as a hidden navigation dependency');
assert.match(router,/function callAppBridge\(route\)/,'Router must delegate non-primary features through one app-bound bridge');
assert.match(router,/bridge\.dataset\.page=route[\s\S]*finally\{bridge\.dataset\.page=previous\|\|'__bridge'/,'app bridge must restore its inert route after every navigation');
assert.match(router,/route==='settings'[\s\S]*settingsTopBtn/,'Settings must use its existing native top control instead of a duplicate bridge');
assert.match(router,/route==='profile'[\s\S]*profileTopBtn/,'Profile must use its existing native top control instead of a duplicate bridge');
assert.match(css,/repeat\(4,minmax\(0,1fr\)\)/,'bottom navigation must expose four primary axes');
assert.match(css,/data-garang-route-bridge="1"\]\{display:none!important\}/,'internal route bridge must never be visible');
assert.match(css,/body\.garang-record-open\{overflow-y:hidden/,'record sheet must explicitly lock vertical background scrolling');
assert.match(html,/garang-simplified-shell-v1\.css\?v=1\.1\.0/,'simplified shell stylesheet must boot at the current version');
assert.match(html,/garang-simplified-shell-v1\.js\?v=1\.1\.0/,'simplified shell runtime must boot at the current version');
assert.match(html,/garang-router-v1\.js\?v=1\.3\.0/,'router cache key must match the single app-bridge implementation');
const nav=html.match(/<nav class="bottom-nav"[\s\S]*?<\/nav>/)?.[0]||'';
const primary=[...nav.matchAll(/<button(?=[^>]*data-garang-primary-nav="1")(?=[^>]*data-page="([^"]+)")[^>]*>/g)].map(x=>x[1]);
assert.deepEqual(primary,['today','log','coach','progress'],'only Today, Record, Coach and Accumulation may be visible first-level navigation');
const bridges=[...nav.matchAll(/<button(?=[^>]*data-garang-route-bridge="1")(?=[^>]*data-page="([^"]+)")(?=[^>]*hidden)[^>]*>/g)].map(x=>x[1]);
assert.deepEqual(bridges,['__bridge'],'all non-primary features must share one inert hidden app bridge');
assert.doesNotMatch(nav,/<button(?=[^>]*data-garang-primary-nav="1")(?=[^>]*data-page="(?:workout|nutrition|running|body)")/,'record sub-routes must not return to first-level navigation');
console.log('simplified-shell-v1 contract: PASS');
