'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const sanitizer=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-state-sanitizer-v1.js'),'utf8');
const sync=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-sync-durability-v1.js'),'utf8');
const route=fs.readFileSync(path.join(root,'06_features/ui/runtime/garang-auth-route-reconcile-v1.js'),'utf8');
const chrome=fs.readFileSync(path.join(root,'03_styles/runtime/garang-app-chrome-fix-v1.css'),'utf8');
const polish=fs.readFileSync(path.join(root,'03_styles/runtime/garang-polish-v3.css'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const swRuntime=fs.readFileSync(path.join(root,'02_core/sw-runtime.js'),'utf8');
assert.ok(html.indexOf('garang-state-sanitizer-v1.js')<html.indexOf('garang-sync-durability-v1.js'),'sanitizer must run before sync runtime');
assert.ok(html.indexOf('./01_app/app.js')<html.indexOf('garang-auth-route-reconcile-v1.js'),'route reconciliation must reuse the canonical app navigation after app boot');
assert.ok(html.includes('garang-app-chrome-fix-v1.css'));
for(const forbidden of ['addEventListener(\'click\'','addEventListener("click"','setInterval(','MutationObserver','firebase.','Storage.prototype'])assert.equal(sanitizer.includes(forbidden),false,`data sanitizer must stay non-interactive: ${forbidden}`);
assert.equal(sync.includes('stopImmediatePropagation'),false,'sync runtime must never stop unrelated tap propagation');
assert.ok(sync.includes('safeCloudState(snapshot.data(),uid)'),'cloud state must be sanitized before app render');
assert.ok(sync.includes('garang:cloud-state-ready'),'sync runtime must publish the one-shot authenticated recovery boundary');
for(const forbidden of ['setInterval(','MutationObserver','stopImmediatePropagation','preventDefault('])assert.equal(route.includes(forbidden),false,`route recovery must not own global interactions: ${forbidden}`);
assert.ok(route.includes('today.click()'),'route recovery must invoke the app-owned Today navigation handler');
assert.ok(chrome.includes('#appView:not([hidden]) #menuBtn.icon-btn'));assert.ok(chrome.includes('display:grid!important'));
assert.equal(/body:has\(\.garang-coach-v2\) \.bottom-nav\{display:none!important\}/.test(polish),false,'Coach must never hide global bottom navigation');
assert.ok(/touch-auth-recovery-v\d+-20260906/.test(sw),'root service worker bytes must be versioned');
assert.ok(/garang-touch-auth-recovery-v\d+-20260906/.test(swRuntime),'shell cache must move with root service worker version');
assert.ok(swRuntime.includes('./06_features/ui/runtime/garang-auth-route-reconcile-v1.js'));
console.log('touch-state-recovery-contract: PASS');
