'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'01_app','app.js'),'utf8');
const runtime=fs.readFileSync(path.join(root,'06_features','ui','runtime','garang-workout-execution-v2.js'),'utf8');
const intelligence=fs.readFileSync(path.join(root,'06_features','ui','runtime','garang-workout-intelligence-ui-v1.js'),'utf8');
const workoutFlow=fs.readFileSync(path.join(root,'06_features','ui','runtime','garang-workout-flow-v1.js'),'utf8');
const css=fs.readFileSync(path.join(root,'03_styles','runtime','garang-workout-execution-v2.css'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'runtime-manifest.json'),'utf8'));

assert.match(app,/GarangWorkoutExecutionBridge/,'app must expose a read-only workout execution bridge');
assert.ok(app.includes("execution=rows.some(row=>row.dataset.executionEnhanced==='true')"),'execution mode must save completed set rows only');
assert.ok(app.includes("executionMode&&!executionImport&&!details.length"),'manual execution must reject adding an exercise with zero completed sets while preserving explicit imports');
assert.ok(intelligence.includes("add.dataset.executionImport='true';add.click()"),'programmatic workout imports must use an explicit execution bypass');
assert.ok(runtime.includes("garang:set-options-toggled"),'execution UI must open set details through the canonical state event');
assert.ok(runtime.includes("host.closest('details')")&&runtime.includes("disclosure.open=true"),'execution set table disclosure must be visibly open on Log entry');
assert.ok(runtime.includes("refreshPrevious(prev)"),'Previous values must refresh when the exercise changes');
assert.ok(runtime.includes("lastResult.unit||'kg'"),'session result volume must label the actual display unit');
assert.ok(runtime.includes("executionImport!=='true'"),'programmatic imports must not start the live session timer');
assert.ok(runtime.includes("current-set"),'execution surface must visually own a current set state');
assert.ok(runtime.includes("execution-compact-fields"),'execution surface must collapse the generic workout form into compact controls');
assert.ok(runtime.includes("executionResetBound"),'clearing a session must reset live execution timing state');
assert.ok(runtime.includes("previousValue"),'Previous values must render from the resolved row value');
assert.ok(runtime.includes("snapshotSetRows")&&runtime.includes("restoreSetRows"),'changing set count must preserve existing execution rows and completion state');
assert.ok(runtime.includes("execution-duration-field"),'manual execution must keep duration editable');
assert.ok(runtime.includes("applyPrefill"),'execution surface must expose a visible-row prefill bridge');
assert.ok(app.includes("executionCompleted:true"),'draft edit rows must reopen as completed execution sets');
assert.ok(app.includes("workoutEditForm={name:x.name"),'draft edit must persist scalar form state across render');
assert.ok(app.includes("if(workoutEditForm){const edit=workoutEditForm;workoutEditForm=null"),'bindWorkout must restore persisted edit form state after render');
assert.ok(app.includes("data-execution-completed=\"'+(row.executionCompleted===true?'true':'false')+'\""),'set renderer must preserve execution completion metadata');
assert.ok(runtime.includes("initiallyComplete"),'execution enhancement must preserve pre-rendered completion state');
assert.ok(runtime.includes("builder.closest('.gws-panel[data-garang-workout-surface=\"log\"]')")&&runtime.includes("log.appendChild(card)"),'session completion card must stay owned by the Log surface');
assert.ok(!runtime.includes("builder.after(card)"),'session completion card must not escape the Log surface');
assert.ok(workoutFlow.includes("GarangWorkoutExecutionV2?.applyPrefill"),'recent-workout reuse must synchronize values into visible execution rows');
assert.ok(workoutFlow.includes("state.active==='log'")&&workoutFlow.includes("GarangWorkoutExecutionV2?.enhance"),'Log activation must deterministically re-enhance the execution table after surface ownership settles');
assert.ok(intelligence.includes("main?.dataset?.garangScreen"),'workout imports must use canonical screen identity instead of bottom-nav identity');
assert.ok(intelligence.includes("GarangRouter?.navigate?.('workout'"),'Daily Workout import must use the canonical Router');
assert.ok(css.includes("safe-area-inset-top")&&css.includes("+ 62px"),'mobile sticky session controls must clear the fixed app header');
for(const token of ['LIVE SESSION','PREVIOUS','workoutExecutionRest','data-execution-set-complete','workout-result-card','garang:screen-rendered','workout_saved'])assert.ok(runtime.includes(token),token);
assert.ok(!runtime.includes('MutationObserver'),'workout execution must use lifecycle events, not a DOM observer');
for(const token of ['.workout-session-bar','.execution-set-row','.set-complete-button','.workout-rest-timer','.workout-result-card','@media(max-width:720px)'])assert.ok(css.includes(token),token);
assert.ok(html.includes('garang-workout-execution-v2.css'),'execution CSS must load');
assert.ok(html.includes('garang-workout-execution-v2.js'),'execution runtime must load');
assert.ok(html.indexOf('garang-workout-library-v2.js')<html.indexOf('garang-workout-execution-v2.js'),'execution layer must load after the workout library layer');
assert.ok(manifest.scripts.includes('06_features/ui/runtime/garang-workout-execution-v2.js'),'runtime manifest must include execution JS');
assert.ok(manifest.styles.includes('03_styles/runtime/garang-workout-execution-v2.css'),'runtime manifest must include execution CSS');
console.log('workout-execution-ui-v2: PASS');