'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'01_app','app.js'),'utf8');
const runtime=fs.readFileSync(path.join(root,'06_features','ui','runtime','garang-workout-execution-v2.js'),'utf8');
const intelligence=fs.readFileSync(path.join(root,'06_features','ui','runtime','garang-workout-intelligence-ui-v1.js'),'utf8');
const workoutFlow=fs.readFileSync(path.join(root,'06_features','ui','runtime','garang-workout-flow-v1.js'),'utf8');
const css=fs.readFileSync(path.join(root,'03_styles','runtime','garang-workout-execution-v2.css'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const polish=fs.readFileSync(path.join(root,'06_features','ui','runtime','garang-polish-v3.js'),'utf8');
const workoutLibrary=fs.readFileSync(path.join(root,'06_features','ui','runtime','garang-workout-library-v2.js'),'utf8');
const swRuntime=fs.readFileSync(path.join(root,'02_core','sw-runtime.js'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'runtime-manifest.json'),'utf8'));

assert.match(app,/GarangWorkoutExecutionBridge/,'app must expose a read-only workout execution bridge');
assert.ok(app.includes("execution=rows.some(row=>row.dataset.executionEnhanced==='true')"),'execution mode must save completed set rows only');
assert.ok(app.includes("executionMode&&!executionImport&&!details.length"),'manual execution must reject adding an exercise with zero completed sets while preserving explicit imports');
assert.ok(intelligence.includes("add.dataset.executionImport='true';add.click()"),'programmatic workout imports must use an explicit execution bypass');
assert.ok(runtime.includes("garang:set-options-toggled"),'execution UI must open set details through the canonical state event');
assert.ok(app.includes("garang:workout-set-rows-rendered"),'app row renderer must publish an explicit execution lifecycle event');
assert.ok(runtime.includes("garang:workout-set-rows-rendered")&&runtime.includes("enhanceRows();updateLive()"),'execution layer must synchronously re-enhance every canonical row render');
assert.ok(app.includes("resetExerciseRows(){workoutSetDraft=[];workoutSetDetailsOpen=true;renderWorkoutSetDetails()"),'execution bridge must reset canonical rows on explicit exercise change');
assert.ok(runtime.includes("bridge()?.resetExerciseRows?.()"),'exercise changes must discard prior exercise completion/value state before re-enhancement');
assert.ok(runtime.includes("host.closest('details')")&&runtime.includes("disclosure.open=true"),'execution set table disclosure must be visibly open on Log entry');
assert.ok(runtime.includes("refreshPrevious(prev)"),'Previous values must refresh when the exercise changes');
assert.ok(runtime.includes("lastResult.unit||'kg'"),'session result volume must label the actual display unit');
assert.ok(app.includes("garang:workout-session-clearing"),'session reset must publish before the app rerenders workout rows');
assert.ok(runtime.includes("garang:workout-session-clearing")&&runtime.includes("liveSetDraft=[]")&&runtime.includes("liveSetCount=0"),'execution layer must clear live row state before session reset rerender');
assert.ok(app.includes("garang:workout-exercise-added")&&app.includes("detail:{imported,groupType:x.groupType,groupId:x.groupId}"),'successful exercise add must publish import status and group execution metadata');
assert.ok(runtime.includes('id="startWorkoutSession"')&&runtime.includes('id="finishWorkoutSession"')&&runtime.includes('aria-label="운동 시작"')&&runtime.includes('aria-label="운동 종료 및 저장"')&&runtime.includes("bar.querySelector('#startWorkoutSession')")&&runtime.includes("bar.querySelector('#finishWorkoutSession')"),'live timer must expose separate symbol-only start and finish controls');
assert.ok(runtime.includes("function finishWorkoutSession()")&&runtime.includes("if(save?.disabled)")&&runtime.includes("add.click()")&&runtime.includes("save.click()"),'finish control must recover from the canonical save button disabled state by staging the current exercise before saving');
assert.ok(runtime.includes("function hardHideCanonicalSave()")&&runtime.includes("hardHideCanonicalSave();\n  }\n  hardHideCanonicalSave();"),'canonical save owner must be hard-hidden again on every execution enhancement after app rerenders');
assert.ok(runtime.includes("draftSummary().exercises===0&&completedCurrent()===0")&&runtime.includes("sessionStartedAt=0;restUntil=0;pendingResult=null")&&runtime.includes("clearPersistedSession()"),'finishing a zero-set session must end cleanly instead of leaving an inert disabled finish control');
assert.ok(runtime.includes("function hardHideCanonicalSave()")&&runtime.includes("save.hidden=true")&&runtime.includes("workout-canonical-save")&&runtime.includes("style.setProperty('display','none','important')")&&runtime.includes("save.setAttribute('aria-hidden','true')"),'legacy text save control must be hard-hidden while remaining the canonical persistence owner');
assert.ok(runtime.includes("garang:workout-exercise-added")&&runtime.includes("updateLive();persistSessionState()"),'adding an exercise must preserve session state without silently starting the workout clock');
assert.ok(!runtime.includes("executionSessionBound"),'raw Add clicks must not start the live session timer');
assert.ok(runtime.includes("current-set"),'execution surface must visually own a current set state');
assert.ok(runtime.includes("headerScope.querySelectorAll('.workout-set-table-head')")&&runtime.includes("forEach(node=>node.remove())"),'active Log enhancement must collapse duplicate set-table headers to exactly one');
assert.ok(runtime.includes("execution-compact-fields"),'execution surface must collapse the generic workout form into compact controls');
assert.ok(runtime.includes("garang:workout-session-clearing")&&runtime.includes("sessionStartedAt=0")&&runtime.includes("restUntil=0"),'clearing a session must reset live execution timing state before rerender');
assert.ok(runtime.includes("if(sessionStartedAt||restUntil)startTicker()"),'remounting an active workout must restart elapsed/rest ticking');
assert.ok(runtime.includes("previousValue"),'Previous values must render from the resolved row value');
assert.ok(runtime.includes("snapshotSetRows")&&runtime.includes("restoreSetRows"),'changing set count must preserve existing execution rows and completion state');
assert.ok(runtime.includes("liveSetDraft")&&runtime.includes("captureLiveSetRows"),'live set values must survive incidental rerenders during execution');
assert.ok(app.includes("toMetricWeight(value){return metricWeight(value);}")&&app.includes("displayWeight(value,digits=1){return shownWeight(value,digits);}"),'execution bridge must expose canonical/display weight conversion');
assert.ok(runtime.includes("weightMetric:metricBufferedWeight")&&runtime.includes("displayBufferedWeight(saved.weightMetric"),'live set buffer must store weight canonically and convert on display restoration');
assert.ok(runtime.includes("liveSetCount")&&runtime.includes("restoringLiveSetCount"),'active set count must survive Workout remounts without truncating buffered rows');
assert.ok(runtime.includes("liveDuration")&&runtime.includes("durationInput.value=liveDuration"),'active workout duration must survive route/settings remounts');
assert.ok(runtime.includes("summary.exercises>liveDraftCount")&&!runtime.includes("summary.exercises!==liveDraftCount"),'removing an unrelated draft exercise must not invalidate active execution rows');
assert.ok(runtime.includes("setsInput.value=String(liveSetCount)")&&runtime.includes("setsInput.dispatchEvent(new Event('input'"),'remount must restore the saved set count before enhancing rows');
assert.ok(runtime.includes("saved?displayBufferedWeight(saved.weightMetric")&&runtime.includes("saved?.reps")&&runtime.includes("saved?.rpe"),'execution enhancement must restore buffered per-set values before falling back to defaults');
assert.ok(runtime.includes("execution-duration-field"),'manual execution must keep duration editable');
assert.ok(app.includes('id="openWorkoutExerciseSearch"')&&app.includes(".garang-exercise-search input")&&app.includes("[data-gws-step=\"exercise\"]"),'Log must expose a magnifier control that routes to the existing exercise search');
assert.ok(app.includes("requestAnimationFrame(()=>document.querySelector('[data-gws-step=\"log\"]')?.click())"),'exercise selection must return directly to Log for fast execution');
assert.ok(workoutLibrary.includes("requestAnimationFrame(()=>document.querySelector('[data-gws-step=\"log\"]')?.click())"),'expanded/search exercise picks must also return directly to Log');
assert.ok(runtime.includes("applyPrefill"),'execution surface must expose a visible-row prefill bridge');
assert.ok(runtime.includes("durationInput.value=liveDuration"),'recent-workout prefill must own duration before live-state recapture');
assert.ok(app.includes("executionCompleted:true"),'draft edit rows must reopen as completed execution sets');
assert.ok(app.includes("workoutEditForm={index:i,name:x.name"),'draft edit must persist scalar form state and original position across render');
assert.ok(app.includes("if(workoutEditForm){const edit=workoutEditForm;workoutEditForm=null"),'bindWorkout must restore persisted edit form state after render');
assert.ok(app.includes("data-execution-completed=\"'+(row.executionCompleted===true?'true':'false')+'\""),'set renderer must preserve execution completion metadata');
assert.ok(runtime.includes("initiallyComplete"),'execution enhancement must preserve pre-rendered completion state');
assert.ok(runtime.includes("builder.closest('.gws-panel[data-garang-workout-surface=\"log\"]')")&&runtime.includes("log.appendChild(card)"),'session completion card must stay owned by the Log surface');
assert.ok(!runtime.includes("builder.after(card)"),'session completion card must not escape the Log surface');
assert.ok(workoutFlow.includes("GarangWorkoutExecutionV2?.applyPrefill"),'recent-workout reuse must synchronize values into visible execution rows');
assert.ok(workoutFlow.includes("state.active==='log'")&&workoutFlow.includes("GarangWorkoutExecutionV2?.enhance"),'Log activation must deterministically re-enhance the execution table after surface ownership settles');
assert.ok(intelligence.includes("main?.dataset?.garangScreen"),'workout imports must use canonical screen identity instead of bottom-nav identity');
assert.ok(intelligence.includes("GarangRouter?.navigate?.('workout'"),'Daily Workout import must use the canonical Router');
assert.ok(css.includes("safe-area-inset-top")&&css.includes("+ 62px"),'mobile sticky session controls must clear the fixed app header');
for(const token of ['LIVE SESSION','PREVIOUS','workoutExecutionRest','data-execution-set-complete','workout-result-card','garang:screen-rendered','workout_saved'])assert.ok(runtime.includes(token),token);
assert.ok(!runtime.includes('MutationObserver'),'workout execution must use lifecycle events, not a DOM observer');
for(const token of ['.workout-session-bar','.execution-set-row','.set-complete-button','.workout-rest-timer','.workout-result-card','@media(max-width:720px)'])assert.ok(css.includes(token),token);
assert.ok(css.includes('Workout commercial UX v4')&&css.includes('.workout-exercise-search-button')&&css.includes('background:#0c0f0d!important'),'Workout v4 must keep picker and active-set controls on one dark surface system');
assert.ok(css.includes('Workout session controls v3')&&css.includes('.workout-session-icon')&&css.includes('touch-action:manipulation'),'session icon controls must own a touch-safe mobile hit area');
assert.ok(css.includes('Workout simplicity v5')&&css.includes('.execution-set-row.current-set .execution-rpe-field')&&css.includes('display:none!important'),'active-set defaults must prioritize weight and reps while keeping RPE behind one-tap details');
const bodyV6Dir=path.join(root,'05_assets','body-model-v6');
for(const gender of ['male','female'])for(const view of ['front','side','back']){const assetPath=path.join(bodyV6Dir,`${gender}-${view}.svg`);assert.ok(fs.existsSync(assetPath),`Body Model v6 asset missing: ${gender}-${view}`);const asset=fs.readFileSync(assetPath,'utf8');assert.match(asset,/MakeHuman hm08 basemesh/);assert.ok((asset.match(/<polygon /g)||[]).length>4500,`Body Model v6 ${gender}-${view} must retain dense mesh geometry`);assert.ok(!asset.includes('feGaussianBlur')&&!asset.includes('filter="url(#soft)"'),`Body Model v6 ${gender}-${view} must render without intentional blur`);}
assert.ok(polish.includes('function v6MeshSVG')&&polish.includes('function v6ZoneMarkup')&&polish.includes('/${person}-${view}.svg?v=7.0.0-muscular-remap')&&polish.includes('data-garang-visual-layer="mesh"')&&polish.includes('data-garang-interaction-layer="zones"'),'Body Model v6 must separate complete mesh visual geometry from interaction/highlight zones');
assert.ok(!polish.includes('transform="scale(2.76923077 2.11538462)"'),'Body Model v6 interaction zones must use the native 720x1100 mesh coordinate system instead of scaled v5 geometry');
assert.ok(polish.includes('function v7DefinitionMarkup')&&polish.includes('data-garang-visual-revision="7"')&&polish.includes("view.querySelectorAll('svg').forEach(node=>node.remove())"),'Body v7 must add anatomy definition, require the v7 renderer revision, and remove duplicate legacy body SVGs');
assert.ok(css.includes('GARANG Body v7')&&css.includes('fill:transparent!important')&&css.includes('pointer-events:all'),'Body v7 hit zones must stay interactive without floating unselected silhouettes');
for(const gender of ['male','female'])for(const view of ['front','side','back'])assert.ok(swRuntime.includes(`./05_assets/body-model-v6/${gender}-${view}.svg?v=7.0.0-muscular-remap`),`Body Model v6 ${gender}-${view} must be available in the offline app shell`);
assert.ok(polish.includes("v6MeshSVG(gender,side)")&&polish.includes("side==='back'")&&polish.includes("gender==='female'"),'Body Model v6 must support male/female FRONT/SIDE/BACK through one renderer contract');
assert.ok(polish.includes('data-garang-classical-model="5"')&&polish.includes('g5-silhouette')&&polish.includes('function v5SideSVG')&&polish.includes('data-g3-view="side"'),'Body Model v5 fallback must preserve FRONT / SIDE / BACK capability and interactive muscle zones');
assert.ok(html.includes('garang-workout-execution-v2.css'),'execution CSS must load');
assert.ok(html.includes('garang-workout-execution-v2.js'),'execution runtime must load');
assert.ok(html.indexOf('garang-workout-library-v2.js')<html.indexOf('garang-workout-execution-v2.js'),'execution layer must load after the workout library layer');
assert.ok(manifest.scripts.includes('06_features/ui/runtime/garang-workout-execution-v2.js'),'runtime manifest must include execution JS');
assert.ok(manifest.styles.includes('03_styles/runtime/garang-workout-execution-v2.css'),'runtime manifest must include execution CSS');
console.log('workout-execution-ui-v2: PASS');
assert.ok(app.includes('id="wSetType"')&&app.includes('value="warmup"')&&app.includes('value="drop"')&&app.includes('value="failure"'),'workout must support warm-up, drop and failure set semantics');
assert.ok(app.includes('id="wRir"')&&app.includes('id="wNotes"'),'workout must support RIR and exercise notes');
assert.ok(app.includes('data-move-workout')&&app.includes('workoutDraft.splice(to,0,item)'),'draft exercises must be reorderable');
assert.ok(runtime.includes('GARANG ')&&runtime.includes('execution-target')&&runtime.includes('TARGET'),'execution table must expose a GARANG target between Previous and Actual');
assert.ok(runtime.includes('targetFor(row)')&&runtime.includes('progressionContext')&&runtime.includes('recentTrend')&&runtime.includes('readiness'),'GARANG target must adapt from recent performance and readiness instead of copying Previous');
assert.ok(runtime.includes('workout-result-pr')&&runtime.includes('estimated 1RM'),'session result must surface a PR benchmark');

assert.ok(app.includes('id="wGroupType"')&&app.includes('value="superset"')&&app.includes('value="circuit"'),'workout must support superset and circuit grouping');
assert.ok(app.includes('id="calcWorkoutPlates"')&&app.includes('workoutPlateResult')&&app.includes('id="wPlateProfile"')&&app.includes('id="wPlateRounding"'),'workout must provide a unit-aware plate calculator with inventory profiles and rounding');

assert.ok(app.includes("weightMetric")&&app.includes("estimated1RMMetric"),'previous-set bridge must expose canonical metric weights for unit-safe GARANG targets');
assert.ok(runtime.includes("base=num(row.weightMetric")&&runtime.includes("displayBufferedWeight(target.weightMetric)"),'GARANG targets must calculate canonically and convert only for display');
assert.ok(app.includes("[data-set-rir]")&&app.includes("[data-set-type]"),'completed set details must persist row-level RIR and set type');
assert.ok(runtime.includes("data-set-type")&&runtime.includes("data-set-rir")&&runtime.includes("saved?.setType")&&runtime.includes("saved?.rir"),'execution rows must own and preserve mixed set semantics');
assert.ok(app.includes("groupType!=='none'&&!groupId"),'superset/circuit entries must reject missing group identifiers');
assert.ok(app.includes("imperial?(profile==='basic'?[45,25,10,5,2.5]:[45,35,25,10,5,2.5])"),'plate calculator must use imperial denominations and profile-aware inventory in lb mode');
assert.ok(app.includes("draftPRComparisons")&&runtime.includes("prComparisons=bridge()?.draftPRComparisons"),'PR result must snapshot pre-save all-time exercise baselines');
assert.ok(runtime.includes("NEW PR")&&runtime.includes("PR 유지"),'session result must distinguish new records from maintained PRs');

assert.ok(runtime.includes("seededEdit?existingWeight"),'editing a seeded draft must preserve entered weights ahead of GARANG target prefills');
assert.ok(app.includes("workoutEditTargetId=x.id")&&app.includes("findIndex(item=>String(item.id)===String(workoutEditTargetId))")&&app.includes("workoutDraft.splice(editIndex,1,x)"),'editing an exercise must use stable draft identity across rerenders and replace atomically');
assert.ok(runtime.includes("pool=improved.length?improved:comparisons"),'NEW PR metric must be selected from exercises that actually improved');

// Workout session resilience v1
assert.ok(runtime.includes("SESSION_KEY='garang_workout_session_v2'")&&runtime.includes('sessionStorage.setItem(SESSION_KEY')&&runtime.includes('hydrateSessionState()'),'active workout execution must survive reloads through session-scoped persistence');
assert.ok(app.includes('sessionDraft(){return clone(workoutDraft);}')&&app.includes('restoreSessionDraft(items)'),'workout bridge must persist and restore the unsaved exercise draft');
assert.ok(runtime.includes('data-execution-add-set')&&runtime.includes('data-execution-set-delete')&&runtime.includes('changeSetCount('),'sets must be directly addable and removable during execution');
assert.ok(app.includes('exercisePRBaseline(exerciseName){return bestEstimated1RM(exerciseName);}'),'execution must read the canonical pre-session PR baseline');
assert.ok(runtime.includes('function updateLivePR()')&&runtime.includes("NEW PR · +"),'execution must surface an immediate PR delta when the active set improves the baseline');
assert.ok(runtime.includes("BEST ")&&runtime.includes("현재 "),'execution must keep the baseline/current comparison understandable before a new PR');
assert.ok(css.includes('.set-delete-button')&&css.includes('.workout-live-pr'),'direct set controls and live PR cue must be styled');

assert.ok(runtime.includes("startRest(setType='working')")&&runtime.includes("type==='drop'")&&runtime.includes("type==='warmup'")&&runtime.includes("type==='failure'"),'set types must change execution rest semantics');
assert.ok(app.includes("latestWorkoutNote")&&runtime.includes("LAST NOTE"),'exercise notes must carry forward into the next execution session');
assert.ok(app.includes("data-replace-workout")&&app.includes("workoutReplaceIndex")&&app.includes('data-gws-step="exercise"')&&app.includes('data-gws-step="log"'),'exercise replacement must move through the exercise surface and return to Log');
assert.ok(app.includes('id="wBarPreset"')&&app.includes('id="wPlateProfile"')&&app.includes('id="wPlateRounding"'),'plate calculator must expose bar presets, inventory profiles, and rounding');
assert.ok(app.includes("analyzeMuscleLoad")&&app.includes("7D VOLUME")&&app.includes("30D VOLUME"),'workout analytics must expose recent volume and muscle load beyond PR-only cards');
assert.ok(app.includes('id="scheduleWorkoutProgram"')&&app.includes("source:'workout_program'")&&app.includes("templateExercises")&&app.includes("data-plan-start")&&app.includes("workoutActivePlanId"),'Workout must support Planner-backed multi-week programs that can launch and complete in Workout Log');
assert.ok(app.includes('id="syncWorkoutHealth"')&&app.includes("GarangNativeHealthBridge")&&app.includes("garang-health-workout-v1"),'Workout must expose native Health bridge integration with a web export fallback');
assert.ok(app.includes("throughToday=x=>withinDays(x.date,7)&&dateMs(x.date)<=dateMs(today())"),'weekly review must exclude future scheduled program rows from current adherence');
assert.ok(app.includes("v==='20kg'")&&app.includes("v==='15kg'")&&app.includes("v==='45lb'")&&app.includes("shownWeight(metric,1)"),'bar presets must convert canonical weights into the active display unit');

 assert.ok(app.includes('id="wWarmupScheme"')&&app.includes('id="generateWorkoutWarmup"')&&app.includes('id="workoutWarmupResult"'),'workout must expose an in-session percentage warm-up calculator');
assert.ok(app.includes('function workoutWarmupPlan()')&&app.includes("{pct:.5,reps:8}")&&app.includes("{pct:.7,reps:5}")&&app.includes("{pct:.85,reps:3}")&&app.includes("setType:'warmup'"),'warm-up calculator must derive typed warm-up sets from working weight percentages');
assert.ok(app.includes("rounding?Math.round(display/rounding)*rounding:display")&&app.includes("metricWeight(rounded)"),'warm-up calculator must reuse active plate rounding without corrupting canonical metric weight');
assert.ok(app.includes("querySelector('[data-execution-completed=\"true\"]')")&&app.includes("진행 중인 세트를 초기화한 뒤 워밍업을 생성해 주세요."),'warm-up generation must refuse to overwrite completed live sets');
assert.ok(app.includes("GarangWorkoutExecutionV2?.replaceSetPlan?.(plan)")&&runtime.includes('function replaceSetPlan(rows=[])')&&runtime.includes('liveSetCount=liveSetDraft.length')&&runtime.includes('applyPrefill,replaceSetPlan'),'warm-up generation must hand expanded set plans to the live execution state owner');

// Workout grouped execution polish v1
assert.ok(app.includes("weightUnit()==='lb'?45:20"),'imperial plate calculator must default to a standard 45 lb bar');
assert.ok(app.includes("groupKey=String(x.groupType)+':'+String(x.groupId).toLowerCase()")&&app.includes("workoutDraft.splice(last.index+1,0,x)"),'superset/circuit exercises must stay contiguous in the session draft');
assert.ok(app.includes('workout-group-chip')&&app.includes('is-workout-grouped'),'grouped exercises must be visibly labeled in the session draft');
assert.ok(app.includes("detail:{imported,groupType:x.groupType,groupId:x.groupId}"),'group execution metadata must be published on successful add');
assert.ok(app.includes('data-execute-workout')&&app.includes('stageWorkoutDraftExecution'),'grouped draft exercises must expose an explicit execution entry point');
assert.ok(app.includes('function workoutGroupExecutionContext()')&&app.includes('function nextWorkoutGroupTarget(setIndex)'),'app bridge must model grouped round context and deterministic next targets');
assert.ok(app.includes('function workoutGroupStartIndex(index)')&&app.includes('member.rows[round]?.executionCompleted!==true'),'starting any grouped member must normalize to the earliest incomplete round/member');
assert.ok(app.includes('executionDraftId:workoutExecutionDraftId||null')&&app.includes('workoutExecutionDraftId=value?.executionDraftId'),'active grouped exercise identity must survive session recovery');
assert.ok(app.includes('persistExecutionRows(rows)')&&runtime.includes('persistExecutionRows?.(liveSetDraft)'),'live row completion state must persist back into the grouped draft owner');
assert.ok(runtime.includes('nextGroupedExecution?.(i)')&&runtime.includes('activateGroupedExercise?.(grouped.target.index)'),'set completion must auto-advance to the next grouped exercise');
assert.ok(runtime.includes('if(grouped.roundEnded)startRest')&&runtime.includes('else stopRest()'),'grouped execution must rest only at round boundaries instead of between superset members');
assert.ok(runtime.includes('workoutGroupExecutionCue')&&css.includes('workout-group-execution-cue'),'group execution must surface current group and round state');


assert.ok(runtime.includes("readinessScore=context?.readiness?.score")&&runtime.includes("readinessScore===null||readinessScore===undefined?NaN"),'missing readiness must remain unknown instead of coercing to a low score');
assert.ok(app.includes("if(workoutDraft.length)return toast('진행 중인 운동 초안을 먼저 저장하거나 초기화해 주세요.')"),'starting a Planner program must not overwrite an active unsaved workout draft');
assert.ok(app.includes("sessionContext(){return {activePlanId:workoutActivePlanId||null")&&app.includes("restoreSessionContext(value)")&&app.includes("workoutActivePlanId=value?.activePlanId")&&runtime.includes("context=bridge()?.sessionContext?.()")&&runtime.includes("restoreSessionContext?.(saved.context||null)"),'active Planner workout identity must survive resilient session persistence and reload');
