
(function(){
'use strict';
const $=id=>document.getElementById(id);let state={type:'workout',data:null,style:'bw',textColor:'#fff',photo:null,position:'bottom'};
function ensureModal(){if($('garangShareModal'))return;const m=document.createElement('div');m.id='garangShareModal';m.className='shareModal';m.innerHTML=`<div class="shareSheet"><div class="shareHeader"><div><span class="eyebrow">GARANG SHARE</span><h3 style="margin:4px 0">인증 카드</h3><small class="muted">사용자 사진/영상이 주인공이고 기록은 작게 보조합니다.</small></div><button class="ghostBtn" onclick="garangCloseShare()">닫기</button></div><div class="shareCanvasWrap"><canvas id="garangShareCanvas" width="1080" height="1920"></canvas></div><div class="shareControls"><div><b>스타일</b><div class="shareRow"><button data-style="bw">흑백</button><button data-style="white">화이트</button><button data-style="black">블랙</button><button data-style="minimal">미니멀</button></div></div><div><b>텍스트 위치</b><div class="shareRow"><button data-pos="top">위</button><button data-pos="bottom">아래</button></div></div><div><b>사진/영상 추가</b><input id="shareMediaInput" type="file" accept="image/*,video/*"><div id="shareMediaPreview"></div></div><div class="shareActions"><button id="shareDownload" class="sharePrimary">인증 이미지 저장</button><button id="shareNative">공유하기</button></div><button id="shareOverlay" class="ghostBtn">투명 오버레이 PNG 저장</button></div></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)window.garangCloseShare()});m.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{state.style=b.dataset.style;render()});m.querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{state.position=b.dataset.pos;render()});$('shareMediaInput').onchange=loadMedia;$('shareDownload').onclick=downloadCard;$('shareNative').onclick=nativeShare;$('shareOverlay').onclick=downloadOverlay}
function getData(){const d=state.data||{};if(state.type==='run'){const r=d.run||d;return {title:'RUN',main:Number(r.distance||0).toFixed(2)+' KM',line1:r.time||'',line2:r.pace||'',line3:Math.round(r.calories||0)+' KCAL',date:r.date||''}}const w=d.workout||d;return {title:(w.exercise||w.name||'WORKOUT').toUpperCase(),main:(w.weight?Number(w.weight)+' KG':'WORKOUT'),line1:(w.sets||0)+' SETS · '+(w.reps||0)+' REPS',line2:(w.volume?Number(w.volume).toLocaleString()+' KG':'') ,line3:(w.durationMin||w.duration||'')+' MIN',date:w.date||''}}
function loadMedia(e){const f=e.target.files?.[0];if(!f)return;const pv=$('shareMediaPreview');if(f.type.startsWith('video/')){const v=document.createElement('video');v.className='videoPreview';v.controls=true;v.muted=true;v.src=URL.createObjectURL(f);pv.innerHTML='';pv.appendChild(v);state.photo=v;state.photoIsVideo=true;v.addEventListener('loadeddata',render,{once:true})}else{const im=new Image();im.className='sharePhotoPreview';im.onload=()=>{state.photo=im;state.photoIsVideo=false;render()};im.src=URL.createObjectURL(f);pv.innerHTML='';pv.appendChild(im)}}
function drawPhoto(ctx){ctx.fillStyle='#101012';ctx.fillRect(0,0,1080,1920);const p=state.photo;if(!p)return;let src=p;if(state.photoIsVideo){try{if(p.readyState<2)return;src=p}catch(e){return}}const sw=src.videoWidth||src.naturalWidth||src.width,sh=src.videoHeight||src.naturalHeight||src.height;if(!sw||!sh)return;const scale=Math.max(1080/sw,1920/sh),w=sw*scale,h=sh*scale;ctx.drawImage(src,(1080-w)/2,(1920-h)/2,w,h)}
function render(){ensureModal();const c=$('garangShareCanvas'),ctx=c.getContext('2d');drawPhoto(ctx);const d=getData();const white=state.style==='white';const black=state.style==='black';const color=white?'#111':black?'#fff':state.style==='bw'?'#fff':'#111';const y=state.position==='top'?120:1630;ctx.save();ctx.fillStyle=color;ctx.shadowColor=color==='#fff'?'rgba(0,0,0,.7)':'rgba(255,255,255,.75)';ctx.shadowBlur=6;ctx.textAlign='left';ctx.font='900 32px Arial,sans-serif';ctx.fillText('G',70,y);ctx.font='900 24px Arial,sans-serif';ctx.fillText('GARANG',110,y);ctx.font='900 64px Arial,sans-serif';ctx.fillText(d.main,70,y+82);ctx.font='700 25px Arial,sans-serif';ctx.fillText(d.title,70,y+125);ctx.font='500 24px Arial,sans-serif';ctx.fillText([d.line1,d.line2,d.line3].filter(Boolean).join('   '),70,y+166);ctx.font='500 20px Arial,sans-serif';ctx.fillText(d.date,70,y+205);ctx.restore();document.querySelectorAll('#garangShareModal [data-style]').forEach(b=>b.classList.toggle('selected',b.dataset.style===state.style));document.querySelectorAll('#garangShareModal [data-pos]').forEach(b=>b.classList.toggle('selected',b.dataset.pos===state.position))}
function overlay(){const c=document.createElement('canvas');c.width=1080;c.height=1920;const ctx=c.getContext('2d'),d=getData(),color=state.style==='black'||state.style==='minimal'?'#fff':'#111';ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle=color;ctx.shadowColor=color==='#fff'?'rgba(0,0,0,.6)':'rgba(255,255,255,.6)';ctx.shadowBlur=5;const y=state.position==='top'?120:1630;ctx.font='900 32px Arial';ctx.fillText('G  GARANG',70,y);ctx.font='900 64px Arial';ctx.fillText(d.main,70,y+82);ctx.font='700 25px Arial';ctx.fillText(d.title,70,y+125);ctx.font='500 24px Arial';ctx.fillText([d.line1,d.line2,d.line3].filter(Boolean).join('   '),70,y+166);return c}
function blob(c,type){return new Promise(r=>c.toBlob(r,type||'image/png',.95))}
async function downloadCard(){const b=await blob($('garangShareCanvas'));const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='GARANG-certification.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function downloadOverlay(){const b=await blob(overlay());const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='GARANG-transparent-overlay.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function nativeShare(){const b=await blob($('garangShareCanvas'));const f=new File([b],'GARANG-certification.png',{type:'image/png'});if(navigator.share){try{await navigator.share({title:'GARANG',text:'GARANG workout',files:[f]})}catch(e){}}else downloadCard()}
window.garangOpenShare=function(data){ensureModal();state=Object.assign(state,data||{});if(state.type==='run')state.data=data;else state.data=data;state.photo=null;state.photoIsVideo=false;$('shareMediaInput').value='';$('shareMediaPreview').innerHTML='';$('garangShareModal').classList.add('open');render()};window.garangCloseShare=()=>{$('garangShareModal')?.classList.remove('open')};
// Add share buttons to rendered workout list without replacing existing UI.
function hookWorkout(){const list=$('workoutList');if(!list)return;const obs=new MutationObserver(()=>{list.querySelectorAll('[data-garang-share]').forEach(x=>x.remove());list.querySelectorAll('.workoutItem,.workout-card,.card').forEach(card=>{if(card.dataset.garangHook)return;const txt=card.textContent||'';if(!/kg|세트|반복|운동/.test(txt))return;card.dataset.garangHook='1';const b=document.createElement('button');b.className='ghostBtn';b.dataset.garangShare='1';b.textContent='공유';b.onclick=()=>{const d=window.__FitMindV6DB?.();const w=(d?.workouts||[]).find(x=>txt.includes(x.exercise||x.name||'___'));if(w)window.garangOpenShare({type:'workout',workout:w,data:w})};card.appendChild(b)})});obs.observe(list,{childList:true,subtree:true})}
setTimeout(hookWorkout,700);
})();
