const assert=require('node:assert/strict');
const {createService,AI_CONTRACT_VERSION,TOOL_CONTRACT_VERSION}=require('../src/core.cjs');
const tests=[];async function test(name,fn){try{await fn();tests.push({name,status:'PASS'});}catch(error){tests.push({name,status:'FAIL',error:error.stack||error.message});process.exitCode=1;}}
(async()=>{
 await test('mock coach returns provider-neutral response with no mutation by default',async()=>{const api=createService(),user={uid:'u'};const r=await api.handle({method:'POST',path:'/v1/coach/respond',user,body:{message:'오늘 컨디션 어때?'}});assert.equal(r.status,200);assert.equal(r.body.data.aiContractVersion,AI_CONTRACT_VERSION);assert.equal(r.body.data.toolContractVersion,TOOL_CONTRACT_VERSION);assert.equal(r.body.data.provider,'mock');assert.deepEqual(r.body.data.actions,[]);});
 await test('coach -> pending createPlan -> confirm -> planner mutation is end-to-end',async()=>{const api=createService({now:()=>Date.parse('2026-09-05T00:00:00Z')}),user={uid:'u'};const r=await api.handle({method:'POST',path:'/v1/coach/respond',user,body:{message:'상체 계획 만들어줘',mockScenario:'createPlan'}});assert.equal(r.status,200);assert.equal(r.body.data.actions.length,1);const action=r.body.data.actions[0];assert.equal(action.tool,'createPlan');assert.equal(action.status,'pending');assert.equal((await api.handle({path:'/v1/data/planner',user})).body.data.value,null);const confirmed=await api.handle({method:'POST',path:`/v1/agent/actions/${action.id}/confirm`,user,body:{confirmed:true}});assert.equal(confirmed.status,200);assert.equal(confirmed.body.data.status,'confirmed');assert.equal(confirmed.body.data.result.domain,'planner');const planner=(await api.handle({path:'/v1/data/planner',user})).body.data.value;assert.equal(planner.length,1);assert.equal(planner[0].origin,'ai');assert.equal(planner[0].done,false);});
 await test('updatePlan applies only after confirmation',async()=>{const api=createService(),user={uid:'u'};await api.handle({method:'PUT',path:'/v1/data/planner',user,body:{value:[{id:'p1',title:'Old',done:false,origin:'user'}]}});const created=await api.handle({method:'POST',path:'/v1/agent/actions',user,body:{tool:'updatePlan',args:{id:'p1',patch:{title:'New',done:true}}}});assert.equal(created.status,201);assert.equal((await api.handle({path:'/v1/data/planner',user})).body.data.value[0].title,'Old');await api.handle({method:'POST',path:`/v1/agent/actions/${created.body.data.id}/confirm`,user,body:{confirmed:true}});const planner=(await api.handle({path:'/v1/data/planner',user})).body.data.value;assert.equal(planner[0].title,'New');assert.equal(planner[0].done,true);});
 await test('saveMemory action writes memory.entries only after confirmation',async()=>{const api=createService(),user={uid:'u'};const r=await api.handle({method:'POST',path:'/v1/coach/respond',user,body:{message:'나는 아침 운동을 선호해 기억해줘',mockScenario:'saveMemory'}});const action=r.body.data.actions[0];assert.equal((await api.handle({path:'/v1/data/memory',user})).body.data.value,null);await api.handle({method:'POST',path:`/v1/agent/actions/${action.id}/confirm`,user,body:{confirmed:true}});const memory=(await api.handle({path:'/v1/data/memory',user})).body.data.value;assert.equal(memory.entries.length,1);assert.equal(memory.entries[0].source,'ai_action');assert.equal(memory.entries[0].userConfirmed,true);});
 await test('deleteRecord removes only the confirmed target record',async()=>{const api=createService(),user={uid:'u'};await api.handle({method:'PUT',path:'/v1/data/workouts',user,body:{value:[{id:'w1',name:'A'},{id:'w2',name:'B'}]}});const created=await api.handle({method:'POST',path:'/v1/agent/actions',user,body:{tool:'deleteRecord',args:{domain:'workouts',id:'w1'}}});assert.equal((await api.handle({path:'/v1/data/workouts',user})).body.data.value.length,2);await api.handle({method:'POST',path:`/v1/agent/actions/${created.body.data.id}/confirm`,user,body:{confirmed:true}});const workouts=(await api.handle({path:'/v1/data/workouts',user})).body.data.value;assert.deepEqual(workouts.map(x=>x.id),['w2']);});
 await test('updateGoal writes canonical profile.goal after confirmation',async()=>{const api=createService(),user={uid:'u'};await api.handle({method:'PUT',path:'/v1/data/profile',user,body:{value:{goal:'유지'}}});const created=await api.handle({method:'POST',path:'/v1/agent/actions',user,body:{tool:'updateGoal',args:{goal:'근력 향상'}}});assert.equal((await api.handle({path:'/v1/data/profile',user})).body.data.value.goal,'유지');await api.handle({method:'POST',path:`/v1/agent/actions/${created.body.data.id}/confirm`,user,body:{confirmed:true}});assert.equal((await api.handle({path:'/v1/data/profile',user})).body.data.value.goal,'근력 향상');});
 await test('rejected AI action never mutates user state',async()=>{const api=createService(),user={uid:'u'};const r=await api.handle({method:'POST',path:'/v1/coach/respond',user,body:{message:'목표를 근력으로 바꿔',mockScenario:'updateGoal'}});const action=r.body.data.actions[0];const rejected=await api.handle({method:'POST',path:`/v1/agent/actions/${action.id}/confirm`,user,body:{confirmed:false}});assert.equal(rejected.body.data.status,'rejected');assert.equal((await api.handle({path:'/v1/data/profile',user})).body.data.value,null);});
 await test('direct tool proposals validate args before action creation',async()=>{const api=createService(),user={uid:'u'};const r=await api.handle({method:'POST',path:'/v1/agent/actions',user,body:{tool:'createPlan',args:{title:'x',date:'tomorrow'}}});assert.equal(r.status,400);assert.equal(r.body.error.code,'INVALID_TOOL_ARGS');assert.equal(api.store.actions.size,0);});
 await test('invalid provider tool output fails closed without pending actions',async()=>{const badProvider={name:'bad',async generate(){return {text:'bad',toolCalls:[{tool:'wipeDatabase',args:{}}]};}};const api=createService({aiProvider:badProvider}),user={uid:'u'};const r=await api.handle({method:'POST',path:'/v1/coach/respond',user,body:{message:'test'}});assert.equal(r.status,502);assert.equal(r.body.error.code,'AI_TOOL_CONTRACT_VIOLATION');assert.equal(api.store.actions.size,0);});
 await test('provider failure is retryable and creates no actions',async()=>{const failing={name:'failing',async generate(){throw new Error('offline');}};const api=createService({aiProvider:failing}),user={uid:'u'};const r=await api.handle({method:'POST',path:'/v1/coach/respond',user,body:{message:'test'}});assert.equal(r.status,502);assert.equal(r.body.error.code,'AI_PROVIDER_ERROR');assert.equal(r.body.error.retryable,true);assert.equal(api.store.actions.size,0);});
 await test('same idempotency key does not create duplicate AI actions',async()=>{const api=createService(),user={uid:'u'},req={method:'POST',path:'/v1/coach/respond',user,headers:{'idempotency-key':'coach-1'},body:{message:'계획 만들어줘',mockScenario:'createPlan'}};const a=await api.handle(req),b=await api.handle(req);assert.deepEqual(b,a);assert.equal(api.store.actions.size,1);});
 console.log(JSON.stringify(tests,null,2));
})();
