const assert=require('node:assert/strict');
const {createService,MemoryStore,MemoryRateLimiter}=require('../src/core.cjs');
const tests=[];async function test(name,fn){try{await fn();tests.push({name,status:'PASS'});}catch(error){tests.push({name,status:'FAIL',error:error.message});process.exitCode=1;}}
(async()=>{
 await test('health is public while user data requires authentication',async()=>{const api=createService();assert.equal((await api.handle({path:'/v1/health'})).status,200);assert.equal((await api.handle({path:'/v1/data/workouts'})).body.error.code,'UNAUTHORIZED');});
 await test('data is isolated by verified user identity',async()=>{const api=createService(),a={uid:'a'},b={uid:'b'};await api.handle({method:'PUT',path:'/v1/data/workouts',user:a,body:{value:[{id:'a1'}]}});assert.equal((await api.handle({path:'/v1/data/workouts',user:a})).body.data.value.length,1);assert.equal((await api.handle({path:'/v1/data/workouts',user:b})).body.data.value,null);});
 await test('idempotency returns the first mutation result',async()=>{const api=createService(),req={method:'PUT',path:'/v1/data/settings',user:{uid:'u'},headers:{'idempotency-key':'same'},body:{value:{a:1}}};const first=await api.handle(req);req.body.value={a:2};const second=await api.handle(req);assert.deepEqual(second,first);assert.deepEqual((await api.handle({path:'/v1/data/settings',user:{uid:'u'}})).body.data.value,{a:1});});
 await test('migration preserves domains and produces an acknowledgement',async()=>{const api=createService(),r=await api.handle({method:'POST',path:'/v1/migrations/local',user:{uid:'u'},body:{migrationId:'u:6:1',schemaVersion:6,state:{workouts:[{id:'w'}],planner:[]}}});assert.equal(r.body.data.accepted,true);assert.deepEqual(new Set(r.body.data.domains),new Set(['workouts','planner']));});
 await test('agent mutation is pending until explicit confirmation',async()=>{const api=createService(),user={uid:'u'},created=await api.handle({method:'POST',path:'/v1/agent/actions',user,body:{tool:'createPlan',args:{title:'Run'}}});assert.equal(created.body.data.status,'pending');const confirmed=await api.handle({method:'POST',path:`/v1/agent/actions/${created.body.data.id}/confirm`,user,body:{confirmed:true}});assert.equal(confirmed.body.data.status,'confirmed');});
 await test('another user cannot confirm an agent action',async()=>{const api=createService(),created=await api.handle({method:'POST',path:'/v1/agent/actions',user:{uid:'a'},body:{tool:'saveMemory',args:{value:'x'}}});const r=await api.handle({method:'POST',path:`/v1/agent/actions/${created.body.data.id}/confirm`,user:{uid:'b'},body:{confirmed:true}});assert.equal(r.status,404);});
 await test('account deletion needs a destructive confirmation',async()=>{const api=createService();assert.equal((await api.handle({method:'DELETE',path:'/v1/account',user:{uid:'u'},body:{}})).body.error.code,'CONFIRMATION_REQUIRED');});
 await test('rate limit is enforced per verified user',async()=>{const api=createService({store:new MemoryStore(),rateLimiter:new MemoryRateLimiter(1,60000)}),u={uid:'u'};assert.equal((await api.handle({path:'/v1/data/profile',user:u})).status,200);assert.equal((await api.handle({path:'/v1/data/profile',user:u})).status,429);});
 console.log(JSON.stringify(tests,null,2));
})();
