const assert=require('node:assert/strict');
const {createService,MemoryStore,MemoryRateLimiter,CONTRACT_VERSION,SCHEMA_VERSION}=require('../src/core.cjs');
const tests=[];async function test(name,fn){try{await fn();tests.push({name,status:'PASS'});}catch(error){tests.push({name,status:'FAIL',error:error.message});process.exitCode=1;}}
(async()=>{
 await test('health is public while user data requires authentication',async()=>{const api=createService(),health=await api.handle({path:'/v1/health'});assert.equal(health.status,200);assert.equal(health.body.data.contractVersion,CONTRACT_VERSION);assert.equal(health.body.data.schemaVersion,SCHEMA_VERSION);assert.equal((await api.handle({path:'/v1/data/workouts'})).body.error.code,'UNAUTHORIZED');});
 await test('data is isolated by verified user identity',async()=>{const api=createService(),a={uid:'a'},b={uid:'b'};await api.handle({method:'PUT',path:'/v1/data/workouts',user:a,body:{value:[{id:'a1'}]}});assert.equal((await api.handle({path:'/v1/data/workouts',user:a})).body.data.value.length,1);assert.equal((await api.handle({path:'/v1/data/workouts',user:b})).body.data.value,null);});
 await test('idempotency returns the first mutation result',async()=>{const api=createService(),req={method:'PUT',path:'/v1/data/settings',user:{uid:'u'},headers:{'idempotency-key':'same'},body:{value:{notifications:true,unit:'metric'}}};const first=await api.handle(req);req.body.value={notifications:false,unit:'imperial'};const second=await api.handle(req);assert.deepEqual(second,first);assert.deepEqual((await api.handle({path:'/v1/data/settings',user:{uid:'u'}})).body.data.value,{notifications:true,unit:'metric'});});
 await test('migration preserves domains and produces a contract acknowledgement',async()=>{const api=createService(),r=await api.handle({method:'POST',path:'/v1/migrations/local',user:{uid:'u'},body:{migrationId:'u:8:1',contractVersion:CONTRACT_VERSION,schemaVersion:SCHEMA_VERSION,state:{workouts:[{id:'w'}],planner:[],userModel:{goal:'strength'},dailyCheckins:[]}}});assert.equal(r.body.data.accepted,true);assert.equal(r.body.data.contractVersion,CONTRACT_VERSION);assert.deepEqual(new Set(r.body.data.domains),new Set(['userModel','workouts','planner','dailyCheckins']));});
 await test('foreign contract and future schema are rejected before persistence',async()=>{const api=createService(),user={uid:'u'};let r=await api.handle({method:'POST',path:'/v1/migrations/local',user,body:{migrationId:'x',contractVersion:'foreign',schemaVersion:SCHEMA_VERSION,state:{workouts:[]}}});assert.equal(r.body.error.code,'INVALID_CONTRACT');r=await api.handle({method:'POST',path:'/v1/migrations/local',user,body:{migrationId:'y',contractVersion:CONTRACT_VERSION,schemaVersion:SCHEMA_VERSION+1,state:{workouts:[]}}});assert.equal(r.body.error.code,'INVALID_SCHEMA');});
 await test('domain writes reject values that violate the frozen top-level type',async()=>{const api=createService(),user={uid:'u'};const r=await api.handle({method:'PUT',path:'/v1/data/workouts',user,body:{value:{id:'not-an-array'}}});assert.equal(r.body.error.code,'INVALID_PAYLOAD');});
 await test('agent mutation is pending until explicit confirmation',async()=>{const api=createService(),user={uid:'u'},created=await api.handle({method:'POST',path:'/v1/agent/actions',user,body:{tool:'createPlan',args:{title:'Run'}}});assert.equal(created.body.data.status,'pending');const confirmed=await api.handle({method:'POST',path:`/v1/agent/actions/${created.body.data.id}/confirm`,user,body:{confirmed:true}});assert.equal(confirmed.body.data.status,'confirmed');});
 await test('another user cannot confirm an agent action',async()=>{const api=createService(),created=await api.handle({method:'POST',path:'/v1/agent/actions',user:{uid:'a'},body:{tool:'saveMemory',args:{value:'x'}}});const r=await api.handle({method:'POST',path:`/v1/agent/actions/${created.body.data.id}/confirm`,user:{uid:'b'},body:{confirmed:true}});assert.equal(r.status,404);});
 await test('account deletion needs a destructive confirmation',async()=>{const api=createService();assert.equal((await api.handle({method:'DELETE',path:'/v1/account',user:{uid:'u'},body:{}})).body.error.code,'CONFIRMATION_REQUIRED');});
 await test('rate limit is enforced per verified user',async()=>{const api=createService({store:new MemoryStore(),rateLimiter:new MemoryRateLimiter(1,60000)}),u={uid:'u'};assert.equal((await api.handle({path:'/v1/data/profile',user:u})).status,200);assert.equal((await api.handle({path:'/v1/data/profile',user:u})).status,429);});
 console.log(JSON.stringify(tests,null,2));
})();
