'use strict';

const {prepareMemoryContext}=require('./memory-engine.cjs');
const {estimateState,compactForContext}=require('./state-intelligence.cjs');
const {decide,compactForContext:compactDecision}=require('./decision-intelligence.cjs');
const {summarizeOutcomeLearning,compactForContext:compactOutcome}=require('./outcome-learning-v2.cjs');
const UserPerformance=require('./user-performance-model-v1.cjs');
const Learning=require('./intelligence-learning-contract.cjs');
const Longitudinal=require('./longitudinal-learning-metrics-v1.cjs');
const Personalization=require('./personalization-policy-v1.cjs');
const Episodes=require('./intelligence-episode-v1.cjs');
const UserResponse=require('./user-response-model-v1.cjs');
const RecommendationPolicy=require('./recommendation-policy-eval-v1.cjs');
const OfflinePolicyEvaluation=require('./offline-policy-evaluation-v1.cjs');
const WorkoutPrescriptionShadow=require('./workout-prescription-shadow-v1.cjs');
const AdaptiveNutritionLearning=require('./adaptive-nutrition-learning-v1.cjs');
const PhysiologicalSignals=require('./physiological-signal-intelligence-v1.cjs');
const IntelligenceDataQuality=require('./intelligence-data-quality-v1.cjs');
const RecommendationQuality=require('./recommendation-quality-eval-v1.cjs');
const ConfidenceCalibration=require('./confidence-calibration-v1.cjs');
const IntelligenceObservability=require('./intelligence-observability-v1.cjs');
const SCORE_FORMULA_VERSION='recording-v2';
const isObject=value=>!!value&&typeof value==='object'&&!Array.isArray(value);
const rows=value=>Array.isArray(value)?value.filter(isObject):[];
const number=value=>Number.isFinite(Number(value))?Number(value):0;
const cap=value=>Math.round(Math.max(0,Math.min(100,value)));
const validLimit=value=>Math.max(1,Math.min(200,Number.parseInt(value,10)||50));
const validMemoryLimit=value=>Math.max(1,Math.min(50,Number.parseInt(value,10)||24));
function parseBearer(value){const match=typeof value==='string'&&value.match(/^Bearer\s+([^\s]+)$/i);return match?match[1]:null;}
function timestamp(row){const date=Date.parse(`${row?.date||''}T12:00:00Z`);return Number.isFinite(date)?date:Number(row?.updatedAtMs||row?.createdAt||0)||0;}
function latest(value,limit){return rows(value).map((row,index)=>({row,index})).sort((a,b)=>timestamp(b.row)-timestamp(a.row)||b.index-a.index).slice(0,limit).map(item=>item.row);}
function runsWithoutCoordinates(value,limit){return latest(value,limit).map(item=>{const {coords,...run}=item;return run;});}
function calculatePerformance(state,asOf){const end=new Date(`${asOf}T23:59:59`).getTime(),start=end-30*86400000,recent=value=>rows(value).filter(item=>{const time=new Date(`${item.date}T12:00:00`).getTime();return time>start&&time<=end;}),workouts=recent(state.workouts),meals=recent(state.meals),runs=recent(state.runs),body=recent(state.body),planner=recent(state.planner),sessions=new Set(workouts.map(item=>item.sessionId||item.id)).size,mealDays=new Set(meals.map(item=>item.date)).size,recovery=planner.filter(item=>item.type==='recovery'),values={exercise:workouts.length?cap(sessions/12*100):null,nutrition:meals.length?cap(mealDays/30*100):null,recovery:recovery.length?cap(recovery.filter(item=>item.done).length/recovery.length*100):null,activity:runs.length||workouts.length?cap(new Set([...runs,...workouts].map(item=>item.date)).size/20*100):null,body:body.length?cap(body.filter(item=>number(item.weight)>0).length/3*100):null},available=Object.values(values).filter(value=>value!==null);return {...values,total:available.length?cap(available.reduce((sum,value)=>sum+value,0)/available.length):null,coverage:available.length,date:asOf,formulaVersion:SCORE_FORMULA_VERSION};}
function buildAgentContext(stateInput,options={}){
 const state=isObject(stateInput)?stateInput:{},now=options.now instanceof Date?options.now:new Date(),limit=validLimit(options.limit),asOf=now.toISOString().slice(0,10),profile=isObject(state.profile)?state.profile:null,ownerUid=String(options.ownerUid||state?.meta?.syncOwnerUid||'').trim()||null;
 const memory=prepareMemoryContext(state.memory,state,{query:String(options.query||''),now,limit:validMemoryLimit(options.memoryLimit),ownerUid}),userState=compactForContext(estimateState(state,{now})),outcome=compactOutcome(summarizeOutcomeLearning(state,{now,days:28,recentDays:7})),decision=compactDecision(decide(userState,{memoryContext:memory,outcomeContext:outcome})),learningGraph=Learning.buildGraph(state,{now,days:28}),intelligenceEpisodes=Episodes.build(state,learningGraph,{days:28,asOf}),intelligenceDataQuality=IntelligenceDataQuality.build(intelligenceEpisodes,{asOf}),userResponseModel=UserResponse.build(intelligenceEpisodes,{asOf}),recommendationPolicy=RecommendationPolicy.build(decision,userResponseModel,{asOf}),offlinePolicyEvaluation=OfflinePolicyEvaluation.build(intelligenceEpisodes,{asOf}),calibrationSamples=rows(offlinePolicyEvaluation.replayRows).map(row=>({id:String(row.episodeId||''),date:String(row.date||''),prediction:Number(row.observedBaseScore),actual:row.observedPositive===true,weight:Math.max(.25,Number(row.responseConfidence)||0)})).filter(row=>Number.isFinite(row.prediction)),confidenceCalibration=ConfidenceCalibration.evaluate(calibrationSamples,{minSamples:12}),workoutPrescriptionShadow=WorkoutPrescriptionShadow.build(state,{asOf}),adaptiveNutritionLearning=AdaptiveNutritionLearning.build(state,{asOf}),physiologicalSignals=PhysiologicalSignals.build(state,{now}),recommendationQuality=RecommendationQuality.build({decision,responseModel:userResponseModel,policy:recommendationPolicy,offlineEvaluation:offlinePolicyEvaluation,workoutPrescription:workoutPrescriptionShadow,adaptiveNutrition:adaptiveNutritionLearning,dataQuality:intelligenceDataQuality,confidenceCalibration}),observabilitySnapshots=rows(offlinePolicyEvaluation.replayRows).map(row=>{const prediction=Number(row.observedBaseScore),actual=row.observedPositive===true?1:0,diff=Number.isFinite(prediction)?prediction-actual:null;return {date:String(row.date||''),qualityOverall:diff===null?null:Math.max(0,1-Math.abs(diff)),calibrationEce:diff===null?null:Math.abs(diff),calibrationBrier:diff===null?null:diff*diff,executionRate:row.observedExecuted===true?1:0,responseConfidence:Number(row.responseConfidence)||0,dataQualityScore:Number(intelligenceDataQuality.score)||0,guardrailViolations:row.guardrailSafe===false?1:0};}),intelligenceObservability=IntelligenceObservability.build(observabilitySnapshots,{baselineWindow:10,recentWindow:5}),userPerformanceModel=UserPerformance.build(state,{days:28,asOf:now,learningGraph}),userPerformance=UserPerformance.compactForContext(userPerformanceModel),longitudinalLearning=Longitudinal.compactForContext(Longitudinal.build(state,learningGraph,{days:28,asOf})),personalizationPolicy=Personalization.compactForContext(Personalization.build(userPerformanceModel,outcome,{responseModel:userResponseModel,candidatePolicy:recommendationPolicy}));
 return {schemaVersion:Number.isFinite(Number(state.schemaVersion))?Number(state.schemaVersion):null,profile,goal:profile&&Object.prototype.hasOwnProperty.call(profile,'goal')?profile.goal:null,workouts:latest(state.workouts,limit),meals:latest(state.meals,limit),runs:runsWithoutCoordinates(state.runs,limit),body:latest(state.body,limit),performanceScore:calculatePerformance(state,asOf),planner:latest(state.planner,limit),memory,userState,outcome,decision,userPerformance,intelligenceEpisodes:Episodes.compactForContext(intelligenceEpisodes),intelligenceDataQuality:IntelligenceDataQuality.compactForContext(intelligenceDataQuality),userResponseModel:UserResponse.compactForContext(userResponseModel),recommendationPolicy:RecommendationPolicy.compactForContext(recommendationPolicy),offlinePolicyEvaluation:OfflinePolicyEvaluation.compactForContext(offlinePolicyEvaluation),workoutPrescriptionShadow:WorkoutPrescriptionShadow.compactForContext(workoutPrescriptionShadow),adaptiveNutritionLearning:AdaptiveNutritionLearning.compactForContext(adaptiveNutritionLearning),recommendationQuality:RecommendationQuality.compactForContext(recommendationQuality),confidenceCalibration:ConfidenceCalibration.compactForContext(confidenceCalibration),intelligenceObservability:IntelligenceObservability.compactForContext(intelligenceObservability),physiologicalSignals:PhysiologicalSignals.compactForContext(physiologicalSignals),longitudinalLearning,personalizationPolicy};
}
module.exports={parseBearer,buildAgentContext,calculatePerformance,validLimit,validMemoryLimit};
