/* Persistence-independent CRUD: a server adapter can replace this repository. */
(function(root){
 'use strict';
 root.GarangRecords={create(getState){
  const G=root.GarangSchema,categories=new Set(['goals','preferences','workout','nutrition','lifestyle','body','planner','coaching','notes']);
  return {
   MemoryService:{list:()=>getState().memory.entries,save(data,id){if(typeof data.text!=='string'||!data.text.trim()||!categories.has(data.category))throw new Error('INVALID_MEMORY');const rows=this.list(),key=String(data.key||'').trim(),old=rows.find(x=>x.id===id)||(!id&&key?rows.find(x=>x.type===(data.type||data.category)&&x.key===key):null);if(id&&!old)throw new Error('NOT_FOUND');const now=new Date().toISOString(),text=data.text.trim().slice(0,10000),history=old&&old.text!==text?[...(old.revisionHistory||[]),{value:old.value??old.text,updatedAt:old.updatedAt||old.createdAt||null}]:[...(old?.revisionHistory||[])],item={...old,...data,id:old?.id||id||G.id(),category:data.category,type:data.type||data.category,key:key||old?.key||'',text,value:text,source:data.source||old?.source||'user',confidence:Math.max(0,Math.min(1,Number(data.confidence??old?.confidence??1))),importance:Math.max(0,Math.min(1,Number(data.importance??old?.importance??.5))),userConfirmed:data.userConfirmed!==false,revisionHistory:history,createdAt:old?.createdAt||now,updatedAt:now};if(old)Object.assign(old,item);else rows.push(item);return item;},remove(id){const state=getState();state.memory.deletedIds=[...new Set([...(state.memory.deletedIds||[]),String(id)])];state.memory.entries=this.list().filter(x=>x.id!==id);}},
   PlannerService:{save(data,id){if(typeof data.title!=='string'||!data.title.trim()||!G.validDate(data.date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(data.time))throw new Error('INVALID_PLAN');const rows=getState().planner,old=rows.find(x=>x.id===id);if(id&&!old)throw new Error('NOT_FOUND');const now=new Date().toISOString(),title=data.title.trim().slice(0,500),changed=old&&(old.title!==title||old.date!==data.date||old.time!==data.time||old.type!==data.type),history=changed?[...(old.revisionHistory||[]),{title:old.title,date:old.date,time:old.time,type:old.type,updatedAt:old.updatedAt||old.createdAt||null}]:[...(old?.revisionHistory||[])],item={...old,...data,id:old?.id||id||G.id(),title,done:old?.done||false,origin:data.origin||old?.origin||'user',confirmed:data.confirmed!==false,revisionHistory:history,createdAt:old?.createdAt||now,updatedAt:now};if(old)Object.assign(old,item);else rows.push(item);return item;},remove(id){getState().planner=getState().planner.filter(x=>x.id!==id);},toggle(id){const x=getState().planner.find(x=>x.id===id);if(!x)throw new Error('NOT_FOUND');x.done=!x.done;x.updatedAt=new Date().toISOString();}}
  };
 }};
})(typeof window==='undefined'?globalThis:window);
