(function(root){
 'use strict';
 const DOMAIN_SET=new Set(['profile','workouts','meals','runs','body','planner','memory','aiChats','scoreHistory','settings']);
 const READ_TOOLS=new Set(['getWorkoutHistory','getNutritionHistory','getRunningHistory','getBodyTrend','getPerformanceScore','getPlanner','getMemory']);
 const WRITE_TOOLS=new Set(['createPlan','updatePlan','saveMemory','deleteRecord','updateGoal']);
 const randomId=(prefix='g')=>root.crypto?.randomUUID?.()||`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2)}`;
 class CommercialError extends Error{constructor(code,message=code,{status=0,retryable=false,traceId=null}={}){super(message);this.name='CommercialError';this.code=code;this.status=status;this.retryable=retryable;this.traceId=traceId;}}
 function config(){return {...(root.GARANG_SERVICES_CONFIG||{}),...(root.GARANG_COMMERCIAL_CONFIG||{})};}
 function apiUrl(path){const base=config().apiBase;if(!base)throw new CommercialError('NOT_CONNECTED','Commercial API is not connected.');const url=new URL(path,base.endsWith('/')?base:base+'/');if(url.origin!==location.origin)throw new CommercialError('UNTRUSTED_ENDPOINT','Commercial API must be same-origin.');return url;}
 async function authToken(){const user=root.firebase?.auth?.().currentUser;if(!user)throw new CommercialError('UNAUTHENTICATED','Sign in is required.',{status:401});return user.getIdToken();}
 async function request(path,{method='GET',body,idempotencyKey,retries=1,signal}={}){
  const traceId=randomId('trace'),url=apiUrl(path),token=await authToken(),headers={'Accept':'application/json','Authorization':`Bearer ${token}`,'X-Trace-Id':traceId};
  if(body!==undefined)headers['Content-Type']='application/json';if(idempotencyKey)headers['Idempotency-Key']=idempotencyKey;
  let attempt=0,last;
  while(attempt<=retries){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),config().timeoutMs||30000);try{const response=await fetch(url,{method,credentials:'same-origin',headers,body:body===undefined?undefined:JSON.stringify(body),signal:signal||controller.signal});const payload=await response.json().catch(()=>null);if(response.ok&&payload?.ok!==false)return payload?.data??payload;if(response.status>=500&&attempt<retries){attempt++;continue;}const e=payload?.error||{};throw new CommercialError(e.code||`HTTP_${response.status}`,e.message||'Request failed.',{status:response.status,retryable:!!e.retryable,traceId:payload?.traceId||traceId});}catch(error){last=error;if(error?.name==='AbortError')last=new CommercialError('TIMEOUT','Request timed out.',{retryable:true,traceId});if(attempt<retries&&(last.retryable||last instanceof TypeError)){attempt++;continue;}throw last;}finally{clearTimeout(timer);}}
 }
 function repository(){return {readDomain(domain){if(!DOMAIN_SET.has(domain))throw new CommercialError('INVALID_DOMAIN');return request(`v1/data/${domain}`);},writeDomain(domain,value,key=randomId('write')){if(!DOMAIN_SET.has(domain))throw new CommercialError('INVALID_DOMAIN');return request(`v1/data/${domain}`,{method:'PUT',body:{value},idempotencyKey:key,retries:0});},deleteDomain(domain,key=randomId('delete')){if(!DOMAIN_SET.has(domain))throw new CommercialError('INVALID_DOMAIN');return request(`v1/data/${domain}`,{method:'DELETE',idempotencyKey:key,retries:0});},exportAll(){return request('v1/user/export');},deleteAccount(confirmation,key=randomId('account-delete')){if(confirmation!=='DELETE')throw new CommercialError('CONFIRMATION_REQUIRED');return request('v1/account',{method:'DELETE',body:{confirmation},idempotencyKey:key,retries:0});}};}
 function migration(){return {prepare(state,uid){if(!uid||!state||typeof state!=='object')throw new CommercialError('INVALID_MIGRATION');const marker=`${uid}:${state.schemaVersion||0}:${state.updatedAtMs||0}`;return {migrationId:marker,schemaVersion:state.schemaVersion,state,preparedAt:new Date().toISOString()};},async upload(state,uid){const payload=this.prepare(state,uid);return request('v1/migrations/local',{method:'POST',body:payload,idempotencyKey:payload.migrationId,retries:0});}};}
 function analytics(){const pending=[];return {pending,track(name,properties={}){if(typeof name!=='string'||!name.trim())throw new CommercialError('INVALID_EVENT');const event={id:randomId('evt'),name:name.trim(),properties,at:new Date().toISOString()};if(!config().apiBase)return {accepted:false,reason:'NOT_CONNECTED',event};pending.push(event);return {accepted:true,event};},async flush(){if(!pending.length)return {sent:0};const batch=pending.splice(0,pending.length);try{await request('v1/analytics/events',{method:'POST',body:{events:batch},idempotencyKey:randomId('analytics'),retries:0});return {sent:batch.length};}catch(error){pending.unshift(...batch);throw error;}}};}
 function errorMonitor(){return {capture(error,context={}){const report={id:randomId('err'),code:String(error?.code||error?.name||'ERROR'),message:String(error?.message||error),context,at:new Date().toISOString()};if(!config().apiBase){console.error('[GARANG]',report);return {sent:false,reason:'NOT_CONNECTED',report};}request('v1/errors',{method:'POST',body:report,idempotencyKey:report.id,retries:0}).catch(()=>{});return {sent:true,report};}};}
 function createAgentGate(getState,applyAction){const proposals=new Map(),logs=[];const readers={getWorkoutHistory:s=>s.workouts,getNutritionHistory:s=>s.meals,getRunningHistory:s=>s.runs,getBodyTrend:s=>s.body,getPerformanceScore:s=>root.GarangPerformance?.calculate(s),getPlanner:s=>s.planner,getMemory:s=>s.memory?.entries?.filter(x=>x.userConfirmed!==false&&(!x.expiresAt||Date.parse(x.expiresAt)>Date.now()))||[]};return {logs,read(tool){if(!READ_TOOLS.has(tool))throw new CommercialError('TOOL_NOT_ALLOWED');return structuredClone(readers[tool](getState()));},propose(tool,args){if(!WRITE_TOOLS.has(tool))throw new CommercialError('TOOL_NOT_ALLOWED');const proposal={id:randomId('proposal'),tool,args:structuredClone(args||{}),status:'pending',createdAt:new Date().toISOString()};proposals.set(proposal.id,proposal);logs.push({...proposal,event:'proposed'});return structuredClone(proposal);},confirm(id,userConfirmed){const proposal=proposals.get(id);if(!proposal)throw new CommercialError('PROPOSAL_NOT_FOUND');if(proposal.status!=='pending')throw new CommercialError('PROPOSAL_ALREADY_RESOLVED');proposal.status=userConfirmed?'confirmed':'rejected';proposal.resolvedAt=new Date().toISOString();let result=null;if(userConfirmed)result=applyAction(proposal.tool,structuredClone(proposal.args));logs.push({...proposal,event:proposal.status});return {proposal:structuredClone(proposal),result};}};}
 root.GarangCommercial={CommercialError,DOMAIN_SET,READ_TOOLS,WRITE_TOOLS,request,repository,migration,analytics,errorMonitor,createAgentGate,connected:()=>!!config().apiBase,build:root.GARANG_BUILD};
})(typeof window==='undefined'?globalThis:window);

