from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f"missing expected snippet in {path}: {old[:120]!r}")
    if text.count(old) != 1:
        raise SystemExit(f"expected one snippet in {path}, found {text.count(old)}")
    p.write_text(text.replace(old, new, 1))


# Remove the signed-out demo entry and stale demo re-entry behavior.
replace_once('index.html', '<p class="auth-note">로그인 없이도 로컬 데모에서 전체 기능을 확인할 수 있습니다.</p><button id="demoBtn" class="ghost wide" type="button">데모로 시작하기</button>', '')
replace_once('01_app/app.js', "const DEMO_KEY = 'garang_demo_state_v3';", "const SIGNED_OUT_KEY = 'garang_signed_out_v1';")
replace_once('01_app/app.js', 'let storageKey=DEMO_KEY, syncTimer=null, syncRetry=0, cloudHydrated=true, cloudSyncPending=false;', 'let storageKey=SIGNED_OUT_KEY, syncTimer=null, syncRetry=0, cloudHydrated=true, cloudSyncPending=false;')
replace_once('01_app/app.js', "      else if(localStorage.getItem('garang_demo')==='1'){setCloudHydrationReady(true);storageKey=DEMO_KEY;loadLocal(storageKey);showApp();}\n      else{setCloudHydrationReady(true);showAuth();}", "      else{localStorage.removeItem('garang_demo');setCloudHydrationReady(true);storageKey=SIGNED_OUT_KEY;showAuth();}")
replace_once('01_app/app.js', "  $('demoBtn').onclick=()=>{localStorage.setItem('garang_demo','1');storageKey=DEMO_KEY;loadLocal(storageKey);state.profile=state.profile||{name:'GARANG 사용자',age:23,height:174,weight:67,goal:'퍼포먼스 향상'};saveState({event:'demo_started'});showApp();};\n", '')
replace_once('01_app/app.js', "function logout(){if(firebaseReady&&currentUser)firebase.auth().signOut().catch(()=>{});clearTimeout(syncTimer);cloudSyncPending=false;setCloudHydrationReady(true);localStorage.removeItem('garang_demo');currentUser=null;storageKey=DEMO_KEY;showAuth();}", "function logout(){if(firebaseReady&&currentUser)firebase.auth().signOut().catch(()=>{});clearTimeout(syncTimer);cloudSyncPending=false;setCloudHydrationReady(true);localStorage.removeItem('garang_demo');currentUser=null;storageKey=SIGNED_OUT_KEY;showAuth();}")

# Ephemeral Coach photo attachment runtime. Raw image data never touches localStorage/Firebase state.
multimodal = r'''/* GARANG Coach Multimodal v1
   Ephemeral one-photo attachment for authenticated Coach requests.
   Raw image data lives only in memory until the next Coach request and is never written to GARANG state/localStorage. */
(()=>{
'use strict';
if(window.__garangCoachMultimodalV1)return;window.__garangCoachMultimodalV1=true;
const MAX_FILE_BYTES=8*1024*1024,MAX_DATA_URL=2600000;
let draft=null,queued=false;
const ko=()=>document.documentElement.lang!=='en';
function clear(){draft=null;document.querySelectorAll('.g6-photo-preview').forEach(el=>el.remove());}
function consumeForRequest(){if(!draft)return null;const out=draft;clear();return out;}
function style(){if(document.getElementById('garang-coach-multimodal-v1-style'))return;const s=document.createElement('style');s.id='garang-coach-multimodal-v1-style';s.textContent=`.g6-photo-tools{display:flex;align-items:center;gap:7px;margin:0 0 7px}.g6-photo-button{min-width:38px;height:34px;border:1px solid rgba(255,255,255,.1);border-radius:9px;background:#0c0f0d;color:#d7dad6;padding:0 10px;font:600 11px/1 var(--g2-ui,system-ui);touch-action:manipulation}.g6-photo-button:focus-visible{outline:1px solid rgba(79,174,146,.7)}.g6-photo-note{color:#777d78;font:500 9px/1.35 var(--g2-ui,system-ui)}.g6-photo-preview{display:flex;align-items:center;gap:9px;padding:8px;border:1px solid rgba(255,255,255,.09);border-radius:10px;background:#0a0c0b;margin:0 0 7px}.g6-photo-preview img{width:48px;height:48px;border-radius:8px;object-fit:cover}.g6-photo-preview span{flex:1;color:#aeb3ae;font:500 10px/1.35 var(--g2-ui,system-ui)}.g6-photo-preview button{border:0;background:transparent;color:#aeb3ae;font-size:16px;padding:8px}`;document.head.appendChild(s);}
function read(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(r.error||new Error('PHOTO_READ_FAILED'));r.readAsDataURL(file);});}
function imageFrom(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('PHOTO_DECODE_FAILED'));image.src=src;});}
async function compress(file){
 if(!file||!/^image\/(jpeg|png|webp)$/i.test(file.type||''))throw new Error(ko()?'JPG, PNG, WebP 사진만 사용할 수 있습니다.':'Use a JPG, PNG, or WebP image.');
 if(file.size>MAX_FILE_BYTES)throw new Error(ko()?'사진은 8MB 이하로 선택해 주세요.':'Choose an image under 8 MB.');
 const src=await read(file),image=await imageFrom(src);let limit=1280,quality=.82;
 for(let attempt=0;attempt<3;attempt++){
  const scale=Math.min(1,limit/Math.max(image.naturalWidth||1,image.naturalHeight||1)),w=Math.max(1,Math.round(image.naturalWidth*scale)),h=Math.max(1,Math.round(image.naturalHeight*scale));
  const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d',{alpha:false}).drawImage(image,0,0,w,h);
  const dataUrl=canvas.toDataURL('image/jpeg',quality);if(dataUrl.length<=MAX_DATA_URL)return {kind:'body_photo',mediaType:'image/jpeg',dataUrl};
  limit=1024;quality=.68;
 }
 throw new Error(ko()?'사진을 더 작은 크기로 선택해 주세요.':'Choose a smaller image.');
}
function renderPreview(wrap){wrap.querySelector('.g6-photo-preview')?.remove();if(!draft)return;const box=document.createElement('div');box.className='g6-photo-preview';const img=document.createElement('img');img.alt=ko()?'전송할 사진 미리보기':'Photo preview';img.src=draft.dataUrl;const text=document.createElement('span');text.textContent=ko()?'이 사진은 다음 Coach 요청에만 사용되며 GARANG 기록에는 저장되지 않습니다.':'This photo is used only for the next Coach request and is not saved to GARANG records.';const remove=document.createElement('button');remove.type='button';remove.setAttribute('aria-label',ko()?'사진 제거':'Remove photo');remove.textContent='×';remove.onclick=clear;box.append(img,text,remove);wrap.prepend(box);}
function ensure(root){
 style();const composer=root.querySelector('.g2-composer'),wrap=root.querySelector('.g2-composer-wrap');if(!composer||!wrap||wrap.querySelector('.g6-photo-tools'))return;
 const tools=document.createElement('div');tools.className='g6-photo-tools';const button=document.createElement('button');button.type='button';button.className='g6-photo-button';button.textContent=ko()?'사진':'Photo';button.setAttribute('aria-label',ko()?'Coach에 사진 첨부':'Attach photo to Coach');const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.hidden=true;const note=document.createElement('span');note.className='g6-photo-note';note.textContent=ko()?'사진 1장 · 요청 후 원본 미저장':'1 photo · raw image not saved';button.onclick=()=>input.click();input.onchange=async()=>{const file=input.files?.[0];input.value='';if(!file)return;try{draft=await compress(file);renderPreview(wrap);const textarea=composer.querySelector('textarea');if(textarea&&!String(textarea.value||'').trim()){textarea.value=ko()?'이 사진을 내 GARANG 기록과 함께 보고, 훈련 관점에서 보이는 점을 알려줘.':'Review this photo with my GARANG records and tell me what is visibly relevant to my training.';textarea.dispatchEvent(new Event('input',{bubbles:true}));}}catch(error){window.dispatchEvent(new CustomEvent('garang:error',{detail:{category:'coach_photo',code:'COACH_PHOTO_INVALID',retryable:true}}));const toast=document.getElementById('toast');if(toast){toast.textContent=String(error?.message||error);toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600);}}};tools.append(button,input,note);wrap.insertBefore(tools,composer);renderPreview(wrap);
}
function sync(){queued=false;const root=document.querySelector('.garang-coach-v2');if(root)ensure(root);}
function queue(){if(queued)return;queued=true;requestAnimationFrame(sync);}
window.addEventListener('garang:screen-rendered',event=>{if(event?.detail?.screen!=='coach')clear();queue();});window.addEventListener('garang:coach-mounted',queue);new MutationObserver(queue).observe(document.getElementById('main')||document.body,{childList:true,subtree:true});
window.GarangCoachPhotoDraft=Object.freeze({consumeForRequest,clear,hasDraft:()=>!!draft});queue();
})();
'''
Path('06_features/ui/runtime/garang-coach-multimodal-v1.js').write_text(multimodal)
replace_once('index.html', '<script src="./06_features/ui/runtime/garang-coach-agent-v4.js?v=4.7.0-canonical-daily-plan"></script>', '<script src="./06_features/ui/runtime/garang-coach-agent-v4.js?v=4.7.0-canonical-daily-plan"></script><script src="./06_features/ui/runtime/garang-coach-multimodal-v1.js?v=1.0.0"></script>')

# Browser transport forwards one validated ephemeral image without logging raw data.
replace_once('07_config/garang-services-config.js', "  const text=(value,limit=120)=>String(value??'').trim().slice(0,limit);", "  const text=(value,limit=120)=>String(value??'').trim().slice(0,limit);\n  function coachImageFrom(value){if(!value||typeof value!=='object'||Array.isArray(value))return null;const mediaType=text(value.mediaType,40).toLowerCase(),dataUrl=String(value.dataUrl||'');if(!['image/jpeg','image/png','image/webp'].includes(mediaType))return null;if(!dataUrl.startsWith(`data:${mediaType};base64,`)||dataUrl.length>2600000)return null;return {kind:'body_photo',mediaType,dataUrl};}")
replace_once('07_config/garang-services-config.js', "        const message=String(source?.message||source?.question||'').trim();if(!message){const error=new Error('COACH_MESSAGE_REQUIRED');error.code='COACH_MESSAGE_REQUIRED';throw error;}\n        const language=source?.language==='en'||globalThis.document?.documentElement?.lang==='en'?'en':'ko',headers=new Headers(init.headers||{});headers.set('Content-Type','application/json');headers.set('Authorization',`Bearer ${await token()}`);\n        diag.lastRequest={url:coachEndpoint,method:'POST',language,messageLength:message.length,uid:String(user.uid||'')};diag.stage='coach-fetch';\n        const response=await nativeFetch(coachEndpoint,{...init,method:'POST',headers,body:JSON.stringify({message,language})});diag.stage='coach-response';return response;", "        const language=source?.language==='en'||globalThis.document?.documentElement?.lang==='en'?'en':'ko',draft=source?.image||globalThis.GarangCoachPhotoDraft?.consumeForRequest?.()||null,image=coachImageFrom(draft),messageRaw=String(source?.message||source?.question||'').trim(),message=messageRaw||(image?(language==='en'?'Review this photo with my GARANG records and explain what is visibly relevant to my training.':'이 사진을 내 GARANG 기록과 함께 보고 훈련 관점에서 보이는 점을 알려줘.'):'');if(!message){const error=new Error('COACH_MESSAGE_REQUIRED');error.code='COACH_MESSAGE_REQUIRED';throw error;}\n        const headers=new Headers(init.headers||{});headers.set('Content-Type','application/json');headers.set('Authorization',`Bearer ${await token()}`);\n        diag.lastRequest={url:coachEndpoint,method:'POST',language,messageLength:message.length,hasImage:!!image,uid:String(user.uid||'')};diag.stage='coach-fetch';\n        const response=await nativeFetch(coachEndpoint,{...init,method:'POST',headers,body:JSON.stringify({message,language,...(image?{image}: {})})});diag.stage='coach-response';return response;")

# Server validates image payload and keeps it out of context/state/logs.
replace_once('functions/src/coach-gateway.cjs', "function redactText(value,limit=800){return clean(value,limit).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}/gi,'[redacted-email]').replace(/(?:\\+?\\d[\\d\\s().-]{7,}\\d)/g,'[redacted-phone]');}", "function redactText(value,limit=800){return clean(value,limit).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}/gi,'[redacted-email]').replace(/(?:\\+?\\d[\\d\\s().-]{7,}\\d)/g,'[redacted-phone]');}\nfunction parseCoachImage(value){if(value===undefined||value===null||value==='')return null;if(!value||typeof value!=='object'||Array.isArray(value))throw Object.assign(new Error('COACH_IMAGE_INVALID'),{code:'COACH_IMAGE_INVALID'});const mediaType=clean(value.mediaType,40).toLowerCase();if(!['image/jpeg','image/png','image/webp'].includes(mediaType))throw Object.assign(new Error('COACH_IMAGE_TYPE_UNSUPPORTED'),{code:'COACH_IMAGE_TYPE_UNSUPPORTED'});const dataUrl=String(value.dataUrl||''),prefix=`data:${mediaType};base64,`;if(!dataUrl.startsWith(prefix))throw Object.assign(new Error('COACH_IMAGE_INVALID'),{code:'COACH_IMAGE_INVALID'});const encoded=dataUrl.slice(prefix.length);if(!encoded||!/^[A-Za-z0-9+/]+={0,2}$/.test(encoded))throw Object.assign(new Error('COACH_IMAGE_INVALID'),{code:'COACH_IMAGE_INVALID'});const padding=(encoded.endsWith('==')?2:encoded.endsWith('=')?1:0),bytes=Math.floor(encoded.length*3/4)-padding;if(bytes>2000000)throw Object.assign(new Error('COACH_IMAGE_TOO_LARGE'),{code:'COACH_IMAGE_TOO_LARGE'});return {kind:'body_photo',mediaType,dataUrl,bytes};}")
replace_once('functions/src/coach-gateway.cjs', "  const message=clean(req?.body?.message,1800),language=req?.body?.language==='en'?'en':'ko';if(!message)return res.status(400).json({ok:false,error:{code:'MESSAGE_REQUIRED'}});", "  const language=req?.body?.language==='en'?'en':'ko';let image=null;try{image=parseCoachImage(req?.body?.image);}catch(error){return res.status(400).json({ok:false,error:{code:errorCode(error)}});}const message=clean(req?.body?.message,1800)||(image?(language==='en'?'Review this photo with my GARANG records and explain what is visibly relevant to my training.':'이 사진을 내 GARANG 기록과 함께 보고 훈련 관점에서 보이는 점을 알려줘.'):'');if(!message)return res.status(400).json({ok:false,error:{code:'MESSAGE_REQUIRED'}});")
replace_once('functions/src/coach-gateway.cjs', "observe({event:'llm_request',requestId:id,provider:clean(config?.provider||'openai',40),decisionMode:clean(context?.garangDecision?.mode,40)||null,outcomeClassification:clean(context?.outcomeLearning?.classification,60)||'insufficient_evidence',nutritionMode:clean(context?.nutritionIntelligence?.mode,60)||null,groundingEvidenceCount:Number(context?.knowledgeGrounding?.evidenceCount)||0});", "observe({event:'llm_request',requestId:id,provider:clean(config?.provider||'openai',40),decisionMode:clean(context?.garangDecision?.mode,40)||null,outcomeClassification:clean(context?.outcomeLearning?.classification,60)||'insufficient_evidence',nutritionMode:clean(context?.nutritionIntelligence?.mode,60)||null,groundingEvidenceCount:Number(context?.knowledgeGrounding?.evidenceCount)||0,hasImage:!!image});")
replace_once('functions/src/coach-gateway.cjs', "generated=alignGenerated(await provider.generate({message,context,language,requestId:id}),context)", "generated=alignGenerated(await provider.generate({message,context,language,requestId:id,image}),context)")
replace_once('functions/src/coach-gateway.cjs', "module.exports={createCoachGatewayHandler,minimalContext,buildGroundedContext,compactNutrition,validateGroundingContext,redactText,latestCheckin,normalizeCheckin,normalizeStateForIntelligence,bodyTrend,safeProviderData,verifyGeneratedAlignment,alignGenerated};", "module.exports={createCoachGatewayHandler,minimalContext,buildGroundedContext,compactNutrition,validateGroundingContext,redactText,parseCoachImage,latestCheckin,normalizeCheckin,normalizeStateForIntelligence,bodyTrend,safeProviderData,verifyGeneratedAlignment,alignGenerated};")

# OpenAI Responses API image input. Disable response storage; GARANG still owns the decision.
replace_once('functions/src/llm-provider.cjs', "Treat garangContext.nutritionIntelligence as deterministic supporting context, not permission to mutate a meal plan or invent nutrition facts. If evidence is insufficient, say so.", "Treat garangContext.nutritionIntelligence as deterministic supporting context, not permission to mutate a meal plan or invent nutrition facts. A user-supplied body photo, when present, is ephemeral visual context only: describe only visible training-relevant observations, do not diagnose medical conditions, do not infer protected or sensitive traits, do not estimate an exact body-fat percentage or hidden measurement from the photo, and never treat the image as permission to mutate GARANG state. If evidence is insufficient, say so.")
replace_once('functions/src/llm-provider.cjs', "return {name:'openai',model,async generate({message,context,language='ko',requestId}){", "return {name:'openai',model,async generate({message,context,language='ko',requestId,image}){")
replace_once('functions/src/llm-provider.cjs', "   const body={model,input:[{role:'system',content:[{type:'input_text',text:systemPrompt()}]},{role:'user',content:[{type:'input_text',text:JSON.stringify({language,message,garangContext:context})}]}],max_output_tokens:900,text:{format:{type:'json_schema',name:'garang_coach_response',strict:true,schema:COACH_RESPONSE_SCHEMA}}};", "   const userContent=[{type:'input_text',text:JSON.stringify({language,message,garangContext:context,visualContext:image?{kind:'body_photo',mediaType:image.mediaType}:null})}];if(image?.dataUrl)userContent.push({type:'input_image',image_url:String(image.dataUrl)});const body={model,store:false,input:[{role:'system',content:[{type:'input_text',text:systemPrompt()}]},{role:'user',content:userContent}],max_output_tokens:900,text:{format:{type:'json_schema',name:'garang_coach_response',strict:true,schema:COACH_RESPONSE_SCHEMA}}};")

# Regression contracts.
Path('tests/no-demo-entry.test.cjs').write_text("""'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('01_app/app.js','utf8');
assert.equal(html.includes('id=\"demoBtn\"'),false);assert.equal(html.includes('데모로 시작하기'),false);assert.equal(html.includes('로그인 없이도 로컬 데모'),false);
for(const forbidden of [\"const DEMO_KEY\",\"getItem('garang_demo')\",\"demo_started\",\"$('demoBtn').onclick\"])assert.equal(app.includes(forbidden),false,forbidden);
assert.match(app,/storageKey=SIGNED_OUT_KEY/);console.log('signed-out demo entry removal: PASS');
""")
Path('functions/tests/coach-multimodal.test.cjs').write_text("""'use strict';
const assert=require('node:assert/strict');const {createOpenAIProvider}=require('../src/llm-provider.cjs');const {createCoachGatewayHandler,parseCoachImage}=require('../src/coach-gateway.cjs');
const image={kind:'body_photo',mediaType:'image/jpeg',dataUrl:'data:image/jpeg;base64,aGVsbG8='};
assert.equal(parseCoachImage(image).bytes,5);assert.throws(()=>parseCoachImage({...image,mediaType:'image/svg+xml'}),e=>e?.code==='COACH_IMAGE_TYPE_UNSUPPORTED');
(async()=>{let request;const provider=createOpenAIProvider({apiKey:'secret',fetchImpl:async(_u,init)=>{request=JSON.parse(init.body);return {ok:true,json:async()=>({id:'r',output:[{content:[{text:JSON.stringify({answer:'visible feedback',decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',confidence:.5,alignment:{decisionId:'d1',decisionMode:'maintain',reasonCodesUsed:[]}})}]}]})};}});await provider.generate({message:'사진 봐줘',image,context:{garangDecision:{decisionId:'d1',mode:'maintain'},decisionReasons:[]}});assert.equal(request.store,false);const content=request.input[1].content;assert.equal(content.some(x=>x.type==='input_image'&&x.image_url===image.dataUrl),true);
let captured,events=[];const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>({profile:{goal:'퍼포먼스'},onboarding:{complete:true,goal:'퍼포먼스'},checkins:[],dailyCheckins:[],workouts:[],meals:[],runs:[],body:[],planner:[],memory:{entries:[]}}),providerFactory:()=>({generate:async x=>{captured=x;return {answer:'ok',decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',confidence:.4,metadata:{provider:'mock'},alignment:{decisionId:x.context.garangDecision.decisionId,decisionMode:x.context.garangDecision.mode,reasonCodesUsed:[]}};}}),getProviderConfig:()=>({provider:'mock'}),observe:e=>events.push(e)});const res={statusCode:200,payload:null,status(c){this.statusCode=c;return this;},json(v){this.payload=v;return this;}};await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'사진 봐줘',image},get(){return null;}},res);assert.equal(res.statusCode,200);assert.equal(captured.image.dataUrl,image.dataUrl);const logged=JSON.stringify(events);assert.equal(logged.includes('aGVsbG8='),false);assert.equal(events.find(e=>e.event==='llm_request')?.hasImage,true);console.log('Coach ephemeral multimodal boundary: PASS');})().catch(e=>{console.error(e);process.exit(1);});
""")
replace_once('package.json', 'node tests/demo-feedback-regression.test.cjs &&', 'node tests/demo-feedback-regression.test.cjs && node tests/no-demo-entry.test.cjs &&')
replace_once('package.json', 'node functions/tests/coach-grounding-live-v2.test.cjs && node functions/tests/semantic-alignment.test.cjs', 'node functions/tests/coach-grounding-live-v2.test.cjs && node functions/tests/coach-multimodal.test.cjs && node functions/tests/semantic-alignment.test.cjs')
replace_once('functions/package.json', 'node tests/coach-grounding-live-v2.test.cjs', 'node tests/coach-grounding-live-v2.test.cjs && node tests/coach-multimodal.test.cjs')

# CI/toolchain hardening.
for path in Path('.github/workflows').glob('*.yml'):
    if path.name == 'agent-apply-coach-hardening.yml':
        continue
    path.write_text(path.read_text().replace('actions/checkout@v4','actions/checkout@v7').replace('actions/setup-node@v4','actions/setup-node@v7'))
replace_once('.github/workflows/ci.yml', '      - name: Verify locked dependency contract\n', '      - name: Install locked Functions dependencies\n        run: npm ci --prefix functions --ignore-scripts --no-audit --no-fund\n      - name: Verify locked dependency contract\n')
replace_once('.github/workflows/ci.yml', '      - name: Report dev tooling audit\n', '      - name: Verify Functions production dependency security\n        run: timeout 90s npm audit --prefix functions --omit=dev --audit-level=high\n      - name: Report dev tooling audit\n')
replace_once('.github/workflows/production-coach-activation.yml', 'permissions:\n  contents: read', 'permissions:\n  contents: read\n  id-token: write')
replace_once('.github/workflows/production-coach-activation.yml', '      - name: Install Functions runtime dependencies\n        run: npm install --prefix functions --omit=dev --no-audit --no-fund', '      - name: Install locked Functions runtime dependencies\n        run: npm ci --prefix functions --omit=dev --no-audit --no-fund\n\n      - name: Authenticate to Google Cloud with short-lived OIDC when configured\n        id: wif\n        if: ${{ vars.GARANG_GCP_WORKLOAD_IDENTITY_PROVIDER != \'\' && vars.GARANG_GCP_SERVICE_ACCOUNT != \'\' }}\n        uses: google-github-actions/auth@v3\n        with:\n          project_id: fitfind-ai\n          workload_identity_provider: ${{ vars.GARANG_GCP_WORKLOAD_IDENTITY_PROVIDER }}\n          service_account: ${{ vars.GARANG_GCP_SERVICE_ACCOUNT }}')
replace_once('.github/workflows/production-coach-activation.yml', '          if [[ -n "${FIREBASE_SERVICE_ACCOUNT_FITFIND_AI:-}" ]]; then', '          if [[ "${{ steps.wif.outcome }}" == "success" && -n "${GOOGLE_APPLICATION_CREDENTIALS:-}" ]]; then\n            echo "mode=oidc-wif" >> "$GITHUB_OUTPUT"\n          elif [[ -n "${FIREBASE_SERVICE_ACCOUNT_FITFIND_AI:-}" ]]; then')
replace_once('.github/workflows/production-coach-activation.yml', 'No Firebase deployment credential is configured. Expected FIREBASE_SERVICE_ACCOUNT_FITFIND_AI, GOOGLE_APPLICATION_CREDENTIALS_JSON, or FIREBASE_TOKEN.', 'No Firebase deployment credential is configured. Configure GARANG_GCP_WORKLOAD_IDENTITY_PROVIDER + GARANG_GCP_SERVICE_ACCOUNT for OIDC/WIF, or use the temporary service-account/token fallback.')

gitignore=Path('.gitignore'); text=gitignore.read_text(); line='gha-creds-*.json'; gitignore.write_text(text if line in text else text.rstrip()+f'\n{line}\n')
