const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..');
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>['.git','dist','node_modules'].includes(x.name)?[]:x.isDirectory()?walk(path.join(dir,x.name)):[path.join(dir,x.name)]);}
const files=walk(root),failures=[],counts={javascript:0,json:0,jsonl:0,activeAssets:0};
for(const f of files){const ext=path.extname(f);if(['.js','.cjs'].includes(ext)){counts.javascript++;const result=cp.spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(result.status!==0)failures.push({file:path.relative(root,f),error:result.stderr});}
 if(['.json','.webmanifest','.jsonl'].includes(ext)){try{const text=fs.readFileSync(f,'utf8').replace(/^\uFEFF/,'');if(ext==='.jsonl'){text.split(/\r?\n/).filter(x=>x.trim()).forEach(x=>JSON.parse(x));counts.jsonl++;}else{JSON.parse(text);counts.json++;}}catch(e){failures.push({file:path.relative(root,f),error:e.message});}}}
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),manifest=JSON.parse(fs.readFileSync(path.join(root,'runtime-manifest.json'),'utf8')),pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
if(manifest.version!==pkg.version)failures.push({file:'runtime-manifest.json',error:'Version does not match package.json'});
for(const group of ['styles','scripts','data','assets'])for(const asset of manifest[group]||[]){if(!fs.existsSync(path.join(root,asset)))failures.push({asset,error:'Missing runtime-manifest asset'});}
for(const asset of [...(manifest.styles||[]),...(manifest.scripts||[])])if(!html.includes('./'+asset))failures.push({asset,error:'Runtime entry does not reference declared style/script'});
if((manifest.scripts||[]).some(x=>/v8|v9|v99|integrated/i.test(x)))failures.push({file:'runtime-manifest.json',error:'Historical runtime source is active'});
const assets=new Set([...html.matchAll(/(?:src|href)="([^"]+)"/g)].map(x=>x[1]).filter(x=>!x.startsWith('https:')&&!x.startsWith('data:')).map(x=>x.replace(/^\.\//,'').split('?')[0]));
const app=fs.readFileSync(path.join(root,'01_app/app.js'),'utf8');for(const m of app.matchAll(/(?:loadJSONL?|fetch)\('([^']+)'/g)){const a=m[1];if(!/^https?:|^\//.test(a))assets.add(a.replace(/^\.\//,''));}
for(const asset of assets){if(!asset||asset==='#')continue;counts.activeAssets++;if(!fs.existsSync(path.join(root,asset)))failures.push({asset,error:'Missing active asset'});}
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);if(new Set(ids).size!==ids.length)failures.push({error:'Duplicate shell IDs'});
for(const f of ['services/adapters.js','services/storage.js','02_core/data-schema.js']){const text=fs.readFileSync(path.join(root,f),'utf8');if(/\beval\s*\(|new Function\s*\(/.test(text))failures.push({file:f,error:'Dynamic code execution forbidden'});}
for(const loose of ['app.js','styles.css','data-schema.js','performance.js','features.js','final.css','commercial.css','garang-auth-bootstrap.js','garang-functional-recovery.js','garang-brand-runtime-v2.js','garang-polish-v3.js','garang-polish-v3-fix.js','garang-coach-home-hotfix.js','garang-mark.svg','garang-app-icon.svg','exercise-db.json','food-db.json'])if(fs.existsSync(path.join(root,loose)))failures.push({file:loose,error:'Loose root runtime duplicate forbidden'});
for(const required of ['06_features/ui/README.md','06_features/ui/i18n/translations.js','06_features/ui/i18n/runtime.js'])if(!fs.existsSync(path.join(root,required)))failures.push({file:required,error:'Missing UI/i18n source'});
const result={timestamp:new Date().toISOString(),status:failures.length?'FAIL':'PASS',counts,failures,scope:'Categorized runtime, JS/JSON syntax, active entry assets, shell IDs, i18n wiring, no loose root runtime duplicates.'};
fs.mkdirSync(path.join(root,'09_docs/qa-data'),{recursive:true});fs.writeFileSync(path.join(root,'09_docs/qa-data/final-static.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;
else if(process.argv.includes('--build')){const dist=path.join(root,'dist');fs.rmSync(dist,{recursive:true,force:true});for(const f of files){const relative=path.relative(root,f);if(relative.startsWith('tests'+path.sep)||relative.startsWith('scripts'+path.sep)||relative.startsWith('09_docs'+path.sep+'archive'+path.sep))continue;const to=path.join(dist,relative);fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(f,to);}console.log('Static build copied to dist');}
