'use strict';

const assert=require('node:assert/strict');
const {buildAgentContext,calculatePerformance,parseBearer}=require('../src/agent-context.cjs');
const {createAgentContextHandler}=require('../src/http-handler.cjs');
const ServerUserPerformance=require('../src/user-performance-model-v1.cjs');
const BrowserUserPerformance=require('../../02_core/user-performance-model-v1.js');
let passed=0;
async function test(name,run){await run();passed++;console.log(`PASS ${name}`);}
function response(){return {statusCode:null,body:null,headers:{},set(name,value){this.headers[name]=value;return this;},status(code){this.statusCode=code;return this;},json(body){this.body=body;return this;}};}
async function call(handler,{method='GET',authorization,query={}}={}){const res=response();await handler({method,headers:{authorization},query,get:name=>name.toLowerCase()==='authorization'?authorization:undefined},res);return res;}
(async()=>{
 await test('strict Bearer token parsing',()=>{assert.equal(parseBearer('Bearer token-1'),'token-1');assert.equal(parseBearer('Basic token-1'),null);assert.equal(parseBearer('Bearer two tokens'),null);});
 await test('missing authentication is rejected',async()=>{const handler=createAgentContextHandler({verifyIdToken:async()=>({uid:'never'}),readUser:async()=>({})}),res=await call(handler);assert.equal(res.statusCode,401);assert.equal(res.body.error.code,'UNAUTHENTICATED');});
 await test('invalid or expired token is rejected',async()=>{const handler=createAgentContextHandler({verifyIdToken:async()=>{throw new Error('expired');},readUser:async()=>({})}),res=await call(handler,{authorization:'Bearer expired'});assert.equal(res.statusCode,401);});
 await test('verified token uid is the only Firestore identity',async()=>{let requestedUid='';const handler=createAgentContextHandler({verifyIdToken:async token=>({uid:token==='valid'?'owner-uid':'wrong'}),readUser:async uid=>{requestedUid=uid;return {profile:{name:'Owner',goal:'5 km'}};},clock:()=>new Date('2026-09-02T00:00:00.000Z')}),res=await call(handler,{authorization:'Bearer valid',query:{uid:'attacker-uid'}});assert.equal(res.statusCode,200);assert.equal(requestedUid,'owner-uid');assert.equal(res.body.data.context.goal,'5 km');});
 await test('verified token uid also scopes memory before AI context',async()=>{const handler=createAgentContextHandler({verifyIdToken:async()=>({uid:'owner-uid'}),readUser:async()=>({memory:{entries:[{id:'mine',ownerUid:'owner-uid',type:'note',key:'mine',value:'visible',userConfirmed:true},{id:'other',ownerUid:'other-uid',type:'note',key:'other',value:'hidden',userConfirmed:true}]}}),clock:()=>new Date('2026-09-02T00:00:00.000Z')}),res=await call(handler,{authorization:'Bearer valid'});assert.equal(res.statusCode,200);assert.deepEqual(res.body.data.context.memory.entries.map(x=>x.id),['mine']);});
 await test('non-GET requests are rejected without data access',async()=>{let accessed=false;const handler=createAgentContextHandler({verifyIdToken:async()=>({uid:'owner'}),readUser:async()=>{accessed=true;return {};}}),res=await call(handler,{method:'POST',authorization:'Bearer valid'});assert.equal(res.statusCode,405);assert.equal(accessed,false);});
 await test('context uses only canonical persisted names',()=>{const context=buildAgentContext({schemaVersion:6,profile:{name:'가랑',goal:'체력 향상'},workouts:[{id:'w',date:'2026-09-01'}],meals:[{id:'m',date:'2026-09-01'}],runs:[{id:'r',date:'2026-09-01',coords:[[37.5,127]]}],body:[{id:'b',date:'2026-09-01',weight:70}],planner:[{id:'p',date:'2026-09-02'}],memory:{facts:['fact'],preferences:[],goals:[],events:[],entries:[]},aiChats:[{text:'secret chat'}],settings:{private:true},plan:'PRO'},{now:new Date('2026-09-02T00:00:00.000Z')});assert.equal(context.goal,'체력 향상');assert.equal(context.meals[0].id,'m');assert.equal(Object.hasOwn(context,'nutrition'),false);assert.equal(Object.hasOwn(context,'aiChats'),false);assert.equal(Object.hasOwn(context,'settings'),false);assert.equal(Object.hasOwn(context,'plan'),false);assert.equal(Object.hasOwn(context.runs[0],'coords'),false);assert.deepEqual(context.memory.facts,[]);});
 await test('performance score matches recording-v2 formula',()=>{const state={workouts:[{id:'w',sessionId:'s1',date:'2026-09-01'}],meals:[{id:'m',date:'2026-09-01'}],runs:[{id:'r',date:'2026-09-02'}],body:[{id:'b',date:'2026-09-01',weight:70}],planner:[{id:'p1',date:'2026-09-01',type:'recovery',done:true},{id:'p2',date:'2026-09-02',type:'recovery',done:false}]},score=calculatePerformance(state,'2026-09-02');assert.deepEqual(score,{exercise:8,nutrition:3,recovery:50,activity:10,body:33,total:21,coverage:5,date:'2026-09-02',formulaVersion:'recording-v2'});});
 await test('memory excludes deleted, unconfirmed and expired entries',()=>{const context=buildAgentContext({memory:{facts:[],preferences:[],goals:[],events:[],deletedIds:['deleted'],entries:[{id:'active',text:'keep',userConfirmed:true},{id:'deleted',text:'drop'},{id:'pending',text:'drop',userConfirmed:false},{id:'expired',text:'drop',expiresAt:'2026-09-01T00:00:00.000Z'}]}},{now:new Date('2026-09-02T00:00:00.000Z')});assert.deepEqual(context.memory.entries.map(item=>item.id),['active']);assert.equal(Object.hasOwn(context.memory,'deletedIds'),false);});
 await test('Agent context includes compact explainable user state and decision, not raw coordinates or chat',()=>{const context=buildAgentContext({profile:{goal:'10K'},workouts:[{id:'w1',sessionId:'s1',date:'2026-09-01',duration:60,rpe:7}],runs:[{id:'r1',date:'2026-09-01',distance:5,duration:30,coords:[[37,127]]}],dailyCheckins:[{date:'2026-09-02',sleepHours:5.5,energy:2,stress:4,soreness:{legs:4}}],memory:{entries:[]}},{now:new Date('2026-09-02T12:00:00Z')});assert.equal(context.userState.engineVersion,'state-intelligence-v1');assert.ok(context.userState.readiness);assert.ok(context.userState.fatigue);assert.ok(Array.isArray(context.userState.patterns));assert.equal(Object.hasOwn(context.userState,'daily'),false);assert.equal(context.decision.engineVersion,'decision-intelligence-v1');assert.equal(context.decision.guardrails.noSilentMutation,true);assert.equal(context.outcome.engineVersion,'plan-outcome-intelligence-v1');});
 await test('recent execution gaps suppress automatic progression while completed outcomes preserve it',()=>{const base={profile:{goal:'근육 증가'},workouts:Array.from({length:8},(_,i)=>({id:`w${i}`,sessionId:`s${i}`,date:`2026-09-${String(i+1).padStart(2,'0')}`,duration:45,rpe:6,weight:60,reps:8,sets:3})),dailyCheckins:[{date:'2026-09-14',sleepHours:8,energy:5,stress:1,soreness:{general:0}}],memory:{entries:[]},meta:{dailyPlanDrafts:{}}};const completed=structuredClone(base),missed=structuredClone(base);completed.meta.dailyPlanDrafts={'2026-09-12':{status:'finalized',result:'completed'},'2026-09-13':{status:'finalized',result:'completed'}};missed.meta.dailyPlanDrafts={'2026-09-12':{status:'finalized',result:'missed'},'2026-09-13':{status:'finalized',result:'partial'}};const a=buildAgentContext(completed,{now:new Date('2026-09-14T12:00:00Z')}),b=buildAgentContext(missed,{now:new Date('2026-09-14T12:00:00Z')});assert.equal(a.outcome.classification,'completed');assert.equal(b.outcome.classification,'partial');if(a.decision.mode==='progress')assert.equal(b.decision.mode,'maintain');assert.equal(b.decision.reasonCodes.includes('OUTCOME_PARTIAL'),true);assert.equal(b.decision.guardrails.noAutomaticProgressionAfterExecutionGap,true);});
 await test('recovery-constrained outcomes become deterministic decision evidence',()=>{const state={profile:{goal:'근육 증가'},dailyCheckins:[{date:'2026-09-14',sleepHours:7.5,energy:4,stress:2,soreness:{general:1}}],memory:{entries:[]},meta:{dailyPlanDrafts:{'2026-09-13':{status:'finalized',result:'recovery_constrained'}}}};const context=buildAgentContext(state,{now:new Date('2026-09-14T12:00:00Z')});assert.equal(context.outcome.classification,'recovery_constrained');assert.equal(context.decision.reasonCodes.includes('OUTCOME_RECOVERY_CONSTRAINED'),true);assert.equal(context.decision.signals.outcomeClassification,'recovery_constrained');});
 await test('server Agent context exposes only confidence-gated User Performance evidence and keeps it non-decisional',()=>{const state={onboarding:{weeklyFrequency:4},workouts:[{id:'w1',date:'2026-09-15'},{id:'w2',date:'2026-09-13'},{id:'w3',date:'2026-09-10'},{id:'w4',date:'2026-09-08'}],checkins:[{id:'c1',date:'2026-09-15',sleep:7.5,energy:4,stress:2,soreness:2},{id:'c2',date:'2026-09-13',sleep:7,energy:3,stress:2,soreness:2}],meals:[{id:'m1',date:'2026-09-15'},{id:'m2',date:'2026-09-14'},{id:'m3',date:'2026-09-13'}],planner:[{id:'p1',date:'2026-09-15',completed:true},{id:'p2',date:'2026-09-14',status:'missed'},{id:'p3',date:'2026-09-13',status:'completed'}],actionLog:[{id:'a1',at:'2026-09-15T08:00:00Z',event:'recommendation_accepted',recommendationId:'r1'},{id:'a2',at:'2026-09-14T08:00:00Z',event:'recommendation_rejected',recommendationId:'r2'},{id:'a3',at:'2026-09-13T08:00:00Z',event:'recommendation_dismissed',recommendationId:'r3'}],memory:{entries:[]}},before=JSON.stringify(state),context=buildAgentContext(state,{now:new Date('2026-09-17T12:00:00+09:00')});assert.equal(JSON.stringify(state),before);assert.equal(context.userPerformance.modelVersion,'user-performance-model-v1.0.0');assert.equal(context.userPerformance.minConfidence,0.5);assert.deepEqual(Object.keys(context.userPerformance.dimensions),['trainingConsistency']);assert.ok(context.userPerformance.withheldDimensions.some(row=>row.name==='recoveryStability'&&row.reason==='LOW_CONFIDENCE'));assert.ok(context.userPerformance.withheldDimensions.some(row=>row.name==='recommendationResponsiveness'&&row.reason==='LOW_CONFIDENCE'));assert.ok(context.userPerformance.withheldDimensions.some(row=>row.name==='attributedOutcomeScore'&&row.reason==='NO_VALUE'));assert.equal(context.userPerformance.guardrails.readOnly,true);assert.equal(context.userPerformance.guardrails.affectsDecision,false);assert.equal(context.userPerformance.guardrails.noDecisionMutation,true);assert.equal(context.userPerformance.guardrails.noAutomaticProgression,true);});
 await test('server User Performance model stays semantically identical to the browser model',()=>{const state={onboarding:{weeklyFrequency:3},workouts:[{id:'w1',date:'2026-09-15'},{id:'w2',date:'2026-09-12'},{id:'w3',date:'2026-09-09'},{id:'w4',date:'2026-09-06'}],dailyCheckins:[{id:'c1',date:'2026-09-15',sleepHours:7.2,energy:4,stress:2,soreness:{legs:2}},{id:'c2',date:'2026-09-12',sleepHours:6.8,energy:3,stress:3,soreness:{legs:3}}],meals:[{id:'m1',date:'2026-09-15'},{id:'m2',date:'2026-09-14'}],planner:[{id:'p1',date:'2026-09-15',status:'completed'},{id:'p2',date:'2026-09-14',status:'missed'}],actionLog:[{id:'a1',at:'2026-09-15T08:00:00Z',event:'recommendation_accepted',recommendationId:'r1'},{id:'a2',at:'2026-09-14T08:00:00Z',event:'recommendation_dismissed',recommendationId:'r2'}]},learningGraph={cycles:[{date:'2026-09-15',recommendationId:'r1',outcomeId:'o1',attribution:{complete:true},outcome:{classification:'completed',score:90}},{date:'2026-09-14',recommendationId:'r2',outcomeId:'o2',attribution:{complete:true},outcome:{classification:'partial',rate:60}}]},options={days:28,asOf:new Date('2026-09-17T12:00:00+09:00'),learningGraph},browser=BrowserUserPerformance.build(state,options),server=ServerUserPerformance.build(state,options);assert.deepEqual(server,browser);assert.deepEqual(ServerUserPerformance.compactForContext(server),BrowserUserPerformance.compactForContext(browser));});
 await test('empty user document produces a valid empty context and no fabricated plan decision',async()=>{const handler=createAgentContextHandler({verifyIdToken:async()=>({uid:'new-user'}),readUser:async()=>({}),clock:()=>new Date('2026-09-02T00:00:00.000Z')}),res=await call(handler,{authorization:'Bearer valid'});assert.equal(res.statusCode,200);assert.deepEqual(res.body.data.context.workouts,[]);assert.equal(res.body.data.context.performanceScore.total,null);assert.equal(res.body.data.context.userState.readiness.value,null);assert.equal(res.body.data.context.decision.mode,'collect_data');assert.equal(res.body.data.context.decision.actionProposal,null);});
 console.log(`${passed} agent context tests passed`);
})().catch(error=>{console.error(error);process.exitCode=1;});
