'use strict';
const assert=require('node:assert/strict');
const {createCoachGatewayHandler,minimalContext,normalizeStateForIntelligence}=require('../src/coach-gateway.cjs');
let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log(`PASS ${name}`);};
function res(){return {statusCode:200,payload:null,headers:{},status(code){this.statusCode=code;return this;},set(key,value){this.headers[key]=String(value);return this;},json(value){this.payload=value;return this;}};}
function state(goal='근육 증가',name='Owner Secret Name'){
 return {profile:{name,email:'hidden@example.com',goal},onboarding:{complete:true,goal},workouts:[{date:'2026-09-13',name:'벤치프레스',weight:80,reps:5,sets:5,notes:'private note'}],meals:[{date:'2026-09-13',name:'점심',kcal:700,protein:45,notes:'private'}],runs:[],body:[{date:'2026-09-10',weight:74.4,fatPercent:18.2,muscle:32.1},{date:'2026-09-12',weight:75,fatPercent:18,muscle:32.4}],checkins:[{date:'2026-09-14',sleep:5.5,energyLevel:2,stressLevel:4,muscleSoreness:3,availableMinutes:45}],dailyCheckins:[],planner:[],memory:{entries:[{id:'m1',type:'preference',key:'training_time',value:'evening',confidence:.9,importance:4,userConfirmed:true},{id:'m2',type:'note',key:'contact',value:'mail me owner@example.com',confidence:.9,importance:3,userConfirmed:true},{id:'m3',type:'identity',key:'display_name',value:'Owner Name',userConfirmed:true},{id:'m4',type:'note',value:'raw secret',userConfirmed:false}]}};
}
(async()=>{
 await test('gateway success uses authenticated normalized server context only',async()=>{
  let readUid=null,captured=null;const handler=createCoachGatewayHandler({verifyIdToken:async token=>{assert.equal(token,'owner-token');return {uid:'owner-1'};},readUser:async uid=>{readUid=uid;return state();},providerFactory:()=>({generate:async input=>{captured=input;return {answer:'회복 신호 때문에 낮추는 편이 좋습니다.',decisionSummary:'GARANG 판단 유지',reasoningSummary:'수면과 에너지가 낮습니다.',suggestedNextStep:'볼륨 조정',actionIntent:{type:'updatePlan'},confidence:.8,metadata:{provider:'mock'}};}}),getProviderConfig:()=>({}),observe:()=>{},clock:()=>new Date('2026-09-14T12:00:00Z')});
  const request={method:'POST',headers:{authorization:'Bearer owner-token'},body:{message:'오늘 벤치 세게 해도 돼?',uid:'victim',context:{profile:{goal:'러닝'},email:'victim@example.com'}},get(){return null;}},response=res();await handler(request,response);
  assert.equal(response.statusCode,200);assert.equal(response.payload.ok,true);assert.equal(response.payload.answer,response.payload.data.answer);assert.equal(readUid,'owner-1');assert.equal(captured.context.goal,'근육 증가');assert.ok(captured.context.garangDecision);assert.ok(captured.context.outcomeLearning);assert.equal(captured.context.recent.recoveryCheckin.sleepHours,5.5);assert.equal(captured.context.recent.recoveryCheckin.energy,2);assert.equal(captured.context.recent.recoveryCheckin.stress,4);assert.ok(captured.context.stateIntelligence.readiness.value!==null);assert.equal(response.payload.data.actionIntent,undefined);assert.deepEqual(captured.context.recent.bodyTrend,{fromDate:'2026-09-10',toDate:'2026-09-12',weightDelta:.6,fatPercentDelta:-.2,muscleDelta:.3});const serialized=JSON.stringify(captured.context);for(const secret of ['hidden@example.com','victim@example.com','owner@example.com','Owner Name'])assert.equal(serialized.includes(secret),false);
 });
 await test('same Coach question yields different deterministic decisions for different user state',async()=>{
  const question='오늘 벤치 세게 해도 돼?',contexts={};
  const ready={profile:{goal:'근육 증가'},checkins:[{date:'2026-09-14',sleep:8,energyLevel:5,stressLevel:1,muscleSoreness:0,availableMinutes:60}],dailyCheckins:[],workouts:[],meals:[],runs:[],body:[],planner:[],memory:{entries:[{id:'ready-goal',ownerUid:'ready-user',type:'goal',key:'primary_goal',value:'근육 증가',userConfirmed:true,confidence:.95,importance:5}]},meta:{syncOwnerUid:'ready-user',dailyPlanDrafts:{'2026-09-12':{status:'finalized',result:'completed'},'2026-09-13':{status:'finalized',result:'completed'}}}};
  const constrained={profile:{goal:'체지방 감소'},checkins:[{date:'2026-09-14',sleep:4.5,energyLevel:1,stressLevel:5,muscleSoreness:5,pain:true,availableMinutes:20}],dailyCheckins:[],workouts:[{date:'2026-09-13',name:'벤치프레스',duration:70,rpe:9,weight:90,reps:3,sets:6}],meals:[],runs:[],body:[],planner:[],memory:{entries:[{id:'constrained-goal',ownerUid:'constrained-user',type:'goal',key:'primary_goal',value:'체지방 감소',userConfirmed:true,confidence:.95,importance:5}]},meta:{syncOwnerUid:'constrained-user',dailyPlanDrafts:{'2026-09-12':{status:'finalized',result:'missed'},'2026-09-13':{status:'finalized',result:'partial'}}}};
  const users={'ready-user':ready,'constrained-user':constrained};
  const handler=createCoachGatewayHandler({verifyIdToken:async token=>({uid:token}),readUser:async uid=>users[uid],providerFactory:()=>({generate:async({context})=>{contexts[context.goal]=context;return {answer:'설명',decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',confidence:.5,metadata:{provider:'mock'}};}}),getProviderConfig:()=>({provider:'mock'}),observe:()=>{},clock:()=>new Date('2026-09-14T12:00:00Z')});
  for(const uid of ['ready-user','constrained-user']){const response=res();await handler({method:'POST',headers:{authorization:`Bearer ${uid}`},body:{message:question},get(){return null;}},response);assert.equal(response.statusCode,200);}
  const a=contexts['근육 증가'],b=contexts['체지방 감소'];assert.ok(a&&b);assert.equal(a.garangDecision.mode==='caution',false);assert.equal(b.garangDecision.mode,'caution');assert.notEqual(a.garangDecision.mode,b.garangDecision.mode);assert.notEqual(a.garangDecision.decisionId,b.garangDecision.decisionId);assert.equal(a.outcomeLearning.classification,'completed');assert.equal(b.outcomeLearning.classification,'partial');assert.equal(a.confirmedMemory.some(entry=>entry.value==='근육 증가'),true);assert.equal(b.confirmedMemory.some(entry=>entry.value==='체지방 감소'),true);
 });
 await test('cross-user context injection cannot select another user',async()=>{const reads=[];const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'user-a'}),readUser:async uid=>{reads.push(uid);return state('근육 증가');},providerFactory:()=>({generate:async({context})=>({answer:context.goal,decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',confidence:.5})}),getProviderConfig:()=>({}),observe:()=>{}});const response=res();await handler({method:'POST',headers:{authorization:'Bearer a'},body:{message:'x',uid:'user-b',context:{goal:'피해자 목표'}},get(){return null;}},response);assert.deepEqual(reads,['user-a']);assert.equal(response.payload.answer,'근육 증가');});
 await test('rate limit blocks state read and provider call with deterministic fallback',async()=>{let reads=0,generated=0;const events=[];const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),consumeRateLimit:async()=>({allowed:false,retryAfterSec:37,reason:'window'}),readUser:async()=>{reads++;return state();},providerFactory:()=>({generate:async()=>{generated++;return {};}}),observe:event=>events.push(event)});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'x'},get(){return null;}},response);assert.equal(response.statusCode,429);assert.equal(response.payload.error.code,'COACH_RATE_LIMITED');assert.equal(response.payload.fallbackRequired,true);assert.equal(response.headers['Retry-After'],'37');assert.equal(reads,0);assert.equal(generated,0);assert.equal(events[0].event,'llm_fallback');assert.equal(events[0].code,'COACH_RATE_LIMITED');});
 await test('quota-store failure fails closed before state or provider access',async()=>{let reads=0,generated=0;const events=[];const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),consumeRateLimit:async()=>{throw new Error('firestore unavailable');},readUser:async()=>{reads++;return state();},providerFactory:()=>({generate:async()=>{generated++;return {};}}),observe:event=>events.push(event)});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'x'},get(){return null;}},response);assert.equal(response.statusCode,503);assert.equal(response.payload.error.code,'COACH_RATE_LIMIT_UNAVAILABLE');assert.equal(response.payload.fallbackRequired,true);assert.equal(reads,0);assert.equal(generated,0);assert.equal(events[0].code,'COACH_RATE_LIMIT_UNAVAILABLE');});
 await test('provider failure requests deterministic fallback without fabricating LLM success',async()=>{const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>({generate:async()=>{const e=new Error('timeout');e.code='LLM_TIMEOUT';throw e;}}),getProviderConfig:()=>({}),observe:()=>{}});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'x'},get(){return null;}},response);assert.equal(response.statusCode,502);assert.equal(response.payload.ok,false);assert.equal(response.payload.fallbackRequired,true);assert.equal(response.payload.error.code,'LLM_TIMEOUT');assert.ok(response.payload.garangDecision);});
 await test('missing provider secret remains explicit and non-success',async()=>{const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>{const e=new Error('missing');e.code='LLM_SECRET_MISSING';throw e;},getProviderConfig:()=>({}),observe:()=>{}});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'x'},get(){return null;}},response);assert.equal(response.statusCode,503);assert.equal(response.payload.error.code,'LLM_SECRET_MISSING');assert.equal(response.payload.fallbackRequired,true);});
 await test('provider cannot return an action contract or mutation result',async()=>{const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>({generate:async()=>({answer:'제안',decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',actionIntent:{type:'createPlan'},writeResult:{id:'forbidden'},confidence:.8})}),getProviderConfig:()=>({}),observe:()=>{}});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'계획 바꿔줘'},get(){return null;}},response);assert.equal(response.statusCode,200);assert.equal(response.payload.data.actionIntent,undefined);assert.equal(response.payload.data.writeResult,undefined);assert.equal(response.payload.data.source,'llm');});
 await test('LLM confidence cannot exceed deterministic GARANG confidence and events omit raw context',async()=>{const events=[];const privateMessage='오늘 벤치 세게 해도 돼? private@example.com';const constrained=state();constrained.meta={dailyPlanDrafts:{'2026-09-12':{status:'finalized',result:'missed'},'2026-09-13':{status:'finalized',result:'partial'}}};const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>constrained,providerFactory:()=>({generate:async()=>({answer:'설명',decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',confidence:.99,metadata:{provider:'mock'}})}),getProviderConfig:()=>({provider:'mock'}),observe:event=>events.push(event),clock:()=>new Date('2026-09-14T12:00:00Z')});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:privateMessage},get(){return null;}},response);assert.equal(response.statusCode,200);assert.ok(response.payload.data.confidence<=response.payload.data.garangDecision.confidence);assert.equal(response.payload.data.metadata.alignment.confidenceCapped,true);assert.equal(response.payload.data.metadata.alignment.outcomeClassification,'partial');assert.deepEqual(events.map(event=>event.event),['llm_request','llm_success']);const logged=JSON.stringify(events);assert.equal(logged.includes(privateMessage),false);assert.equal(logged.includes('private@example.com'),false);assert.equal(logged.includes('confirmedMemory'),false);});
 await test('fallback observability distinguishes provider rate error without logging message or context',async()=>{const events=[];const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>({generate:async()=>{const error=new Error('provider');error.code='LLM_PROVIDER_ERROR';error.status=429;throw error;}}),getProviderConfig:()=>({provider:'openai'}),observe:event=>events.push(event)});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'sensitive prompt'},get(){return null;}},response);assert.equal(response.statusCode,502);assert.equal(events.at(-1).event,'llm_fallback');assert.equal(events.at(-1).code,'LLM_PROVIDER_ERROR');assert.equal(events.at(-1).providerStatus,429);assert.equal(JSON.stringify(events).includes('sensitive prompt'),false);});
 await test('legacy checkin aliases are canonicalized without hiding current recovery evidence',()=>{const normalized=normalizeStateForIntelligence({dailyCheckins:[],checkins:[{date:'2026-09-14',sleep:6.25,energyLevel:3,stressLevel:4,muscleSoreness:2,pain:true,availableMinutes:35}]});assert.equal(normalized.dailyCheckins.length,1);assert.equal(normalized.checkins.length,1);const check=normalized.checkins[0];assert.equal(check.sleepHours,6.25);assert.equal(check.energy,3);assert.equal(check.stress,4);assert.deepEqual(check.soreness,{overall:2});assert.equal(check.painCaution,true);});
 await test('minimal context excludes direct identity and free-text note fields',()=>{const ctx=minimalContext({goal:'g',memory:{entries:[{type:'preference',key:'k',value:'v',userConfirmed:true},{type:'identity',key:'display_name',value:'Person'}]},workouts:[{name:'Bench',notes:'secret'}],body:[{date:'2026-09-10',weight:70},{date:'2026-09-14',weight:70.5}],outcome:{classification:'partial',confidence:.5},decision:{mode:'reduce',reasonCodes:['LOW_SLEEP']}},{checkins:[{date:'2026-09-14',sleepHours:6}]});const text=JSON.stringify(ctx);assert.equal(text.includes('notes'),false);assert.equal(text.includes('Person'),false);assert.equal(text.includes('email'),false);assert.equal(ctx.recent.recoveryCheckin.sleepHours,6);assert.equal(ctx.recent.bodyTrend.weightDelta,.5);assert.equal(ctx.decisionReasons[0],'LOW_SLEEP');assert.equal(ctx.outcomeLearning.classification,'partial');});
 console.log(`${passed} coach gateway tests passed`);
})().catch(error=>{console.error(error);process.exitCode=1;});
