'use strict';
const assert=require('node:assert/strict');
const {createCoachGatewayHandler,minimalContext}=require('../src/coach-gateway.cjs');
let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log(`PASS ${name}`);};
function res(){return {statusCode:200,payload:null,status(code){this.statusCode=code;return this;},json(value){this.payload=value;return this;}};}
function state(goal='근육 증가',name='Owner Secret Name'){
 return {profile:{name,email:'hidden@example.com',goal},onboarding:{complete:true,goal},workouts:[{date:'2026-09-13',name:'벤치프레스',weight:80,reps:5,sets:5,notes:'private note'}],meals:[{date:'2026-09-13',name:'점심',kcal:700,protein:45,notes:'private'}],runs:[],body:[{date:'2026-09-10',weight:74.4,fatPercent:18.2,muscle:32.1},{date:'2026-09-12',weight:75,fatPercent:18,muscle:32.4}],checkins:[{date:'2026-09-14',sleep:5.5,energy:2,stress:4,soreness:3,availableMinutes:45}],dailyCheckins:[],planner:[],memory:{entries:[{id:'m1',type:'preference',key:'training_time',value:'evening',confidence:.9,importance:4,userConfirmed:true},{id:'m2',type:'note',key:'contact',value:'mail me owner@example.com',confidence:.9,importance:3,userConfirmed:true},{id:'m3',type:'identity',key:'display_name',value:'Owner Name',userConfirmed:true},{id:'m4',type:'note',value:'raw secret',userConfirmed:false}]}};
}
(async()=>{
 await test('gateway success uses authenticated server context only',async()=>{
  let readUid=null,captured=null;const handler=createCoachGatewayHandler({verifyIdToken:async token=>{assert.equal(token,'owner-token');return {uid:'owner-1'};},readUser:async uid=>{readUid=uid;return state();},providerFactory:()=>({generate:async input=>{captured=input;return {answer:'회복 신호 때문에 낮추는 편이 좋습니다.',decisionSummary:'GARANG 판단 유지',reasoningSummary:'수면과 에너지가 낮습니다.',suggestedNextStep:'볼륨 조정',actionIntent:{type:'updatePlan'},confidence:.8,metadata:{provider:'mock'}};}}),getProviderConfig:()=>({}),observe:()=>{},clock:()=>new Date('2026-09-14T12:00:00Z')});
  const request={method:'POST',headers:{authorization:'Bearer owner-token'},body:{message:'오늘 벤치 세게 해도 돼?',uid:'victim',context:{profile:{goal:'러닝'},email:'victim@example.com'}},get(){return null;}},response=res();await handler(request,response);
  assert.equal(response.statusCode,200);assert.equal(response.payload.ok,true);assert.equal(response.payload.answer,response.payload.data.answer);assert.equal(readUid,'owner-1');assert.equal(captured.context.goal,'근육 증가');assert.ok(captured.context.garangDecision,'GARANG decision must be computed before provider invocation');assert.ok(captured.context.outcomeLearning,'outcome learning must be available before provider invocation');assert.equal(captured.context.recent.recoveryCheckin.sleep,5.5);assert.equal(captured.context.recent.recoveryCheckin.energy,2);assert.deepEqual(captured.context.recent.bodyTrend,{fromDate:'2026-09-10',toDate:'2026-09-12',weightDelta:.6,fatPercentDelta:-.2,muscleDelta:.3});assert.equal(captured.context.email,undefined);const serialized=JSON.stringify(captured.context);assert.equal(serialized.includes('hidden@example.com'),false);assert.equal(serialized.includes('victim@example.com'),false);assert.equal(serialized.includes('owner@example.com'),false);assert.equal(serialized.includes('Owner Name'),false);
 });
 await test('cross-user context injection cannot select another user',async()=>{const reads=[];const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'user-a'}),readUser:async uid=>{reads.push(uid);return state('근육 증가');},providerFactory:()=>({generate:async({context})=>({answer:context.goal,decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',actionIntent:{type:'none'},confidence:.5})}),getProviderConfig:()=>({}),observe:()=>{}});const response=res();await handler({method:'POST',headers:{authorization:'Bearer a'},body:{message:'x',uid:'user-b',context:{goal:'피해자 목표'}},get(){return null;}},response);assert.deepEqual(reads,['user-a']);assert.equal(response.payload.answer,'근육 증가');});
 await test('provider failure requests deterministic fallback without fabricating LLM success',async()=>{const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>({generate:async()=>{const e=new Error('timeout');e.code='LLM_TIMEOUT';throw e;}}),getProviderConfig:()=>({}),observe:()=>{}});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'x'},get(){return null;}},response);assert.equal(response.statusCode,502);assert.equal(response.payload.ok,false);assert.equal(response.payload.fallbackRequired,true);assert.equal(response.payload.error.code,'LLM_TIMEOUT');assert.ok(response.payload.garangDecision);});
 await test('missing provider secret remains explicit and non-success',async()=>{const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>{const e=new Error('missing');e.code='LLM_SECRET_MISSING';throw e;},getProviderConfig:()=>({}),observe:()=>{}});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'x'},get(){return null;}},response);assert.equal(response.statusCode,503);assert.equal(response.payload.error.code,'LLM_SECRET_MISSING');assert.equal(response.payload.fallbackRequired,true);});
 await test('gateway has no mutation dependency and LLM action intent is advisory only',async()=>{let generated=0;const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>({generate:async()=>{generated++;return {answer:'제안',decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',actionIntent:{type:'createPlan'},confidence:.8};}}),getProviderConfig:()=>({}),observe:()=>{}});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'계획 바꿔줘'},get(){return null;}},response);assert.equal(generated,1);assert.equal(response.payload.data.actionIntent.type,'createPlan');assert.equal(response.payload.data.source,'llm');assert.equal('writeResult' in response.payload.data,false);});
 await test('LLM confidence cannot exceed deterministic GARANG confidence and events omit raw context',async()=>{const events=[];const privateMessage='오늘 벤치 세게 해도 돼? private@example.com';const constrained=state();constrained.meta={dailyPlanDrafts:{'2026-09-12':{status:'finalized',result:'missed'},'2026-09-13':{status:'finalized',result:'partial'}}};const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>constrained,providerFactory:()=>({generate:async()=>({answer:'설명',decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',actionIntent:{type:'none'},confidence:.99,metadata:{provider:'mock'}})}),getProviderConfig:()=>({provider:'mock'}),observe:event=>events.push(event),clock:()=>new Date('2026-09-14T12:00:00Z')});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:privateMessage},get(){return null;}},response);assert.equal(response.statusCode,200);assert.ok(response.payload.data.confidence<=response.payload.data.garangDecision.confidence);assert.equal(response.payload.data.metadata.alignment.confidenceCapped,true);assert.equal(response.payload.data.metadata.alignment.outcomeClassification,'partial');assert.deepEqual(events.map(event=>event.event),['llm_request','llm_success']);const logged=JSON.stringify(events);assert.equal(logged.includes(privateMessage),false);assert.equal(logged.includes('private@example.com'),false);assert.equal(logged.includes('confirmedMemory'),false);});
 await test('fallback observability distinguishes provider error without logging message or context',async()=>{const events=[];const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>({generate:async()=>{const error=new Error('provider');error.code='LLM_PROVIDER_ERROR';error.status=429;throw error;}}),getProviderConfig:()=>({provider:'openai'}),observe:event=>events.push(event)});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'sensitive prompt'},get(){return null;}},response);assert.equal(response.statusCode,502);assert.equal(events.at(-1).event,'llm_fallback');assert.equal(events.at(-1).code,'LLM_PROVIDER_ERROR');assert.equal(events.at(-1).providerStatus,429);assert.equal(JSON.stringify(events).includes('sensitive prompt'),false);});
 await test('minimal context excludes direct identity and free-text note fields',()=>{const ctx=minimalContext({goal:'g',memory:{entries:[{type:'preference',key:'k',value:'v',userConfirmed:true},{type:'identity',key:'display_name',value:'Person'}]},workouts:[{name:'Bench',notes:'secret'}],body:[{date:'2026-09-10',weight:70},{date:'2026-09-14',weight:70.5}],outcome:{classification:'partial',confidence:.5},decision:{mode:'reduce',reasonCodes:['LOW_SLEEP']}},{checkins:[{date:'2026-09-14',sleep:6}]});const text=JSON.stringify(ctx);assert.equal(text.includes('notes'),false);assert.equal(text.includes('Person'),false);assert.equal(text.includes('email'),false);assert.equal(ctx.recent.recoveryCheckin.sleep,6);assert.equal(ctx.recent.bodyTrend.weightDelta,.5);assert.equal(ctx.decisionReasons[0],'LOW_SLEEP');assert.equal(ctx.outcomeLearning.classification,'partial');});
 console.log(`${passed} coach gateway tests passed`);
})().catch(error=>{console.error(error);process.exitCode=1;});
