'use strict';
const assert=require('node:assert/strict');
const {createCoachGatewayHandler,minimalContext}=require('../src/coach-gateway.cjs');
let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log(`PASS ${name}`);};
function res(){return {statusCode:200,payload:null,status(code){this.statusCode=code;return this;},json(value){this.payload=value;return this;}};}
function state(goal='근육 증가',name='Owner Secret Name'){
 return {profile:{name,email:'hidden@example.com',goal},onboarding:{complete:true,goal},workouts:[{date:'2026-09-13',name:'벤치프레스',weight:80,reps:5,sets:5,notes:'private note'}],meals:[{date:'2026-09-13',name:'점심',kcal:700,protein:45,notes:'private'}],runs:[],body:[{date:'2026-09-12',weight:75}],checkins:[{date:'2026-09-14',sleep:5.5,energy:2,stress:4,soreness:3,availableMinutes:45}],dailyCheckins:[],planner:[],memory:{entries:[{id:'m1',type:'preference',key:'training_time',value:'evening',confidence:.9,importance:4,userConfirmed:true},{id:'m2',type:'note',key:'contact',value:'mail me owner@example.com',confidence:.9,importance:3,userConfirmed:true},{id:'m3',type:'identity',key:'display_name',value:'Owner Name',userConfirmed:true},{id:'m4',type:'note',value:'raw secret',userConfirmed:false}]}};
}
(async()=>{
 await test('gateway success uses authenticated server context only',async()=>{
  let readUid=null,captured=null;const handler=createCoachGatewayHandler({verifyIdToken:async token=>{assert.equal(token,'owner-token');return {uid:'owner-1'};},readUser:async uid=>{readUid=uid;return state();},providerFactory:()=>({generate:async input=>{captured=input;return {answer:'회복 신호 때문에 낮추는 편이 좋습니다.',decisionSummary:'GARANG 판단 유지',reasoningSummary:'수면과 에너지가 낮습니다.',suggestedNextStep:'볼륨 조정',actionIntent:{type:'updatePlan'},confidence:.8,metadata:{provider:'mock'}};}}),getProviderConfig:()=>({}),clock:()=>new Date('2026-09-14T12:00:00Z')});
  const request={method:'POST',headers:{authorization:'Bearer owner-token'},body:{message:'오늘 벤치 세게 해도 돼?',uid:'victim',context:{profile:{goal:'러닝'},email:'victim@example.com'}},get(){return null;}},response=res();await handler(request,response);
  assert.equal(response.statusCode,200);assert.equal(response.payload.ok,true);assert.equal(response.payload.answer,response.payload.data.answer);assert.equal(readUid,'owner-1');assert.equal(captured.context.goal,'근육 증가');assert.ok(captured.context.garangDecision,'GARANG decision must be computed before provider invocation');assert.equal(captured.context.recent.recoveryCheckin.sleep,5.5);assert.equal(captured.context.recent.recoveryCheckin.energy,2);assert.equal(captured.context.email,undefined);const serialized=JSON.stringify(captured.context);assert.equal(serialized.includes('hidden@example.com'),false);assert.equal(serialized.includes('victim@example.com'),false);assert.equal(serialized.includes('owner@example.com'),false);assert.equal(serialized.includes('Owner Name'),false);
 });
 await test('cross-user context injection cannot select another user',async()=>{const reads=[];const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'user-a'}),readUser:async uid=>{reads.push(uid);return state('근육 증가');},providerFactory:()=>({generate:async({context})=>({answer:context.goal,decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',actionIntent:{type:'none'},confidence:.5})}),getProviderConfig:()=>({})});const response=res();await handler({method:'POST',headers:{authorization:'Bearer a'},body:{message:'x',uid:'user-b',context:{goal:'피해자 목표'}},get(){return null;}},response);assert.deepEqual(reads,['user-a']);assert.equal(response.payload.answer,'근육 증가');});
 await test('provider failure requests deterministic fallback without fabricating LLM success',async()=>{const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>({generate:async()=>{const e=new Error('timeout');e.code='LLM_TIMEOUT';throw e;}}),getProviderConfig:()=>({})});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'x'},get(){return null;}},response);assert.equal(response.statusCode,502);assert.equal(response.payload.ok,false);assert.equal(response.payload.fallbackRequired,true);assert.equal(response.payload.error.code,'LLM_TIMEOUT');assert.ok(response.payload.garangDecision);});
 await test('missing provider secret remains explicit and non-success',async()=>{const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>{const e=new Error('missing');e.code='LLM_SECRET_MISSING';throw e;},getProviderConfig:()=>({})});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'x'},get(){return null;}},response);assert.equal(response.statusCode,503);assert.equal(response.payload.error.code,'LLM_SECRET_MISSING');assert.equal(response.payload.fallbackRequired,true);});
 await test('gateway has no mutation dependency and LLM action intent is advisory only',async()=>{let generated=0;const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u'}),readUser:async()=>state(),providerFactory:()=>({generate:async()=>{generated++;return {answer:'제안',decisionSummary:'d',reasoningSummary:'r',suggestedNextStep:'s',actionIntent:{type:'createPlan'},confidence:.8};}}),getProviderConfig:()=>({})});const response=res();await handler({method:'POST',headers:{authorization:'Bearer t'},body:{message:'계획 바꿔줘'},get(){return null;}},response);assert.equal(generated,1);assert.equal(response.payload.data.actionIntent.type,'createPlan');assert.equal(response.payload.data.source,'llm');assert.equal('writeResult' in response.payload.data,false);});
 await test('minimal context excludes direct identity and free-text note fields',()=>{const ctx=minimalContext({goal:'g',memory:{entries:[{type:'preference',key:'k',value:'v',userConfirmed:true},{type:'identity',key:'display_name',value:'Person'}]},workouts:[{name:'Bench',notes:'secret'}],decision:{mode:'reduce',reasonCodes:['LOW_SLEEP']}},{checkins:[{date:'2026-09-14',sleep:6}]});const text=JSON.stringify(ctx);assert.equal(text.includes('notes'),false);assert.equal(text.includes('Person'),false);assert.equal(text.includes('email'),false);assert.equal(ctx.recent.recoveryCheckin.sleep,6);assert.equal(ctx.decisionReasons[0],'LOW_SLEEP');});
 console.log(`${passed} coach gateway tests passed`);
})().catch(error=>{console.error(error);process.exitCode=1;});
