'use strict';
const assert=require('node:assert/strict');
const CoreNutrition=require('../../02_core/nutrition-intelligence-v2.js');
const CoreGrounding=require('../../02_core/coach-knowledge-grounding-v2.js');
const ServerNutrition=require('../src/nutrition-intelligence-v2.cjs');
const ServerGrounding=require('../src/coach-knowledge-grounding-v2.cjs');
const {RULES}=require('../src/coach-knowledge-v2.cjs');
const {buildGroundedContext,validateGroundingContext,createCoachGatewayHandler}=require('../src/coach-gateway.cjs');
let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log(`PASS ${name}`);};
function state(){return {profile:{goal:'근육 증가',weight:72,height:175,age:29,gender:'male'},workouts:[{date:'2026-09-15',name:'벤치프레스',sets:4,reps:8,weight:80}],runs:[],meals:[{date:'2026-09-15',name:'아침',kcal:420,protein:22,carbs:45,fat:12}],body:[{date:'2026-09-15',weight:72}],planner:[],dailyCheckins:[{date:'2026-09-15',sleepHours:7.5,energy:4,stress:2,soreness:2}],checkins:[],memory:{entries:[]},meta:{syncOwnerUid:'u1'}};}
function full(decision={decisionId:'d-progress-1',mode:'progress',confidence:.8,reasonCodes:['MODE_PROGRESS','CHECKIN_STABLE']}){return {goal:'근육 증가',memory:{entries:[]},workouts:state().workouts,meals:state().meals,runs:[],body:state().body,planner:[],userState:{readiness:{band:'high',value:85,reasons:['CHECKIN_STABLE']},fatigue:{band:'low',score:20,reasons:[]}},performanceScore:{total:75},outcome:{classification:'completed'},decision};}
function res(){return {statusCode:200,payload:null,headers:{},status(code){this.statusCode=code;return this;},set(key,value){this.headers[key]=String(value);return this;},json(value){this.payload=value;return this;}};}
(async()=>{
 await test('server Nutrition Intelligence matches core contract for canonical state',()=>{const input=state(),options={now:new Date('2026-09-15T12:00:00Z')};assert.deepEqual(ServerNutrition.interpret(input,options),CoreNutrition.interpret(input,options));});
 await test('server grounding matches core selection contract for same evidence',()=>{const input={decision:full().decision,userState:full().userState,nutrition:ServerNutrition.interpret(state(),{now:new Date('2026-09-15T12:00:00Z')}),query:'오늘 벤치 세게 하고 단백질도 챙길까?',coachRules:RULES,limit:5};assert.deepEqual(ServerGrounding.ground(input),CoreGrounding.ground(input));});
 await test('grounded context keeps GARANG decision ownership and is mutation-disabled',()=>{const context=buildGroundedContext(full(),state(),{query:'오늘 벤치 세게 해도 돼?',now:new Date('2026-09-15T12:00:00Z')});assert.equal(context.knowledgeGrounding.decisionIdentity.decisionId,context.garangDecision.decisionId);assert.equal(context.knowledgeGrounding.decisionIdentity.mode,context.garangDecision.mode);assert.equal(context.knowledgeGrounding.contract.decisionOwnedBy,'GARANG');assert.equal(context.knowledgeGrounding.contract.llmRole,'explain_only');assert.equal(context.knowledgeGrounding.contract.stateMutationAllowed,false);assert.ok(context.knowledgeGrounding.evidenceCount>0);assert.ok(context.nutritionIntelligence.mode);assert.equal(validateGroundingContext(context),true);});
 await test('grounding contract fails closed on decision identity drift',()=>{const context=buildGroundedContext(full(),state(),{query:'회복',now:new Date('2026-09-15T12:00:00Z')});context.knowledgeGrounding.decisionIdentity.decisionId='invented';assert.throws(()=>validateGroundingContext(context),error=>error?.code==='GROUNDING_DECISION_MISMATCH');});
 await test('high recovery stress becomes deterministic recovery_support nutrition mode',()=>{const input=state();input.dailyCheckins=[{date:'2026-09-15',sleepHours:4.5,energy:2,stress:9,soreness:8}];const out=ServerNutrition.interpret(input,{now:new Date('2026-09-15T12:00:00Z')});assert.equal(out.mode,'recovery_support');assert.ok(out.reasonCodes.includes('SHORT_SLEEP'));assert.ok(out.reasonCodes.includes('RECOVERY_SIGNAL_PRIORITY'));});
 await test('Coach gateway sends grounded nutrition context to provider and exposes safe grounding metadata',async()=>{let captured=null;const handler=createCoachGatewayHandler({verifyIdToken:async()=>({uid:'u1'}),readUser:async()=>state(),consumeRateLimit:async()=>({allowed:true}),providerFactory:()=>({generate:async input=>{captured=input;const d=input.context.garangDecision;return {answer:'GARANG 판단을 기준으로 설명합니다.',decisionSummary:'판단 유지',reasoningSummary:'기록과 grounding evidence를 사용했습니다.',suggestedNextStep:'다음 기록을 이어가세요.',confidence:.9,alignment:{decisionId:d.decisionId,decisionMode:d.mode,reasonCodesUsed:[]},metadata:{provider:'mock'}};}}),getProviderConfig:()=>({provider:'mock'}),observe:()=>{},clock:()=>new Date('2026-09-15T12:00:00Z')});const response=res();await handler({method:'POST',headers:{authorization:'Bearer token'},body:{message:'오늘 운동이랑 식단 어떻게 가져갈까?'},get(){return null;}},response);assert.equal(response.statusCode,200);assert.ok(captured.context.nutritionIntelligence);assert.ok(captured.context.knowledgeGrounding);assert.equal(captured.context.knowledgeGrounding.contract.stateMutationAllowed,false);assert.equal(response.payload.data.metadata.grounding.contractVerified,true);assert.equal(response.payload.data.metadata.grounding.decisionOwnedBy,'GARANG');assert.ok(response.payload.data.metadata.grounding.evidenceCount>=0);const serialized=JSON.stringify(captured.context);assert.equal(serialized.includes('Bearer token'),false);});
 console.log(`${passed} live Coach grounding v2 tests passed`);
})().catch(error=>{console.error(error);process.exitCode=1;});
