'use strict';
const assert=require('node:assert/strict');
const {summarizeOutcomeLearning}=require('../src/outcome-learning-v2.cjs');
const ServerDecision=require('../src/decision-intelligence.cjs');
const BrowserDecision=require('../../02_core/decision-intelligence-v1.js');

let passed=0;const test=(name,fn)=>{fn();passed++;console.log(`PASS ${name}`);};
const now=new Date('2026-09-14T12:00:00Z');
const draft=result=>({status:'finalized',result});
function stateFrom(entries){return {meta:{dailyPlanDrafts:Object.fromEntries(entries.map(([date,result])=>[date,draft(result)]))}};}
function readyState(){return {engineVersion:'state-intelligence-v1',asOf:'2026-09-14',confidence:.8,readiness:{value:90,band:'high',confidence:.9,reasons:['CHECKIN_STABLE']},fatigue:{score:18,band:'low',confidence:.8,reasons:['NO_FATIGUE_CLUSTER']},load:{ratio:1.05,band:'stable',confidence:.8},patterns:[],goalAlignment:{score:85,band:'aligned',confidence:.8}};}

test('longitudinal learning is read-only and preserves recent v1 contract',()=>{const state=stateFrom([['2026-09-12','completed'],['2026-09-13','completed']]),before=JSON.stringify(state),out=summarizeOutcomeLearning(state,{now});assert.equal(out.engineVersion,'plan-outcome-intelligence-v1');assert.equal(out.learningVersion,'outcome-learning-v2');assert.equal(out.classification,'completed');assert.equal(out.longitudinal.classification,'insufficient_longitudinal_evidence');assert.equal(JSON.stringify(state),before);assert.equal(out.guardrails.noAutomaticProgressionIncrease,true);});
test('missing outcome rates are not learned as missed execution',()=>{const out=summarizeOutcomeLearning({meta:{dailyPlanDrafts:{'2026-09-01':{status:'finalized',outcome:{domains:{training:{rate:null},recovery:{rate:''}}}}}}},{now});assert.equal(out.longitudinal.sampleDays,0);assert.equal(out.longitudinal.classification,'insufficient_longitudinal_evidence');});
test('repeated execution gaps become a longitudinal fragile-execution signal',()=>{const out=summarizeOutcomeLearning(stateFrom([['2026-09-01','missed'],['2026-09-02','partial'],['2026-09-03','missed'],['2026-09-04','partial'],['2026-09-12','completed'],['2026-09-13','completed']]),{now});assert.equal(out.classification,'completed');assert.equal(out.longitudinal.classification,'fragile_execution');assert.equal(out.decisionSupport.suppressProgression,true);assert.equal(out.decisionSupport.automaticProgressionIncrease,false);});
test('repeated recovery constraints become conservative decision support',()=>{const out=summarizeOutcomeLearning(stateFrom([['2026-09-01','recovery_constrained'],['2026-09-03','recovery_constrained'],['2026-09-05','completed'],['2026-09-07','completed'],['2026-09-12','completed'],['2026-09-13','completed']]),{now});assert.equal(out.longitudinal.classification,'recovery_constrained_pattern');assert.equal(out.decisionSupport.preferReducedLoad,true);assert.equal(out.decisionSupport.suppressProgression,true);});
test('stable execution never creates automatic progression by itself',()=>{const out=summarizeOutcomeLearning(stateFrom([['2026-09-01','completed'],['2026-09-03','completed'],['2026-09-05','completed'],['2026-09-08','completed'],['2026-09-12','completed'],['2026-09-13','completed']]),{now});assert.equal(out.longitudinal.classification,'stable_execution');assert.equal(out.decisionSupport.suppressProgression,false);assert.equal(out.decisionSupport.preferReducedLoad,false);assert.equal(out.decisionSupport.automaticProgressionIncrease,false);});
test('longitudinal execution gaps can suppress a recent completed progression candidate',()=>{const outcome=summarizeOutcomeLearning(stateFrom([['2026-09-01','missed'],['2026-09-02','partial'],['2026-09-03','missed'],['2026-09-04','partial'],['2026-09-12','completed'],['2026-09-13','completed']]),{now}),server=ServerDecision.decide(readyState(),{outcomeContext:outcome}),browser=BrowserDecision.decide(readyState(),{outcomeContext:outcome});assert.equal(outcome.classification,'completed');assert.equal(server.mode,'maintain');assert.equal(server.reasonCodes.includes('OUTCOME_LONGITUDINAL_EXECUTION_GAP'),true);assert.equal(server.guardrails.longitudinalLearningCanOnlyConstrainProgression,true);assert.deepEqual(server,browser);});
test('longitudinal recovery pattern can prefer reduced load with identical browser/server policy',()=>{const outcome=summarizeOutcomeLearning(stateFrom([['2026-09-01','recovery_constrained'],['2026-09-03','recovery_constrained'],['2026-09-05','completed'],['2026-09-07','completed'],['2026-09-12','completed'],['2026-09-13','completed']]),{now}),server=ServerDecision.decide(readyState(),{outcomeContext:outcome}),browser=BrowserDecision.decide(readyState(),{outcomeContext:outcome});assert.equal(server.mode,'reduce');assert.equal(server.reasonCodes.includes('OUTCOME_LONGITUDINAL_RECOVERY_CONSTRAINT'),true);assert.deepEqual(server,browser);});
console.log(`${passed} outcome learning v2 tests passed`);
